### ISSUE TITLE
Modify acknowledgments in README and docs

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#1004]
### Description

This task is to remove the mandatory acknowledgments in the past to comply with the project's initial co-sponsor.

1. Replace the current README file with the new one from this gist: https://gist.github.com/krzysztofspilka/1977d61b4a68b2631562b814d30637aa

2. Remove the [acknowledgments](https://handsontable.github.io/hyperformula/guide/acknowledgements.html) page from the docs.

**Comment by krzysztofspilka** [comment]
@warpech please review

**Comment by sequba** [comment]
Released in **2.0.1**
