### ISSUE TITLE
Reduce bundle size of HyperFormula

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1006]
### Description

[hot-formula-parser](https://www.npmjs.com/package/hot-formula-parser) has a significantly smaller bundle size than HyperFormula.

We should investigate possibilities of reducing it, e.g.:
- remove some dependencies (like `regenerator-runtime`)
- add tree-shaking support for applications that use only a small set of features

### Links

- https://github.com/handsontable/hyperformula/discussions/1003
- https://bundlephobia.com/package/hyperformula@2.0.0
- https://bundlephobia.com/package/hot-formula-parser@4.0.0

<img width="2262" alt="Screen Shot 2022-06-08 at 2 52 20 PM" src="https://user-images.githubusercontent.com/566463/172621129-850ffdee-a339-42ba-a8ab-34aac8b85068.png">

<img width="2107" alt="Screen Shot 2022-06-08 at 2 57 37 PM" src="https://user-images.githubusercontent.com/566463/172622124-0f75a02c-31b5-4820-87eb-b3b6dcd2760f.png">

**Comment by sequba** [comment]
When completed, please re-verify https://github.com/handsontable/handsontable/issues/8118.

**Comment by krzysztofspilka** [comment]
Thanks!
