### ISSUE TITLE
Replace the license

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#1015]
### Description

For commercial use, our proprietary license replaces the open-source terms which gives us an opportunity to better communicate the open-source character of HyperFormula. We could do that by replacing the content of the [LICENSE.txt](https://github.com/handsontable/hyperformula/blob/master/LICENSE.txt) file with the content already existing in [gpl-3.0.txt](https://github.com/handsontable/hyperformula/blob/master/gpl-3.0.txt).

Both GitHub and npm should properly detect, and display the new license.

The file "gpl-3.0.txt" should be then deleted.

<img width="189" alt="Screenshot 2022-06-14 at 16 35 58" src="https://user-images.githubusercontent.com/8048526/173604281-ee994ab9-726a-4bb3-96cf-ce9e588e2a8e.png">

<img width="437" alt="Screenshot 2022-06-14 at 16 35 51" src="https://user-images.githubusercontent.com/8048526/173604288-07467c4b-aea6-48e7-b191-13d2b02d18c9.png">

**Comment by sequba** [comment]
Also in `package.json` we have this entry:
```json
  "license": "SEE LICENSE IN LICENSE.txt",
```

I believe this is the place where npm looks for our license so it should also be changed. @krzysztofspilka ?

**Comment by sequba** [comment]
Closing as released in version [2.1.0](https://github.com/handsontable/hyperformula/releases/tag/2.1.0).

![image.png](https://images.zenhubusercontent.com/61fbcaf4b7e91d1b90813a31/eb6b925a-d1b2-426d-8efa-8790e82c884b)
