### ISSUE TITLE
Add npm badges to the README

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#1016]
### Description

Add 2 (two) new badges to the README.md file. 

[![npm](https://img.shields.io/npm/dt/hyperformula.svg)](https://npmjs.com/package/hyperformula)
[![npm](https://img.shields.io/npm/dm/hyperformula.svg)](https://npmjs.com/package/hyperformula)

A part of the README file after that change: https://gist.github.com/krzysztofspilka/cfe4d1c711894dbbccf6d1a32873e736

**Comment by sequba** [comment]
Closing as released in version [2.1.0](https://github.com/handsontable/hyperformula/releases/tag/2.1.0).
