### ISSUE TITLE
Improve i18n/locale docs for the US clients

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1025]
### Description

- create Internationalization Overview guide that describes setting up the language and all the i18n-related configuration options (including `decimalSeparator`, `functionArgSeparator`) - add examples for the US locale
- add info to the `Introduction` page that we do support internationalization (with link to the Internationalization Overview)
- rename (or alias) default language from `enGB` to `enUS` (don't change the translations)
- use `enUS` date, currency & number formats in all the examples in the docs
- change Chineese example to US in [date and time handling guide](https://handsontable.github.io/hyperformula/guide/date-and-time-handling.html)
- add a "notice" on top of the guide that the default date format is en-gb (number, currency?)
- fix error in [date and time handling guide](https://handsontable.github.io/hyperformula/guide/date-and-time-handling.html) - mentioned wrong default format:
![image](https://user-images.githubusercontent.com/2480086/177773853-d1f76c20-3dce-44f9-b63b-beef466b4931.png)
- make sure there is no more error in this guide

### Links

- https://handsoncode.slack.com/archives/C031GBX62SE/p1657905045235899 (internal discussion)
- https://handsoncode.slack.com/archives/C031GBX62SE/p1659007424918559 (internal discussion)
- Related issues:
  - #535
  - #912
  - #953
  - #956

### Type of issue

- [ ] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by warpech** [comment]
> change Chineese example to US in [date and time handling guide](https://handsontable.github.io/hyperformula/guide/date-and-time-handling.html)

This example should include US am/pm time formatting. It is supported by HyperFormula (I can see it in the test suite) but not demonstrated in the docs.

**Comment by sequba** [comment]
Config params that should be covered by the `Internationalization overview` page:
- `language`
- `functionArgSeparator`, `decimalSeparator`, `thousandSeparator`
- `accentSensitive`, `localeLang` (in the context of string comparison)

**Comment by sequba** [comment]
To achieve US locale compatibility:

- `language: 'enUS'` (add this language and make sure there are no differences in function names between 'enGB' and 'enUS')
- `dateFormats: ['MM/DD/YYYY', 'MM/DD/YY']`
- make sure `timeFormats: ['hh:mm', 'hh:mm:ss.sss']` accepts AM/PM notation, add this information to the API reference
- `decimalSeparator` cannot be set to `,` because it must be different than `functionArgSeparator` (what about coercing strings to numbers?)
- `localeLang: 'en-US`` (make sure it works)

**Comment by sequba** [comment]
Closing as released in [HyperFormula 2.2.0](https://github.com/handsontable/hyperformula/releases/tag/2.2.0)
