### ISSUE TITLE
Bugs in the volatile-functions guide

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1056]
### Description

According to the guide we have 4 volatile functions:
- RAND
- RANDBETWEEN
- COLUMNS
- ROWS

But actually, functions marked by the `isVolatile` flag are different:
- RAND
- RANDBETWEEN
- NOW
- TODAY

### Links

- https://hyperformula.handsontable.com/guide/volatile-functions.html#volatile-functions-2
- https://github.com/handsontable/hyperformula/discussions/1053

**Comment by AMBudnik** [comment]
Issue closed as solved in v2.6.1
The guide is updated https://hyperformula.handsontable.com/guide/volatile-functions.html#volatile-functions-2
