### ISSUE TITLE
Parsing error for some cases of named expressions with numbers (before: Named expression on format "HF2_2" not allowed)

### ISSUE THREAD

**Issue by jboysen** [handsontable/hyperformula#1058]
But there is not information about why, and the naming doesn't violate the rules mentioned here: https://hyperformula.handsontable.com/guide/named-expressions.html#naming-convention

A jsfiddle to illustrate the issue: https://jsfiddle.net/uk1djxpw/1/

**Comment by sequba** [comment]
Hi, @jboysen. I am sorry you experienced an issue with HyperFormula. You are right, our naming rules must be updated. Thank you for reporting it.

**Comment by jboysen** [comment]
The implementation of isNameValid indicates that the name is valid:
https://github.com/handsontable/hyperformula/blob/fd0a40581d1dea2a19c2307228825ad0c3b6dedb/src/NamedExpressions.ts#L161

Is the implementation incorrect?

**Comment by sequba** [comment]
It might be incorrect or there is something else going on here. Our team will investigate this issue shortly.

**Comment by sequba** [comment]
Also, the heading `Naming convention` in our [named expressions guide](https://hyperformula.handsontable.com/guide/named-expressions.html#naming-convention) is very misleading. What this section describes is not a convention. These are the requirements for a valid name of the expression. @kirszenbaum proposed to change the heading to `Custom name rules`.

**Comment by AMBudnik** [comment]
Note to myself: Based on the case https://jsfiddle.net/h93ak8pL/1/, update the forum topic at https://forum.handsontable.com/t/gh-hyperformula-1058-named-expression-is-not-working/6569

**Comment by jboysen** [comment]
I see now the title changed of this issue. We looked more into this, and found that "HF2_2" is problematic, but "HF_2" was not, so the title is now misleading. 

For now we solved it by checking our named expressions like this in a validate method:
```
if (/[A-Z]+\d+/ig.test(variable)) {
    return false;
}
```

**Comment by sequba** [comment]
@jboysen Thank you for your input. It will come in handy in the process of working on this issue.

**Comment by sequba** [comment]
Possible duplicate: #880

**Comment by sequba** [comment]
@jboysen,
 
I'm more than happy to announce that we just released [HyperFormula 2.3.1](https://github.com/handsontable/hyperformula/releases/tag/2.3.1) where this issue is fixed. We are closing this issue as solved. If there is anything that won't work for you after updating, please leave a comment.

**Comment by kevinplummer** [comment]
Because HF can handle more columns than Excel something like AUFRINGES1 is invalid in HF but not Excel. How about if we set MaxColumns to say 26 or max Excel columns could you only do the named range check up to that column?

**Comment by AMBudnik** [comment]
Hi @kevinplummer that's an interesting idea. But at the moment, it is not available out of the box. If you'd like to test a custom solution and create a pull request we would be more than happy to review it as at the moment we focus more on fixing issues than on providing new functionalities.
