### ISSUE TITLE
Improve the description of value returned by methods `addRows`, `removeRows`, etc - the array of changes

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1062]
### Description

From #845:
> changes do not include updated formulas, only calculated values. Since HF will shift relative formula references, they will reference same values and the calculation results will not change.

This might not be described clearly enough in the API reference for these methods

### Links

- https://github.com/handsontable/hyperformula/issues/845
- https://github.com/handsontable/hyperformula/issues/1156
- https://hyperformula.handsontable.com/guide/basic-operations.html#what-are-the-changes

### Type of issue

- [x] Missing documentation

**Comment by AMBudnik** [comment]
Issued solved with https://github.com/handsontable/hyperformula/pull/1343 in HyperFormula v.6.2.1
