### ISSUE TITLE
hyperFormula does not catch syntax error with dangling comma, and returns invalid result

### ISSUE THREAD

**Issue by makarandp0** [handsontable/hyperformula#1066]
### Description

for a formula with syntax error (dangling comma) excel catches the error, but hyperformula doesn't 

### Steps to reproduce
```
import { HyperFormula } from 'hyperformula';

describe('hyperformula', () => {
  it('repro ', () => {
    const hfInstance = HyperFormula.buildFromArray([], {
      licenseKey: 'gpl-v3',
    });

    // this part works as expected
    const goodFormula = '=AND(1, 1)';
    const result1 = hfInstance.calculateFormula(goodFormula, 0);
    expect(result1).toStrictEqual(true);

    // hyperFormula did not catch the syntax error here.
    const badFormula = '=AND(1, 1,)';
    const result2 = hfInstance.calculateFormula(badFormula, 0);
    expect(result2).toStrictEqual(false);
  });
});


* HyperFormula version: 2.1.0
* Browser Name and version: N/A
* Operating System: N/A

**Comment by sequba** [comment]
Hi @makarandp0, thanks for reaching out to us.

I checked this issue and it seems to me that HyperFormula behaves consistently with Microsoft Excel.

The dangling comma is interpreted as if the last argument was `0` by both HyperFormula and Microsoft Excel. `AND()` function accepts a variable number of arguments so it doesn't report a syntax error, unlike `IF()` which must be called with exactly 3 arguments.

| Example | HyperFormula | Excel |
|-|-|-|
| `=AND(1, 1,)` | `FALSE` (interpreted as `=AND(1, 1, 0)`) | `FALSE` (interpreted as `=AND(1, 1, 0)`) |
| `=IF(1, 1, 1, )` | `#N/A: Wrong number of arguments` | `You've entered too many arguments for this function` |
| `=IF(0, 1,)` | `0` (interpreted as `=IF(0, 1, 0)`) | `0` (interpreted as `=IF(0, 1, 0)`) |

Tested using: Microsoft Excel Version 2208 on Windows 11

Are you sure Microsoft Excel reports a syntax error for `=AND(1, 1,)`? What version of Excel do you use?

**Comment by makarandp0** [comment]
Thank you for your response @sequba - You are of-course right, I see the same behavior in excel now for AND. I remember excel not allowing me to enter formula with dangling comma, but I must have been trying  using some other function. 

Thanks agains!
