### ISSUE TITLE
hyperformula does not optimize AND operations making it hard to write safe code

### ISSUE THREAD

**Issue by makarandp0** [handsontable/hyperformula#1067]
### Description

The demo below should make the issue clear. in evaluating `AND` operations, we typically expect that once a false condition is encounter, rest of the AND operations are not evaluated. But as you see in the demo below, hyperfomrula evaluates the 2nd part , causing it to return error.
 

### Demo
```
import { HyperFormula } from 'hyperformula';

describe('hyperformula', () => {
  it('does not optimize AND operations', () => {
    const hfInstance = HyperFormula.buildFromArray([], {
      licenseKey: 'gpl-v3',
    });

    hfInstance.addNamedExpression('myVariable', NaN);
    const goodFormula = '=ISNUMBER(myVariable)';
    const result1 = hfInstance.calculateFormula(goodFormula, 0);
    expect(result1).toStrictEqual(false);

    // in the formula below I was expecting that 2nd part of and condition
    // to not get evaluated (since 1st part is false)
    const badFormula = '=AND(ISNUMBER(myVariable), myVariable > 4)';
    const result2 = hfInstance.calculateFormula(badFormula, 0);
    expect(result2).toStrictEqual(false);
  });
});

```

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by sequba** [comment]
Hi @makarandp0, thanks for your feedback!

This behavior of `AND()` function is compliant with OpenFormula standard and consistent with Microsoft Excel. You should probably use `IF()` function which is guaranteed to use short-circuit evaluation.

```
=AND(1,1/0) -> #DIV/0!
=IF(1,1,1/0) -> 1
```
