### ISSUE TITLE
[Handsontable] Ability to work on dates 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/hyperformula#1074]
### Description

I would like to have the ability to work on dates on the Handsontable level.

Our current situation
* we need to define the `dateFormats` within the plugin
* the `dateFormats` is added globally (and we'd prefer to have it per cell)

### Links

**Conversation**: https://handsoncode.slack.com/archives/C031GBX62SE/p1664871825198519
**Example**: https://jsfiddle.net/z2vnm4st/5/

**Comment by warpech** [comment]
Closing as this is a Handsontable Formula plugin issue that is tracked in https://github.com/handsontable/handsontable/issues/10078
