### ISSUE TITLE
Docs: Add information that the result of `getCellPrecedents` & `getCellDependents` contains named expressions 

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1078]
### Description

Methods `getCellPrecedents` and `getCellDependents` return named expressions in the form of call addresses with `sheetId = -1`.
```js
  it('getCellPrecedents returns named expressions', () => {
    const engine = HyperFormula.buildFromArray([
      ['=FOO']
    ], {}, [
      { name: 'FOO', expression: '=42' }
    ])

    expect(engine.getCellPrecedents(adr('A1'))).toEqual([{ sheet: -1, row: 0, col: 0 }])
  })
```

This information should be added to the API reference. Also, we need unit tests for this behavior.

### Type of issue

- [ ] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

### Links
#1077

**Comment by AMBudnik** [comment]
Closed as solved with https://github.com/handsontable/hyperformula/pull/1350/files in HyperFormula v 2.6.1

Main guide page: [****](https://hyperformula.handsontable.com/guide/dependency-graph.html#ranges-in-the-dependency-graph)
