### ISSUE TITLE
Incomplete documentation for custom function arguments validation

### ISSUE THREAD

**Issue by nicoladaniello** [handsontable/hyperformula#1090]
### Description
I'm trying to add a custom formula but the [documentation](https://hyperformula.handsontable.com/guide/custom-functions.html#custom-function-options) on how to accept arguments is incomplete.

The [FunctionArgument](https://github.com/handsontable/hyperformula/blob/25941f6df7c7f2420ac814bacf76f6e31fce94b1/src/interpreter/plugin/FunctionPlugin.ts#L171) interface requires a field called `argumentType` but this is not specified in the [docs](https://hyperformula.handsontable.com/guide/custom-functions.html#custom-function-options).

Also the parameter type is an [enum](https://github.com/handsontable/hyperformula/blob/25941f6df7c7f2420ac814bacf76f6e31fce94b1/src/interpreter/plugin/FunctionPlugin.ts#L123) but apparently this is not exported by hyperformula, which gives an error when using typescript:

```
Module not found: Error: Can't resolve 'hyperformula/typings/interpreter/plugin/FunctionPlugin'
```

### Links

https://hyperformula.handsontable.com/guide/custom-functions.html#custom-function-options

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by sequba** [comment]
Hi @nicoladaniello! Thanks for reaching out to us.

You are absolutely right. Our custom functions guide should mention required `argumentType` field and `ArgumentTypes` enum should be exported.

As a workaround you can use the string literals specified in the [enum definition](https://github.com/handsontable/hyperformula/blob/25941f6df7c7f2420ac814bacf76f6e31fce94b1/src/interpreter/plugin/FunctionPlugin.ts#L123):
```js
parameters: [{
  argumentType: 'NUMBER' as any,
}],
```

We will fix this bug in one of the upcoming releases together with #779

**Comment by sequba** [comment]
Closing. This issue will be addressed in one of the upcoming releases when working on #779

**Comment by sequba** [comment]
@nicoladaniello I just created an example of a custom function that accepts a parameter. It's still in the development stage, and it will be published in the next version of our documentation, but you may want to look at it: https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/feature/issue-779/custom-functions
