### ISSUE TITLE
batching addSheet setSheetContent does not work as expected

### ISSUE THREAD

**Issue by BrianHung** [handsontable/hyperformula#1114]
### Description

Related to https://github.com/handsontable/hyperformula/issues/207.

It is expected that
```ts
hf.suspendEvaluation();

const table1 = hf.addSheet("table1");
hf.setCellContents(
  {
    row: 0,
    col: 0,
    sheet: hf.getSheetId(table1)
  },
  [["='table2'!A1"]]
);

const table2 = hf.addSheet("table2");
hf.setCellContents(
  {
    row: 0,
    col: 0,
    sheet: hf.getSheetId(table2)
  },
  [["10"]]
);

hf.resumeEvaluation();
```

will result in

```ts
// Expected [[10]]
// Actual [[DetailedCellError]]
hf.getAllSheetValues(table1)
```

What actually works is moving both `setCellContents` after the `addSheet`.

```ts
hf.suspendEvaluation();

const table1 = hf.addSheet("table1");
const table2 = hf.addSheet("table2");

hf.setCellContents(
  {
    row: 0,
    col: 0,
    sheet: hf.getSheetId(table1)
  },
  [["='table2'!A1"]]
);

hf.setCellContents(
  {
    row: 0,
    col: 0,
    sheet: hf.getSheetId(table2)
  },
  [["10"]]
);

hf.resumeEvaluation();
```

### Demo
https://codesandbox.io/s/loving-dijkstra-25ett6

### Your environment

* HyperFormula version: 2.2.0
* Browser Name and version:
* Operating System:

**Comment by sequba** [comment]
@BrianHung As described in #207, in that case, it is necessary to call [rebuildAndRecalculate()](https://hyperformula.handsontable.com/api/classes/hyperformula.html#rebuildandrecalculate) to force updating the [dependency graph](https://hyperformula.handsontable.com/guide/dependency-graph.html):

https://codesandbox.io/s/affectionate-franklin-hyso8m?file=/src/hyperformulaConfig.js:638-666

This operation might be computationally heavy, but I hope it won't be a performance bottleneck for you ;)

**Comment by sequba** [comment]
@BrianHung I'm glad this workaround works for you. I'm closing this issue.

However, after discussion with the team, we decided we want to fix the implementation of `addSheet()` so that calling `rebuildAndRecalculate()` manually won't be necessary. We'll track this task in #1116
