### ISSUE TITLE
Docs: make it clear that read operations are not allowed in a batch

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1118]
### Description

Explain how batching works and what are the benefits of using it. Make it clear that read operations are not possible.

### Links

- #1113 
- https://hyperformula.handsontable.com/guide/batch-operations.html

### Type of issue

- [ ] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by AMBudnik** [comment]
Changes applied via https://github.com/handsontable/hyperformula/pull/1337 in HyperFormula v 2.6.1. Issue closed as solved.
