### ISSUE TITLE
Using TEXT formula returns # characters in output

### ISSUE THREAD

**Issue by yalamber** [handsontable/hyperformula#1138]
### Using TEXT formula returns # characters in output
Formula =TEXT(1234.567,"$#,##0.00")
expected output: $1,234.57
returned output:  $1235,##0.00

### Steps to reproduce

1. use TEXT formula =TEXT(1234.567,"$#,##0.00") in any column value

### Demo
https://gist.github.com/yalamber/2f88fa523a55a9e89d03a9f26de9adbf

### Your environment
Node.js v18

* HyperFormula version: v2.1.0
* Browser Name and version: node
* Operating System: Mac

**Comment by sequba** [comment]
Hi @yalamber, thanks for reaching out to us.

### Explanation

Our implementation of the `TEXT()` function does not support formats with thousands separator (`,` in the case of the format `$#,##0.00`). 

I created an [issue](https://github.com/handsontable/hyperformula/issues/1145) to add such a format, but at our current stage of development, we prioritize bug and interoperability fixes, so this feature is not on our immediate roadmap.

Also, bear in mind that HyperFormula is an open-source project. We are open to [contributions from the community](https://hyperformula.handsontable.com/guide/contributing.html) and we would be delighted to collaborate on that feature.

### Workaround

The analogous format without a thousands separator works:

```js
hf.setSheetContent(mainSheetId, [['=TEXT(1234.567,"$#.00")']]);
```

**Comment by sequba** [comment]
Closing. If you had more questions, please reopen the issue.
