### ISSUE TITLE
ESM module files in the published package should have `.mjs` file extension

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1143]
### Description

[Publint](https://publint.dev/hyperformula@2.3.0) reports for all files in `/es/` directory:
> /es/${filename}.js is written in ESM, but is interpreted as CJS. Consider using the .mjs extension, e.g. /es/${filename}.mjs

We should change it to comply with the standard.

Warning: this change might be considered breaking because it will break the [code that uses filenames with extensions in the import statements](https://codesandbox.io/s/thirsty-feather-dukby4?file=/src/hyperformulaConfig.js:41-100).

HOT team did a similar task in https://github.com/handsontable/handsontable/pull/7403 & https://github.com/handsontable/handsontable/pull/8875/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

### Links

- https://handsoncode.slack.com/archives/C4PV4S33Q/p1673602200151429 (internal discussion)

**Comment by sedghi** [comment]
Having the same issue, my library has /cjs, /umd, and /esm and here is my package json, and getting the same error

```js
"main": "dist/umd/index.js",
  "module": "src/index.ts",
  "exports": {
    ".": {
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    },
    "./package.json": "./package.json"
  },
```

**Comment by AMBudnik** [comment]
Thank you for the feedback @sedghi 

I will notify you as soon as we fix this issue.

**Comment by sequba** [comment]
@sedghi Ok, we'll increase the priority of this task. Is it a blocker for you? Were you able to make HyperFormula work by adjusting the configuration?

**Comment by sequba** [comment]
Will be done in scope of #1344
