### ISSUE TITLE
Function IFS

### ISSUE THREAD

**Issue by makarandp0** [handsontable/hyperformula#1157]
### Can you support function IFS
I see that IFS is [supported by excel](https://support.microsoft.com/en-us/office/ifs-function-36329a26-37b2-467c-972b-4a39bd951d45) but not by [hyperformula](https://hyperformula.handsontable.com/guide/built-in-functions.html#list-of-available-functions), I am curious why is that and can it be supported. 

Thank you!
Makarand

**Comment by sequba** [comment]
@makarandp0 you are correct, there are a few functions missing from HyperFormula, but at our current stage of development, we prioritize bug and interoperability fixes, so new functions are not on our immediate roadmap.

However, bear in mind that HyperFormula is an open-source project. We are open to [contributions from the community](https://hyperformula.handsontable.com/guide/contributing.html) and we would be delighted to collaborate on that feature. Recently, we accepted a [pull request from the external collaborator](https://github.com/handsontable/hyperformula/pull/1047) that added functions MINIFS and MAXIFS.

**Comment by makarandp0** [comment]
Thank you for your quick reply @sequba. For now we have worked around by using nested `IF` function, but will try to implement `IFS` and open a PR soon.

**Comment by AMBudnik** [comment]
Hi @makarandp0 

Thank you very much for your input.

The changes proposed are added to HyperFormula v2.5.0 released today.

Here https://hyperformula.handsontable.com/guide/release-notes.html#_2-5-0 you can read more about the changes within this version.
