### ISSUE TITLE
`cell-references` guide describes 3D ranges which are in fact not supported

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1168]
### Description

`cell-references` guide:
![image](https://user-images.githubusercontent.com/2480086/222126981-f1996605-dcc8-44bb-8437-88204bae2737.png)

`known-limitations` guide:
![image](https://user-images.githubusercontent.com/2480086/222127524-0f15da8f-9a11-461d-98d5-847f10a9813c.png)

We could verify whether or not 3D ranges work but currently there are no unit tests for them so we cannot communicate that they are supported. The incorrect information in the `cell-references` guide was introduced while working on reversed ranges feature. The author of this feature did not know the project well enough at that time.

### Links

- https://hyperformula.handsontable.com/guide/cell-references.html
- https://hyperformula.handsontable.com/guide/known-limitations.html
- https://github.com/handsontable/hyperformula/pull/938

### Type of issue

- [ ] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by AMBudnik** [comment]
Closed as solved with https://github.com/handsontable/hyperformula/pull/1338 in HyperFormula 2.6.1
