### ISSUE TITLE
`SimpleRangeValue` should be exported as part of our public API

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1178]
### Description

It is exported by ES module but not when importing HF through the HTML `<script>`.

### Demo

https://codepen.io/qcurtemanjc/pen/oNPedpB (provided by @qcurtemanjc)

### Links

https://github.com/handsontable/hyperformula/discussions/1177
https://github.com/handsontable/hyperformula/issues/843

**Comment by qcurtemanjc** [comment]
@sequba Is there a timeline for this fix?

**Comment by AMBudnik** [comment]
Hi @qcurtemanjc I am doing regular checks on the issues in this repository. And as mentioned here https://github.com/handsontable/hyperformula/issues/1162 we do not do so many instant releases, but this issue has a high priority and surely will be fixed as soon as possible.

I will make sure to ping you as soon as the release is out.

**Comment by qcurtemanjc** [comment]
@AMBudnik Just wanted to follow up on this and see if there might be any updates. This has become a blocker for multiple custom formulas I have tried to create. Thanks!

**Comment by AMBudnik** [comment]
Hi @qcurtemanjc This task already has a PR connected https://github.com/handsontable/hyperformula/pull/1240 and is currently in the code review

**Comment by sequba** [comment]
@qcurtemanjc It should be released in about two weeks. Stay tuned ;)

**Comment by AMBudnik** [comment]
Hi @qcurtemanjc we just release v2.4.0 where this issue is fixed.
Here https://hyperformula.handsontable.com/guide/release-notes.html#_2-4-0 you can read more about the changes in this version.
