### ISSUE TITLE
Favicon is mission for Hyperformula webpages

### ISSUE THREAD

**Issue by thilgen** [handsontable/hyperformula#1186]
Related to [Handsontable Issue #10274](https://github.com/handsontable/handsontable/issues/10274)

## [Handsontable Page](https://handsontable.com/docs/javascript-data-grid/api/core/) Favicon
![image](https://user-images.githubusercontent.com/9309340/224170231-8577d71b-382b-4377-924e-deaa0724709b.png)

## [Handsontable Forum Page](https://forum.handsontable.com/t/export-to-json/3925) Favicon
![image](https://user-images.githubusercontent.com/9309340/224170375-de80aac0-027c-40bb-a63f-259e7dc8e65f.png)

## [Hyperformula Page](https://hyperformula.handsontable.com/guide/basic-usage.html) Favicon **(MISSING)**
![image](https://user-images.githubusercontent.com/9309340/224170496-411a45cf-ce52-462d-88bf-3947eb3d68cb.png)

### Steps to reproduce
1. Open the pages and take a look at the browser tabs

### Your environment
Mac+Chrome

**Comment by sequba** [comment]
Internal resources: https://handsoncode.slack.com/archives/C031GBX62SE/p1680524294934339
