### ISSUE TITLE
DependentFormulaTransformer is not exported (defined in MoveCellsTransformer.ts)

### ISSUE THREAD

**Issue by thilgen** [handsontable/hyperformula#1199]
### Description
Because `class DependentFormulaTransformer` is not exported from `MoveCellsTransformer.ts` - it is currently not possible (or at least not very obvious how) to resolve non-covered codecov lines for `MoveCellsTransformer.ts`

Can we do one of the following
* Export`class DependentFormulaTransformer`from `MoveCellsTransformer.ts`
* Move `class DependentFormulaTransformer` it to its own file and export it

So that codecov tests can be added

### Steps to reproduce
1. Run codecov and inspect the report
2. Look at the structure of `MoveCellsTransformer.ts`

**Comment by AMBudnik** [comment]
Thank you for the suggestion, @thilgen 

Sharing the `DependentFormulaTransformer` class for the reference https://github.com/handsontable/hyperformula/blob/master/src/dependencyTransformers/MoveCellsTransformer.ts#L98

**Comment by sequba** [comment]
Hi, @thilgen! Thank you for your efforts on code coverage front. Exporting this class might be a good idea, but - to be honest - HyperFormula code coverage is already pretty high and working on it is not our top priority right now.

If you want to contribute to the project, I encourage you to have a look on [Good First Issues](https://github.com/handsontable/hyperformula/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22). Also, we will be thrilled to have a call and discuss your ideas for the development of HyperFormula.

**Comment by thilgen** [comment]
@sequba - I'm happy to take on the work - but didn't know if the core team would have a strong opinion about exporting this class or not. Should I go ahead an submit a PR with the proposed change? (I'd export this helper and add unit tests)

**Comment by sequba** [comment]
@thilgen This issue has low priority for our team, so we will not be able to work on it anytime soon. If you want to contribute, we will appreciate your help. Feel free to open a pull request ;)

**Comment by thilgen** [comment]
Done - https://github.com/handsontable/hyperformula/pull/1212

**Comment by sequba** [comment]
Fixed in HyperFormula 2.4.0
