### ISSUE TITLE
Hyperformula should produce same number of columns for each records for getSheetValues

### ISSUE THREAD

**Issue by yalamber** [handsontable/hyperformula#1211]
### Description
Hyperformula should produce same number of columns for each records for getSheetValues

### Steps to reproduce

setSheetContent with last item of the row to be null
```
hf.setSheetContent(mainSheetId, [
    ['Apple Inc.', '2%', 'text', null, ''],
    ['Apple Inc 2.', '2%', 'text', 1, null],
]);
const mainBoardData = hf.getSheetValues(0);
console.log("mainBoardData", mainBoardData);
```
This produces results as below 

```
mainBoardData [
  [ 'Apple Inc.', 0.02, 'text', null, '' ], // 5 cols here
  [ 'Apple Inc 2.', 0.02, 'text', 1 ] // only 4 cols here
]
```
### Demo

https://codesandbox.io/p/sandbox/sleepy-thunder-medp8e

### Your environment

Mac

* HyperFormula version: 2.3.0
* Browser Name and version: node 16
* Operating System: Mac

**Comment by sequba** [comment]
The reason for this behavior is that HyperFormula optimizes memory usage by storing only non-empty cells.

@yalamber Please, explain why this feature is useful to you.

**Comment by thilgen** [comment]
FWIW: This behavior **is** different when compared with how trailing null row values are returned in `Handsontable` - although changing how `Hyperformula` does this would probably break about 10,000 unit tests 😞 

```
const container = document.getElementById('example')
container.hot = new Handsontable(
  container,
  {
    licenseKey: 'non-commercial-and-evaluation',
    rowHeaders: false,
    colHeaders: false,
    height: 'auto',
    fillHandle: false,
    formulas: {
      engine: hyperformulaInstance,
      sheetName: container.id
    },   
    data: [
      [10, 11, 12, 13],
      [10, 11, 12],
      [10, 11],
      [10],
    ]
  }
)

container.hot.getData().forEach(row => {
  console.log(row)  
})

console.log(hyperformulaInstance.getSheetDimensions(0))
hyperformulaInstance.getSheetValues(0).forEach(row => {
  console.log(row)  
})
```
[JSFiddle Example](https://jsfiddle.net/thilgen/2gf5ardj/25/)

* `Handsontable.getData()` - Supplies `nulls` for col values out to dimensions of max row width

    ```
    [10, 11, 12, 13]
    [10, 11, 12, null]
    [10, 11, null, null]
    [10, null, null, null]
   ```
* `Hyperformula.getSheetDimensions()` - Returns the full dimensional space

   ```
   {
    height: 4,
    width: 4
   }
  ```
* However `Hyperformula.getSheetValues()` - Omits the nulls
  ```
  [10, 11, 12, 13]
  [10, 11, 12]
  [10, 11]
  [10]
  ```

**Comment by sequba** [comment]
Closing this issue as we do not consider it a bug. That is the way HyperFormula treats empty cells and it can be handled easily by the client code by adding `null` values where necessary.

@yalamber if you have more information about it, please comment or re-open.
