### ISSUE TITLE
INDEX failing with #CYCLE if Source Range overlaps (but Row offset does not)

### ISSUE THREAD

**Issue by thilgen** [handsontable/hyperformula#1214]
### Description

This works as expected in Google Sheets and Excel

```
const hyperformulaInstance = HyperFormula.buildEmpty({
  licenseKey: 'internal-use-in-handsontable',
});

const containerName = 'example'
var container = document.getElementById('example')
container.hot = new Handsontable(
  container,
  {
    licenseKey: 'non-commercial-and-evaluation',
    rowHeaders: false,
    colHeaders: false,
    height: 'auto',
    fillHandle: false,
    formulas: {
      engine: hyperformulaInstance,
      sheetName: containerName
    },   
    data: [
      ['apple'        , null],
      ['pear'         , null],
      ['orange'       , null],
      ['=INDEX(A:A,2)','=FORMULATEXT(A4)']
    ]
  }
)
```
| Platform | Results |
| --------- | ------- |
| HyperFormula | ![image](https://user-images.githubusercontent.com/9309340/228416304-6e4ad650-e5f9-4b30-9903-efe1a2b407a5.png) |
| Google Sheets | ![image](https://user-images.githubusercontent.com/9309340/228416339-f487e599-2c7c-4617-90c6-a82c271f31f0.png) |
| MS Excel |  ![image](https://user-images.githubusercontent.com/9309340/228416321-c27b551f-ce95-4bf8-b79a-cd990b172203.png)  |

### Steps to reproduce
1. [JSFiddle Example](https://jsfiddle.net/thilgen/74w0pdxe/5/)
 
### Your environment
* Handsontable: v12.3.2 (22/03/2023 14:43:31)
* HyperFormula: 2.3.1
* Browser Name & OS: Mac + Chrome

**Comment by sequba** [comment]
This seems like something that would be pretty hard to fix. Currently, HyperFormula detects `CYCLE` errors statically without running the function evaluation.

I suggest adding this to the list of limitations: the https://hyperformula.handsontable.com/guide/list-of-differences.html

**Comment by sequba** [comment]
Closing
