### ISSUE TITLE
Add ADDRESS Support

### ISSUE THREAD

**Issue by thilgen** [handsontable/hyperformula#1221]
### Description

`ADDRESS` is a formula provided by 
* **Google Sheets** ([documentation](https://support.google.com/docs/answer/3093308))
* **MS Excel** ([documentation](https://support.microsoft.com/en-us/office/address-function-d0c26c0d-3991-446b-8de4-ab46431d4f89))
* **Open Document Format for Office Applications** ([documentation](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part2.html#__RefHeading__1018416_715980110))

The syntax (copied from [Google Sheets Documentation](https://support.google.com/docs/answer/3093308)) is

```
ADDRESS(row, column, [absolute_relative_mode], [use_a1_notation], [sheet])

row                     The row number of the cell reference

column                  The column number (not name) of the cell reference. A is column number 1.

absolute_relative_mode  [OPTIONAL - 1 by default] - An indicator of whether the reference is 
                        row/column absolute. 1 is row and column absolute (e.g. $A$1), 2 is 
                        row absolute and column relative (e.g. A$1), 3 is row relative and 
                        column absolute (e.g. $A1), and 4 is row and column relative (e.g. A1).

use_a1_notation         [OPTIONAL - TRUE by default] - A boolean indicating whether to use A1 
                        style notation (TRUE) or R1C1 style notation (FALSE).

sheet                   [OPTIONAL - absent by default] - A string indicating the name of the 
                        sheet into which the address points.
```

| Platform | Results |
| --------- | ------- |
| **Google Sheets** |  ![image](https://user-images.githubusercontent.com/9309340/228943314-9ff77290-fe71-47e3-bcb4-459606a7e111.png) ![image](https://user-images.githubusercontent.com/9309340/235277748-559a3028-6ef8-4000-a238-92741e215019.png) ![image](https://user-images.githubusercontent.com/9309340/235277753-53bf3dc4-0c4a-4db5-94cf-46aac36a03a1.png) |
| **MS Excel** |  ![image](https://user-images.githubusercontent.com/9309340/228943263-b40f161f-24b1-48ad-8149-99efe383fa9b.png) ![image](https://user-images.githubusercontent.com/9309340/235277814-feb3f59c-1a03-448d-b0af-bb9eda0663a4.png) ![image](https://user-images.githubusercontent.com/9309340/235277820-4dc56994-3b59-40c5-bab7-c48fcf2d93d3.png) |

### Design and Prototype
* A basic `FormulaPlugin`
### HyperFormula Changes (https://github.com/handsontable/hyperformula/pull/1222)
* Add a new `FunctionPlugin` called `ADDRESS`
  * This handles all the logic of parsing the parameters and formatting the resultant VALUE
  * ~~Note: Since the `use_a1_notation` param is in all the other implementations - I suggest keeping the signature the same for `HyperFormula` - but throwing an `Error` if `use_a1_notation` is ever passed as `FALSE` (since `HyperFormula` does not have support for `R1C1` reference notation)~~
    * **Update 2023-04-28:** Per comment in PR (https://github.com/handsontable/hyperformula/pull/1222#discussion_r1175502018) - I have added support for `R1C1` notation - Passing `FALSE` for this argument is now valid
* * **Prototype and Unit Tests:** https://github.com/handsontable/hyperformula/pull/1222

#### Results
| ADDRESS Formula| HyperFormula Results | Google Sheets Results | MS Excel Results | Notes |
| --------- | ------- | ------- | ------- | ------- | 
| `=ADDRESS(1,1)` | `$A$1` | `$A$1` | `$A$1` |   |
| `=ADDRESS(77,300)` | `$KN$77` | `$KN$77` | `$KN$77` |   |
| `=ADDRESS(ROW(),300)` | `$KN$3` | `$KN$3` | `$KN$3` |   |
| `=ADDRESS(45,COLUMN())` | `$A$45`| `$A$45` | `$A$45` |   |
| `=ADDRESS(1,1,1)` | `$A$1` | `$A$1` | `$A$1` |   |
| `=ADDRESS(1,1,2)` | `A$1` | `A$1` | `A$1` |   |
| `=ADDRESS(1,1,3)` | `$A1` | `$A1` | `$A1` |   |
| `=ADDRESS(1,1,4)` | `A1` | `A1` | `A1` |   |
| `=ADDRESS(1,1,1, TRUE(), "Sheet1")` | `Sheet1!$A$1` | `Sheet1!$A$1` | `Sheet1!$A$1` |   |
| `=ADDRESS(1,1,2, TRUE(), "Sheet2")` | `Sheet2!A$1` | `Sheet2!A$1` | `Sheet2!A$1` |   |
| `=ADDRESS(1,1,3, TRUE(), "Sheet3")` | `Sheet3!$A1` | `Sheet3!$A1` | `Sheet3!$A1` |   |
| `=ADDRESS(1,1,4, TRUE(), "Sheet4")` | `Sheet4!A1` | `Sheet4!A1`   | `Sheet4!A1`  |   |
| `=ADDRESS(1,1,4, TRUE(), "")` | `!A1` | `'!A1` | `!A1` | Divergent result for Sheets is due to how empty strings are handled in Sheets |
| `=ADDRESS()` | `(ErrorType.NA,`<br>`ErrorMessage.WrongArgNumber)` | `#N/A`| `=ADDRESS()` / `#N/A` |   |
| `=ADDRESS(1)` | `(ErrorType.NA,`<br>`ErrorMessage.WrongArgNumber)` | `#N/A` | `=ADDRESS(1)` / `#N/A` |   |
| `=ADDRESS(0,0)` | `(ErrorType.NUM,`<br>`ErrorMessage.ValueSmall)` | `#VALUE!` | `#VALUE!`| Divergent result for `HyperFormula` is not understood. Other `FunctionPlugin` param range checking seems to align with Sheets and Excel |
| `=ADDRESS("row1","row2")` | `(ErrorType.VALUE,`<br>`ErrorMessage.NumberCoercion)` | `#VALUE!` | `#VALUE!` |   |
| `=ADDRESS(1,1,0)` | `(ErrorType.NUM,`<br>`ErrorMessage.ValueSmall)` | `#NUM!` | `#VALUE!` | Divergent `ERROR` result between Excel and Sheets |
| `=ADDRESS(1,1,5)` | `(ErrorType.NUM,`<br>`ErrorMessage.ValueLarge)` | `#NUM!` | `#VALUE!`| Divergent `ERROR` result between Excel and Sheets |
| ~~`=ADDRESS(1,1,4,FALSE())`~~ | ~~`(ErrorType.NA,`<br>`ErrorMessage.ArgumentMustEqual(`<br>`'useA1Style', 'TRUE'))`~~ | ~~`R[1]C[1]`~~ | ~~`R[1]C[1]`~~ | ~~Since `HyperFormula` does not support `R1C1` notation choosing to return an `#N/A!`~~ |
| `=ADDRESS(1,1,1, true, "")` | `(ErrorType.NAME,`<br>`ErrorMessage.NamedExpressionName(`<br>`'true'))` | `'!$A$1` | `!$A$1` | Since `HyperFormula` does not support `true` or `false` as expression names - return an `#NAME!` |

**Update 2023-04-28:** Per https://github.com/handsontable/hyperformula/pull/1222#discussion_r1175502018 - I have added support for `R1C1` notation - Passing `FALSE` for the fourth argument is now valid
| ADDRESS Formula| HyperFormula Results | Google Sheets Results | MS Excel Results | Notes |
| --------- | ------- | ------- | ------- | ------- | 
| `=ADDRESS(1,1,1,FALSE)` | `R1C1` | `R1C1` | `R1C1` |   |
| `=ADDRESS(1,1,2,FALSE)` | `R1C[1]`  | `R1C[1]` | `R1C[1]` |   |
| `=ADDRESS(1,1,3,FALSE)` | `R[1]C1`  | `R[1]C1` | `R[1]C1` |   |
| `=ADDRESS(1,1,4,FALSE)` | `R[1]C[1]` | `R[1]C[1]` | `R[1]C[1]` |   |
| `=ADDRESS(1,1,1,FALSE,"Sheet1")` | `Sheet1!R1C1` | `Sheet1!R1C1` | `Sheet1!R1C1` |   |
| `=ADDRESS(1,1,2,FALSE,"Sheet2")` | `Sheet2!R1C[1]` | `Sheet2!R1C[1]` | `Sheet2!R1C[1]` |   |
| `=ADDRESS(1,1,3,FALSE,"Sheet3")` | `Sheet3!R[1]C1` | `Sheet3!R[1]C1` | `Sheet3!R[1]C1` |   |
| `=ADDRESS(1,1,4,FALSE,"Sheet4")` | `Sheet4!R[1]C[1]` | `Sheet4!R[1]C[1]` | `Sheet4!R[1]C[1]` |   |
| `=ADDRESS(1,1,4,FALSE,"")` | `!R[1]C[1]` | `"!R[1]C[1]` | `!R[1]C[1]` | Divergent result for Sheets is due to how empty strings are handled in Sheets  |

**Comment by jfstephe** [comment]
Any ETA on this being resolved/released?

**Comment by thilgen** [comment]
All PR comments have been resolved - https://github.com/handsontable/hyperformula/pull/1222/

**Comment by sequba** [comment]
If everything went well, we'll release it with the upcoming version of HyperFormula.

**Comment by AMBudnik** [comment]
Hi @thilgen 

Thank you again for an outstanding help with making HyperFormula a great library!

I am more than glad to announce that ADDRESS and HYPERLINK functions are added to HyperFormulas 2.5.0.
Here is a full list of changes for this version https://hyperformula.handsontable.com/guide/release-notes.html#_2-5-0
