### ISSUE TITLE
JS Export Missing: CellError

### ISSUE THREAD

**Issue by thilgen** [handsontable/hyperformula#1232]
### Description

`CellError` is missing from `JS` exports.

This means that if your solution is developed entirely in the front-end you cannot properly make us of `CellError` when implementing a `Custom Function` / `FunctionPlugin` per these instructions in the [HyperFormula Guide: Custom Functions](https://hyperformula.handsontable.com/guide/custom-functions.html#advanced-custom-function-example)

<img src="https://user-images.githubusercontent.com/9309340/230515528-4acdea27-c305-49de-a947-68ac1d3d9afb.png" width=700>

**Ironically `DetailedCellError` is exported - but since its constructor requires a `CellError` you cannot make use of that class either.**

### Steps to reproduce
1. [JSFiddle: hyperformula-cell-error-export](https://jsfiddle.net/thilgen/kn8vfa7x/25/)
2. Modify the zero-check in the `checkValue` function to observe the error
   
   **Note:** JSFiddle doesn't show the full error in their console. However you can see the error more clearly when running in Chrome
   
   ![image](https://user-images.githubusercontent.com/9309340/230515810-bf1dbfa3-d190-4fad-ae70-f32f4ac0758e.png)

### Your environment
* Handsontable: v12.3.3 (28/03/2023 12:24:28)
* HyperFormula: 2.3.0
* Browser Name and version: Mac+Chrome

**Comment by thilgen** [comment]
PR https://github.com/handsontable/hyperformula/pull/1233

**Comment by AMBudnik** [comment]
Hi @thilgen 

Thank you again for contributing to HyperFormula. We just released v2.4.0 with fixes to this issue and the one that you mentioned at https://github.com/handsontable/hyperformula/issues/1205
