### ISSUE TITLE
Add Svelte demo to documentation

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1246]
### Description

After the initial research - the demo needs to be adjusted to be compatible with CodeSandbox.

### Links

https://handsoncode.slack.com/archives/C031GBX62SE/p1681898730460589 (internal)

### Type of issue

- [ ] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [x] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by AMBudnik** [comment]
Issue closed as done. Solved in v2.6.1.

New page URL https://hyperformula.handsontable.com/guide/integration-with-svelte.html
