### ISSUE TITLE
Compatibility: Different result for PV() when rate === -1 and periods === 0 

### ISSUE THREAD

**Issue by thilgen** [handsontable/hyperformula#1249]
### Description

Discovered while improving code coverage in https://github.com/handsontable/hyperformula/pull/1248

### Steps to reproduce

```
const hyperformulaInstance = HyperFormula.buildFromArray(
  [
    ['=PV(-1, 0, 100, 400)']  
  ],
  {
    licenseKey: 'internal-use-in-handsontable'  
  }
);
console.log(hyperformulaInstance.getCellValue({ sheet: 0, col: 0, row: 0 }))
```

| Engine  | Result |
| ------------- | ------------- |
| HyperFormula |  `#NUM!`|
| Excel | `#NUM!`  |
| Google Sheets | `-$400.00`  |

### Your environment
* HyperFormula version: 2.3.0

**Comment by sequba** [comment]
`periods = 0` is an edge case. Personally, the result given by Google Sheets seems more logical to me, but we value compatibility with Excel over Sheets so we'd rather leave it like that.

But I think, this difference is worth mentioning on our `list-of-differences` page.

**Comment by AMBudnik** [comment]
Thank you again for your input @thilgen 

I closed this issue as solved with https://github.com/handsontable/hyperformula/pull/1319 in HyperFormula v.2.6.1

Referenced guide https://hyperformula.handsontable.com/guide/list-of-differences.html#built-in-functions
