### ISSUE TITLE
Compatibility: Different result for RATE() when guess is negative (but greater than -1)

### ISSUE THREAD

**Issue by thilgen** [handsontable/hyperformula#1250]
### Description

Discovered while improving code coverage in https://github.com/handsontable/hyperformula/pull/1248

### Steps to reproduce
```
const hyperformulaInstance = HyperFormula.buildFromArray(
  [
    ['=RATE(0.9, -100, 400, 0, 0, -1)', ],
    ['=RATE(0.9, -100, 400, 0, 0, -1)', ],
    ['=RATE(0.9, -100, 400, 0, 0, -1)', ],
    ['=RATE(0.9, -100, 400, 0, 0, -0.8)', ],
    ['=RATE(0.9, -100, 400, 0, 0, -0.0000001)', ],
    ['=RATE(0.9, -100, 400, 0, 0, -0.00000001)', ],
  ],
  {
    licenseKey: 'internal-use-in-handsontable',
  }
);

console.log(hyperformulaInstance.getCellValue({ sheet: 0, col: 0, row: 0 }))
console.log(hyperformulaInstance.getCellValue({ sheet: 0, col: 0, row: 1 }))
console.log(hyperformulaInstance.getCellValue({ sheet: 0, col: 0, row: 2 }))
console.log(hyperformulaInstance.getCellValue({ sheet: 0, col: 0, row: 3 }))
console.log(hyperformulaInstance.getCellValue({ sheet: 0, col: 0, row: 4 }))
console.log(hyperformulaInstance.getCellValue({ sheet: 0, col: 0, row: 5 }))
```
**HyperFormula**
```
#VALUE!
#VALUE!
#VALUE!
-0.796172361015191
-0.796172361010535
-0.796172361010618
```
**Excel**
```
#VALUE!
#VALUE!
#VALUE!
-80%
-80%
-80%
```
**Google Sheets**
```
#NUM!
#NUM!
#NUM!
#NUM!
#NUM!
#NUM!
```
**Note: The error presented in Google Sheet on hover-over is `Function RATE parameter 1 value is 0. It should be greater than 0.`** (which doesn't make a ton of sense since the first param is `0.9`)

### Your environment
* HyperFormula version: 2.3.0

**Comment by sequba** [comment]
@thilgen So it seems that our results are consistent with Excel (with some rounding errors) and Google Sheets clearly has some bugs in their implementation.

What exactly do you think should be fixed in HyperFormula? The rounding errors so `-0.79617236101` turns into `-0.8`?

**Comment by thilgen** [comment]
I agree that the Google Sheet result looks suspect; And since the HF result is aligned with Excel there is nothing actionable. I just wanted to make a note of the behavior in case there was more to be done. Closing this out.
