### ISSUE TITLE
`updateConfig()` should check if new config is the same as the old one

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1251]
### Description

`updateConfig()` is an expensive operation. It rebuilds the whole engine so we should avoid doing it when not necessary. This method should check if the new config is the same as the old one.

### Links

https://github.com/handsontable/handsontable/pull/10326
https://github.com/handsontable/hyperformula/issues/1252

**Comment by AMBudnik** [comment]
Closed as solved in HyperFormula v2.5.0
Release notes for the version: https://hyperformula.handsontable.com/guide/release-notes.html#_2-5-0
