### ISSUE TITLE
Custom func that returns an array doesn't seem to resize properly

### ISSUE THREAD

**Issue by qcurtemanjc** [handsontable/hyperformula#1253]
### Description
Custom function that returns a `SimpleRangeValue` value doesn't recalculate using the `arraySizeFunc` first and it breaks. Not sure if this is a bug or if I have my set up incorrect.

### Steps to reproduce
Using this codepen: https://codepen.io/qcurtemanjc/pen/abRWzbK?editors=1111
In cell `A1`, try to add another value (i.e. enter `1,2,3,4` into cell `A1`)

Expected: 
In row 2, it should have 1 2 3 4 in incremental column cells respectively

Actual:
It breaks.

### Demo
https://codepen.io/qcurtemanjc/pen/abRWzbK?editors=1111

### Your environment

* HyperFormula version: 2.4.0
* Browser Name and version: Chrome (`104.0.5112.79`)
* Operating System: Mac OS

### Note:
My chrome console throws an error when following the steps to reproduce but code pen doesn't for some reason. Here's the error in chrome:
```
hyperformula.full.min.js:815 Uncaught Error: Resizing to smaller array
    at i.resize (hyperformula.full.min.js:815:1693)
    at h.setCellValue (hyperformula.full.min.js:810:1074)
    at t.Evaluator.recomputeFormulaVertexValue (hyperformula.full.min.js:1004:2362)
    at hyperformula.full.min.js:1004:628
    at hyperformula.full.min.js:825:2965
    at Array.forEach (<anonymous>)
    at t.Graph.getTopSortedWithSccSubgraphFrom (hyperformula.full.min.js:825:2833)
    at hyperformula.full.min.js:1004:503
    at o.measure (hyperformula.full.min.js:786:1166)
    at t.Evaluator.partialRun (hyperformula.full.min.js:1004:441)
```

**Comment by adrianszymanski89** [comment]
Hi @qcurtemanjc 

It looks like there is an issue in this part:

`return new HyperFormula.ArraySize(data?.length, 1);`

As the first parameter doesn't resize the array correctly. If you change it to the fixed value larger than the initial data in the first cell, then it works correctly.

**Comment by qcurtemanjc** [comment]
Hey @adrianszymanski89 

Thanks for the reply. I'm not sure that setting the first parameter to a larger fixed value will always work. If there is a value in the arrays "path" it will cause a `#SPILL!` error.

Example:
I changed it to this `return new HyperFormula.ArraySize(100, 1);`
and if I enter a value in one of the empty cells in the "array row" it causes a spill error
<img width="382" alt="Screen Shot 2023-04-28 at 7 20 50 AM" src="https://user-images.githubusercontent.com/53444830/235173806-bac35a0e-0155-4025-81d3-75010c485a8f.png">

**Comment by adrianszymanski89** [comment]
Hi @qcurtemanjc 

I'm not sure about your complete requirements for this, but it seems that overwriting the new array will cause a `#SPILL` error even with your initial implementation. 

One way to avoid it would be to set this row to `readOnly` so the values won't be modified.

**Comment by qcurtemanjc** [comment]
Hey @adrianszymanski89 

I would expect the `HyperFormula.ArraySize` formula to recalculate the size of the array each time the array changes values/size. Is that an incorrect assumption? I think if that is not how this function works, I would have to have the user enter in a "Max Length" parameter into the formula and use that in the `ArraySize` function.

**Comment by sequba** [comment]
Hi @qcurtemanjc, what you stumbled upon is, unfortunately, a limitation of HyperFormula.

The `ArraySize` function is called only once and it must return an upper bound on the size of the resulting array. After that, the size cannot be changed on updates to the dependencies.

Therefore, this implementation of `SPLIT` function is not possible in the current version of HyperFormula. See [this discussion](https://github.com/handsontable/hyperformula/issues/857#issuecomment-977865922) for reference.

**Comment by sequba** [comment]
I decided to add this information to our documentation in https://github.com/handsontable/hyperformula/pull/1261

**Comment by qcurtemanjc** [comment]
@sequba Thank you for letting me know.

**Comment by sequba** [comment]
I'm closing this issue.

**Comment by BrianHung** [comment]
@sequba is this issue blocked by the same issue here? https://github.com/handsontable/hyperformula/discussions/870#discussioncomment-1775947

I’m trying to implement more array size methods but not being able to calculate the array size from dependencies results in #REF! or #SPILL! errors. Thanks!

**Comment by sequba** [comment]
@BrianHung it's not exactly the same issue but a closely related one.

The way HyperFormula currently works requires knowing some information statically (after parsing cell content but before evaluating formulas). E.g.:
- dependencies of a formula cell (https://github.com/handsontable/hyperformula/discussions/870#discussioncomment-1775947)
- in case of array formulas - an upper bound on the size of the resulting array (https://github.com/handsontable/hyperformula/issues/1253#issuecomment-1535840508)

Unfortunately, removing these limitations requires redesigning the core of HyperFormula, so it is not on our roadmap,
