### ISSUE TITLE
Registered Custom Function with Handsontable Not Found

### ISSUE THREAD

**Issue by danelikethedog** [handsontable/hyperformula#1259]
### Description

~~Registered custom function seem to be getting dropped on subsequent render. Any idea why this might be happening?~~

Initial problem is resolved. But now I pass the Hyperformula to Handsontable. If I check the validity of my custom function from the instance (`hfInstance.validateFormula("=CONVERT(4,\"kg\",\"g\")")`) it says `true`. But when I try to add that same formula to a cell in the table, it says it can't find `CONVERT()`. See comment below for logs.

### Steps to reproduce

Rough idea is a Spreadsheet viewer component which contains a HotTable component. The HotTable component registers the `CONVERT()` custom function at the top of the file. It seems on first render, the custom function is in the available functions. But after a re-render, it seems to drop registered functions.

### Demo

Rough idea is this

```javascript

// UnitConversionFunction.js
export class UnitConversionCustomExcelFunction extends FunctionPlugin {
  convert(ast, state) {
    return this.runFunction(
      ast.args,
      state,
      this.metadata("CONVERT"),
      (number, fromUnit, toUnit) => {
        const convertedNumber = UnitConversions.convertFromToUnits(
          number,
          fromUnit,
          toUnit
        );
        return convertedNumber;
      }
    );
  }
}

export const UnitConversionCustomExcelFunctionTranslations = {
  enUS: {
    CONVERT: "CONVERT"
  }
};

UnitConversionCustomExcelFunction.implementedFunctions = {
  CONVERT: {
    method: "convert",
    parameters: [
      { argumentType: FunctionArgumentType.NUMBER },
      { argumentType: FunctionArgumentType.STRING },
      { argumentType: FunctionArgumentType.STRING }
    ]
  }
};

// Table.js
import { registerAllModules } from "handsontable/registry";
import {
  UnitConversionCustomExcelFunction,
  UnitConversionCustomExcelFunctionTranslations
} from "./UnitConversionCustomExcelFunction";
import enUS from "hyperformula/es/i18n/languages/enUS";

if (!HyperFormula.getRegisteredLanguagesCodes().includes(enUS.langCode))
  HyperFormula.registerLanguage(enUS.langCode, enUS);
HyperFormula.registerFunctionPlugin(
  UnitConversionCustomExcelFunction,
  UnitConversionCustomExcelFunctionTranslations
);
registerAllModules();


const Table = (data) => {
  const globalParser = useRef(
    HyperFormula.buildEmpty({
      language: "enUS",
      licenseKey: "internal-use-in-handsontable"
    })
  );

    logger.debug(
      "DataSpreadsheet contains CONVERT: ",
      tableRef.current?.props.formulas?.engine.getRegisteredFunctionNames().includes("CONVERT")
    );

  return (
    <HotTable
      data={data}
      formulas={{
        engine: globalParser.current,
      }}
      ... />
  )
}

// Excel.js
const ExcelPage = () => {

  const [data, setData] = useState([]);

    logger.debug(
      "DataExcel contains CONVERT: ",
      tableRef.current?.props.formulas?.engine.getRegisteredFunctionNames().includes("CONVERT")
    );

  return (
    <Table data={data} />
  )
}

```

These console Logs:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/7367603/236039738-fb5f2a63-42aa-42fb-bddf-8556db51f936.png">

### Your environment

* HyperFormula version: `2.4.0`
* Browser Name and version: Arc (Chromium based)
* Operating System: Mac OS

**Comment by danelikethedog** [comment]
It seems part of the problem might be that I was wrapping it in a `useRef()`. It now shows that it is in the available functions but it shows in the chart something wrong with the invocation of the function.

**Comment by danelikethedog** [comment]
Okay yea so I have the Formula instance checking the validity of the `CONVERT()` and it says its possible. But when I update a cell in the Handsontable, it says it can't find the function:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/7367603/236061920-0d6dc209-0582-41d2-8df9-604ac9f28c2b.png">

**Comment by adrianszymanski89** [comment]
Hi @danelikethedog 

I'll check it and get back to you tomorrow with more information.

**Comment by AMBudnik** [comment]
Hi @danelikethedog I am afraid that we have to close this issue report as there's no reply for over 3 weeks.

If you still need help please let us know.
