### ISSUE TITLE
Update React, Angular and Vue in the demos

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1273]
### Description

Update frameworks to the newest versions that work. If more effort is needed to make it work with `@latest`, create a follow-up issue for next release.

### Type of issue

- [ ] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [x] Other issues, suggestions or ideas

**Comment by AMBudnik** [comment]
Closed with HyperFormula [v.2.5.0](https://hyperformula.handsontable.com/guide/release-notes.html#_2-5-0) released today.

**Comment by sequba** [comment]
Related: #1281
