### ISSUE TITLE
Add Vue 3 demo

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1275]
### Description

Create new demo using vue 3 framework. Rename the existing demo to `Vue 2 demo`

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by AMBudnik** [comment]
Changes added to the documentation under https://hyperformula.handsontable.com/guide/integration-with-vue.html for HyperFormula v2.6.1.
