### ISSUE TITLE
[Bug]: Angular 16 demo not rendering in Codesandbox 

### ISSUE THREAD

**Issue by aninde** [handsontable/hyperformula#1281]
### Description

[CodeSandbox demo ](https://hyperformula.handsontable.com/guide/integration-with-angular.html) with Angular 16 is not displaying correctly. We decided to go back to the previous, properly rendering version. Issue is caused by CodeSandbox.
The Angular version boost in the demo requires more time and will be done separately.

It's related to Codesandbox new feature: [Cloud Sandbox](https://codesandbox.io/docs/learn/sandboxes/overview?tab=cloud).

### Video or screenshots
![image](https://github.com/handsontable/hyperformula/assets/30186818/67cb98fc-03df-46c7-8242-a5199e9b6194)

### Demo

https://hyperformula.handsontable.com/guide/integration-with-angular.html

### HyperFormula version

12.5

### Your framework

Angular 16

### Your environment

Codesandbox

**Comment by sequba** [comment]
The buggy demo is on branches:
- https://github.com/handsontable/hyperformula-demos/tree/develop
- https://github.com/handsontable/hyperformula-demos/tree/2.5.x

The documentation was reverted to use the previous release branch (https://github.com/handsontable/hyperformula-demos/tree/2.4.x) in the `Integration with Angular` page.

Hotfix pull requests:
- https://github.com/handsontable/hyperformula/pull/1282 (for master)
- https://github.com/handsontable/hyperformula/pull/1283 (for develop)

**Comment by sequba** [comment]
I verified it today, and it works. I believe CodeSandbox might have fixed their issue in the meantime.

So I made sure that:

- [ ] demo with angular@16 is on branch [develop@hyperformula-demos](https://github.com/handsontable/hyperformula-demos/blob/develop/angular-demo/package.json)
- [ ] demo with angular@16 is on branch [2.6.x@hyperformula-demos](https://github.com/handsontable/hyperformula-demos/blob/2.6.x/angular-demo/package.json)
- [ ] angular demo from branch [2.6.x](https://github.com/handsontable/hyperformula-demos/tree/2.6.x) is on branch [master@hyperformula](https://github.com/handsontable/hyperformula/blob/master/docs/guide/integration-with-angular.md)
- [ ] angular demo from branch [2.6.x](https://github.com/handsontable/hyperformula-demos/tree/2.6.x) is on branch [develop@hyperformula](https://github.com/handsontable/hyperformula/blob/develop/docs/guide/integration-with-angular.md)
- [ ] angular demo from branch [2.6.x](https://github.com/handsontable/hyperformula-demos/tree/2.6.x) is [published](https://hyperformula.handsontable.com/guide/integration-with-angular.html)
