### ISSUE TITLE
[Bug]: Issue with decimal separator

### ISSUE THREAD

**Issue by haraleib** [handsontable/hyperformula#1301]
### Description

- If someone uses handsontable with hyperformula
- If there is a numeric column A and a numeric column B
- Per default, handsontable handles/formats the cell value correctly when the user edits the numeric field regardless if the user types in ',' or '.' as decimal separator.
- Hyperformula calculation results in an error if the user types in the wrong decimal separator

### Video or screenshots

Type in **1,2** in column B -> results in an error
![image](https://github.com/handsontable/hyperformula/assets/19574757/13f45a55-3ab0-42c5-8ab3-371ba0af3489)

Type in **1.2** in column B -> results in a valid calculation
![image](https://github.com/handsontable/hyperformula/assets/19574757/eb0d7bab-616f-4dd6-accb-29411ce17ba1)

It works the same on column A (so without numericFormat)

### Demo

https://jsfiddle.net/sqxv6tgj/

### HyperFormula version

2.5.0

### Your environment

Chrome 116.0.5845.111

**Comment by adrianszymanski89** [comment]
Hi @haraleib 

We are not considering this behavior as a bug. This is because if you enter the '1,2' value, it's treated as a string and two separate values. That's why it's throwing an error. Compared to other industry solutions, Google Sheets will behave in the same way.

**Comment by haraleib** [comment]
> 

Hi @adrianszymanski89, thanks for your reply.
I understand your point, but I want to question it, because from a user perspective it seems that it doesn't make sense.
It doesn't matter if the User types in '1**.**2' or '1**,**2', the value is represented and formatted correct for the user, but the calculation doesn't work. I think as a User I would be clueless what I have done wrong, because my User Input seems to be correct in both cases.

**Comment by AMBudnik** [comment]
Hi @haraleib 

You may want to workaround this limitation by the `afterChange` char replacement, like

```js
 afterChange: function(changes, src){
  	let row = changes[0][0];
    let col = changes[0][1];
    let val = changes[0][3];
    let parsed = val.replace(/,/g, " ");
    
    // val.replace(/,/g, " ");
    if(src !== 'myChange'){
    	hot.setDataAtCell(row, col, parsed, 'myChange')
    }
  }
```

but you would need to recalculate the formula as `afterChange` triggers after the formula is calculated.

**Comment by haraleib** [comment]
Hi @AMBudnik, thank you for the workaround, I will try it  :-)
