### ISSUE TITLE
[Bug]: Typo in the API reference for HyperFormula class

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1323]
### Description

There is a typo in the API reference for HyperFormula class. Originally reported [here](https://github.com/handsontable/hyperformula/pull/1322) by @zackrw

### Video or screenshots

![image](https://github.com/handsontable/hyperformula/assets/2480086/ca63ff57-99c5-40cc-b354-3f1f3159dcad)

### Demo

https://hyperformula.handsontable.com/api/classes/hyperformula.html

### HyperFormula version

2.6.0

### Your environment

Chrome

**Comment by AMBudnik** [comment]
Issue closed as solved in documentation for HyperFormula v6.2.1
