### ISSUE TITLE
[Bug]: `Maximum call stack size exceeded` when adding a row to a huge spreadsheet with formulas

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1332]
### Description

Code that produces this issue:
```ts
  it('handles huge spreadsheet', () => {
    const rowsCount = 1048576 // 2^20

    const sheet = []
    sheet.push(['1', '2', '3', '0', '0'])

    let prev = 1

    while (prev < rowsCount) {
      const rowToPush = [
        `${prev + 1}`,
        '2',
        '=3*5',
        `=A${prev}+D${prev}`,
        `=SUM($A$1:A${prev})`,
      ]

      sheet.push(rowToPush)
      ++prev
    }

    const engine = HyperFormula.buildFromArray(sheet, { maxRows: rowsCount*2 })

    expect(() => engine.addRows(0, [2000, 1])).not.toThrow()
  })
```

Originally reported by @BrianHung in https://github.com/handsontable/hyperformula/pull/1321

![image](https://github.com/handsontable/hyperformula/assets/2480086/9fab35c3-2306-4c4f-9003-ad9e81bc557a)

### HyperFormula version

2.6.0

### Your environment

- Node
- Windows 11
- 16 GB RAM

**Comment by AMBudnik** [comment]
Closed as solved and released in HyperFormula 2.6.1.
List of all the changes https://github.com/handsontable/hyperformula/releases/tag/2.6.1
