### ISSUE TITLE
[Bug]: Moving rows sometimes does not update formulas correctly

### ISSUE THREAD

**Issue by mtjoe3** [handsontable/hyperformula#1339]
### Description

Moving last row referenced in formula to the top of the formula will update formula to exclude it from the formula.

I think this makes sense if we move the row directly in one single step, but it does not if we are moving the row in multiple steps (move it to the middle of the formula first, and then to the top).

### Video or screenshots

https://github.com/handsontable/hyperformula/assets/83485085/a61e849b-f941-432a-aa55-bc10e4511287

### Demo

https://jsfiddle.net/fuqsmc3e/

### HyperFormula version

2.4.0

### Your framework

Vanilla Javascript

### Your environment

MacOS

**Comment by adrianszymanski89** [comment]
Hi @mtjoe3 

This feature isn't implemented yet. However, we have it already reported here: https://github.com/handsontable/hyperformula/issues/1156

We will update this thread once it gets on our roadmap.

**Comment by adrianszymanski89** [comment]
Hi @mtjoe3 

I'm not sureif I understood your issue correctly. Can you please explain what would be your expected output here?

**Comment by AMBudnik** [comment]
Hi @mtjoe3 do we have any updates regarding this issue?

**Comment by BrianHung** [comment]
This issue should probably belong in the handsontable repo right, since hyperformula does not offer a UI for manipulating rows.
