### ISSUE TITLE
Add events to notify about value and formula updates

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#135]
### Description

We've made an analysis of how we could implement events on our side but it would work only for simple use cases. When we have multiple worksheets and multiple Handsontable instances it's complex, triggers multiple hooks, there is a problem which instance to listen on. It's important to have a single place where we can listen to calculation engine events.

From what I see it shouldn't be hard to add them to HyperFormula.

https://github.com/handsontable/hyperformula/blob/e361d8c7abc698970b58168a308566d36361253d/src/HyperFormula.ts#L771-L781

Just dispatch an event before returning the changes:

```diff
 private recomputeIfDependencyGraphNeedsIt(): ContentChanges { 
   const changes = this.crudOperations.getAndClearContentChanges() 
   const verticesToRecomputeFrom = Array.from(this.dependencyGraph.verticesToRecompute()) 
   this.dependencyGraph.clearRecentlyChangedVertices() 
  
   if (verticesToRecomputeFrom.length > 0) { 
     changes.addAll(this.evaluator.partialRun(verticesToRecomputeFrom)) 
   } 

+   this.dispatch('onChange', changes)

   return changes 
 } 

+ private dispatchEvent(eventName, ...args) {
+   // ... do something
+ }
```

### From  #24

Since the use case includes external widgets where formulas are included and calculation results are displayed it will be necessary to notify those widgets about recalculations and formula references changes on CRUD operations.

Events mentioned in #7 might be useful here:
```ts
// Values were recalculated
onValueUpdated(changes: CellValueChange[], sourceSheet: string)
// Formulas references were updated
onFormulaUpdated(changes: CellFormulaChange[], sourceSheet: string)
```

### Events ideas

- onReady
- onValueUpdated
- onFormulaUpdated
- Sheet:
    - onAddSheet
    - onRemoveSheet
    - onMoveSheet
    - onRenameSheet
- Column:
    - onAddColumn
    - onRemoveColumn
    - onMoveColumn
- Row:
    - onAddRow
    - onRemoveRow
    - onMoveRow
- onMoveCell
- Named Expression:
    - onAddExpression
    - onRemoveExpression
    - onGetExpression
- Copy,Cut,Paste:
    - onCopy
    - onCut
    - onPaste

**Comment by BrianHung** [comment]
> formulasUpdated

This doesn't seem to have been implemented? And is pretty important when doing something like a `moveCols` where the values don't have to update, but the formulas do. `formulasUpdated` is useful when hyperformula isn't authoritative i.e. its values are derived from some external data store.

**Comment by AMBudnik** [comment]
Hi @BrianHung 

Yes, that's true. Thank you for noticing! Eventually, we only added the `valuesUpdated` hook. But, you're right `formulasUpdated` still sounds like a idea. Let me [report it as a separate feature request](https://github.com/handsontable/hyperformula/issues/1156). 

Now, we focus on fixing bugs but will keep this idea in the back of our heads. If anything changes I will surely let you know.
