### ISSUE TITLE
Docs: broken EUIPO link in the branding page

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1353]
### Description

`https://www.euipo.europa.eu/eSearch/#details/trademarks/018141121` should be changed to `https://euipo.europa.eu/eSearch/#details/trademarks/018141121`

Page: https://hyperformula.handsontable.com/guide/branding.html#trademark-protection

### Demo

https://hyperformula.handsontable.com/guide/branding.html#trademark-protection

### HyperFormula version

2.6.0

### Your environment

Chrome

**Comment by AMBudnik** [comment]
Closed as solved in v.6.2.1
