### ISSUE TITLE
Remove Vue 2 demo

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1355]
### Page URL

https://hyperformula.handsontable.com/guide/integration-with-vue.html

### Improvement description

From https://v2.vuejs.org/lts/:

> Vue 2 will reach End of Life (EOL) on December 31st, 2023. After that date, Vue 2 will continue to be available in all existing distribution channels (CDNs and package managers), but will no longer receive updates, including security and browser compatibility fixes.

- https://handsoncode.slack.com/archives/C4PV4S33Q/p1702899238389759 (internal discussion)

**Comment by AMBudnik** [comment]
This issue is closed as solved by https://github.com/handsontable/hyperformula/pull/1356/files in HyperFormula 2.6.1. We are no longer able to access Vue 2 demo along with all the resource at https://github.com/handsontable/hyperformula-demos
