### ISSUE TITLE
Feature: get a list of named expressions used by a formula

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1365]
Create a method that returns a list of named expressions in a formula.

The method should take a cell address as parameter or the formula as string, whichever is better, easier or more consistent with the rest of the API.

Originally requested in https://github.com/handsontable/hyperformula/discussions/1077#discussioncomment-3879351

**Comment by AMBudnik** [comment]
Confirmed to be done and released under HyperFormula 2.7.0
