### ISSUE TITLE
Bug in the Server side installation instructions

### ISSUE THREAD

**Issue by sandzone** [handsontable/hyperformula#1372]
### Page URL

https://hyperformula.handsontable.com/guide/server-side-installation.html

### Improvement description

It should be 
const {HyperFormula} = require('hyperformula');

instead of 
const HyperFormula = require('hyperformula');

**Comment by sequba** [comment]
Hi @sandzone, thank you for this report. You're right. I'll fix it in the upcoming release.

**Comment by sequba** [comment]
@sandzone We've just published new version of the documentation with this issue fixed ;)
