### ISSUE TITLE
Per-instance internal custom state accessible from a custom function implementation

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1396]
### Description

As proposed in https://github.com/handsontable/hyperformula/discussions/808#discussioncomment-8907333, we want to add an untyped config parameter that can be used to store any custom data, which then will be available in the scope of a custom function implementation.

### Links

https://github.com/handsontable/hyperformula/discussions/808

**Comment by AMBudnik** [comment]
Released in [v2.7.0.](https://hyperformula.handsontable.com/guide/release-notes.html#_2-7-0)
