### ISSUE TITLE
[Bug]: =1.0667-1.0666 count wrong 0.000099999999999989

### ISSUE THREAD

**Issue by wanquantong** [handsontable/hyperformula#1417]
### Description

=1.0667-1.0666
count wrong 0.000099999999999989
correct is 0.0001

### Demo

https://stackblitz.com/run?file=index.js

### HyperFormula version

2.7.0

### Your environment

chrome 122

**Comment by thilgen** [comment]
This is a limitation of JS - See same results in Chrome console and Node console
<img width="266" alt="Screenshot 2024-06-22 at 2 43 19 PM" src="https://github.com/handsontable/hyperformula/assets/9309340/78768285-545b-4232-92e5-e6ffe892a26c">
<img width="325" alt="Screenshot 2024-06-22 at 2 45 03 PM" src="https://github.com/handsontable/hyperformula/assets/9309340/df8c7291-d52c-44fb-9072-31444ad6f8d4">

**Comment by thilgen** [comment]
...and when I raised the same concern 😄 

https://github.com/handsontable/hyperformula/issues/1234

**Comment by adrianszymanski89** [comment]
Hi @wanquantong 

@thilgen is right. This is the same case he already reported and was discussed in the mentioned issue. I will close this ticket.
