### ISSUE TITLE
Setup staging environment for documentation

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#1450]
### Description

It's useful to see the documentation release candidate before pushing it to production. The goal:

- a separate GH pages environment (`gh-pages-staging`) that can serve the documentation
- a special branch `staging` that can keep the release candidate of HyperFormula
- pushing to `staging` triggers a workflow that deploys the documentation to `gh-pages-staging`

**Comment by sequba** [comment]
Staging is accessible at

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
