### ISSUE TITLE
Add Compatibility functions

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#152]
### Description

Part of Epic #150 

We need to add lacking **Compatibility** functions to achieve the minimum viable product to be incorporated into Handsontable.

The below list is compatible with formula.js as seen [here](https://github.com/sutoiku/formula.js/blob/master/lib/compatibility.js):

- [x] BETADIST
- [x] BETAINV
- [x] BINOMDIST
- [x] CONFIDENCE
- [x] EXPONDIST
- [x] FDIST
- [x] FLOOR
- [x] GAMMADIST
- [x] GAMMAINV
- [x] HYPGEOMDIST
- [x] LOGNORMDIST
- [x] NEGBINOMDIST
- [x] NORMDIST
- [x] NORM.INV
- [x] NORMSDIST
- [x] NORMSINV
- [x] STDEVP
- [x] TDIST
- [x] TINV
- [x] VARP

**Comment by wojciechczerniak** [comment]
STDEVP, VARP added in #536

**Comment by wojciechczerniak** [comment]
#554
- [x] BETADIST
- [x] BETAINV
- [x] BINOMDIST
- [x] EXPONDIST
- [x] FDIST
- [x] GAMMADIST
- [x] GAMMAINV
- [x] HYPGEOMDIST
- [x] LOGNORMDIST
- [x] NEGBINOMDIST
- [x] NORMDIST
- [x] NORM.INV
- [x] NORMSDIST
- [x] NORMSINV
- [x] TDIST
- [x] TINV

#575
- [x] CONFIDENCE

#576
- [x] FLOOR

**Comment by wojciechczerniak** [comment]
All done here
