### ISSUE TITLE
Add Date and Time functions

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#153]
### Description

Part of Epic #150 

We need to add lacking **Date and Time** functions to achieve the minimum viable product to be incorporated into Handsontable.

The below list is compatible with formula.js as seen [here](https://github.com/sutoiku/formula.js/blob/master/lib/date-time.js).

- [x] DATEVALUE
- [x] DAYS360
- [x] EDATE
- [x] HOUR
- [x] ISOWEEKNUM
- [x] MINUTE
- [x] NETWORKDAYS
- [x] NOW
- [x] SECOND
- [x] TIME
- [x] TIMEVALUE
- [x] TODAY
- [x] WEEKDAY
- [x] WEEKNUM
- [x] WORKDAY

**Comment by wojciechczerniak** [comment]
Update:

- [x] DATEVALUE
- [x] DAYS360
- [x] EDATE
- [x] HOUR
- [x] ISOWEEKNUM
- [x] MINUTE
- [x] NOW
- [x] SECOND
- [x] TIME
- [x] TIMEVALUE
- [x] TODAY
- [x] WEEKDAY
- [x] WEEKNUM

Only two left @bardek8 @izulin  🎉 
- [ ] NETWORKDAYS
- [ ] WORKDAY

**Comment by wojciechczerniak** [comment]
NETWORKDAYS and WORKDAY in #534

**Comment by wojciechczerniak** [comment]
Done
