### ISSUE TITLE
Add Financial functions

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#155]
### Description

Part of Epic #150 

We need to add lacking **Financial** functions to achieve the minimum viable product to be incorporated into Handsontable.

The below list is compatible with formula.js as seen [here](https://github.com/sutoiku/formula.js/blob/master/lib/financial.js).

- [ ] ACCRINT
- [x] CUMIPMT
- [x] CUMPRINC
- [x] DB
- [x] DDB
- [x] DOLLARDE
- [x] DOLLARFR
- [x] EFFECT
- [x] FV
- [x] FVSCHEDULE
- [x] IPMT
- [ ] IRR
- [x] ISPMT
- [x] MIRR
- [x] NOMINAL
- [x] NPER
- [x] NPV
- [x] PDURATION
- [x] PMT
- [x] PPMT
- [x] PV
- [x] RATE
- [x] RRI
- [x] SLN
- [x] SYD
- [x] TBILLEQ
- [x] TBILLPRICE
- [x] TBILLYIELD
- [ ] XIRR
- [x] XNPV

**Comment by wojciechczerniak** [comment]
Update:

- DOLLARDE
- DOLLARFR
- ISPMT
- NOMINAL
- NPER
- PV
- RATE
- RRI
- SLN
- SYN

**Comment by wojciechczerniak** [comment]
FVSCHEDULE, NPV, MIRR, PDURATION, XNPV added in #542

**Comment by wojciechczerniak** [comment]
Just few left, I will reevaluate our list later
