### ISSUE TITLE
Add Lookup and Reference functions

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#158]
### Description

Part of Epic #150 

We need to add lacking **Lookup and Reference** functions to achieve the minimum viable product to be incorporated into Handsontable.

The below list is compatible with formula.js as seen [here](https://github.com/sutoiku/formula.js/blob/master/lib/lookup-reference.js).

- [x] CHOOSE
- [x] COLUMN
- [x] COLUMNS
- [x] ROW
- [x] ROWS
- [ ] UNIQUE

**Comment by wojciechczerniak** [comment]
Update:

- CHOOSE
- COLUMNS
- ROWS

**Comment by voodoo11** [comment]
Update:
- HLOOKUP
- ROW
- COLUMN

**Comment by wojciechczerniak** [comment]
Note from #520 by @voodoo11 "Function UNIQUE seems out of our scope for now as it returns array."
