### ISSUE TITLE
Add Text functions

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#159]
### Description

Part of Epic #150 

We need to add lacking **Text** functions to achieve the minimum viable product to be incorporated into Handsontable.

The below list is compatible with formula.js as seen [here](https://github.com/sutoiku/formula.js/blob/master/lib/text.js).

- [x] CLEAN
- [x] EXACT
- [x] LEFT
- [x] LEN
- [x] LOWER
- [x] MID
- [x] PROPER
- [x] REPLACE
- [x] REPT
- [x] RIGHT
- [x] SEARCH
- [x] SUBSTITUTE
- [x] T
- [x] TRIM
- [x] UNICHAR
- [x] UNICODE
- [x] UPPER

**Comment by wojciechczerniak** [comment]
Update:

- [x] CLEAN
- [x] LEFT
- [x] LEN
- [x] PROPER
- [x] REPT
- [x] RIGHT
- [x] SEARCH
- [x] TRIM

**Comment by bardek8** [comment]
Finished in: #518 :)

**Comment by wojciechczerniak** [comment]
Awesome! 💪 🎉
