### ISSUE TITLE
Add Statistical functions

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#160]
### Description

Part of Epic #150 

We need to add lacking **Statistical** functions to achieve the minimum viable product to be incorporated into Handsontable.

The below list is compatible with formula.js as seen [here](https://github.com/sutoiku/formula.js/blob/master/lib/statistical.js).

- [x] CONFIDENCE.NORM
- [x] CONFIDENCE.T
- [x] COVARIANCE.P
- [x] COVARIANCE.S
- [x] DEVSQ
- [x] EXPON.DIST
- [x] EXPONDIST
- [x] F.DIST
- [x] F.DIST.RT
- [x] F.INV
- [x] F.INV.RT
- [x] FINV
- [x] FISHER
- [x] FISHERINV
- [ ] FORECAST
- [ ] FREQUENCY
- [x] GAMMA
- [x] GAMMA.DIST
- [x] GAMMA.INV
- [x] GAMMAINV
- [x] GAMMALN
- [x] GAMMALN.PRECISE
- [x] GAUSS
- [x] GEOMEAN
- [ ] GROWTH
- [x] HARMEAN
- [x] HYPGEOM.DIST
- [ ] INTERCEPT
- [ ] KURT
- [x] LARGE
- [ ] LINEST
- [ ] LOGEST
- [x] LOGNORM.DIST
- [x] LOGNORM.INV
- [ ] MODE.MULT
- [ ] MODE.SNGL
- [x] NEGBINOM.DIST
- [x] NORM.DIST
- [x] NORMINV
- [x] NORM.S.DIST
- [x] NORM.S.INV
- [x] PEARSON
- [ ] PERMUT
- [ ] PERMUTATIONA
- [x] PHI
- [x] POISSON.DIST
- [ ] PROB
- [ ] QUARTILE.EXC
- [ ] QUARTILE.INC
- [ ] RANK.AVG
- [ ] RANK.EQ
- [x] RSQ
- [x] SKEW
- [x] SKEW.P
- [x] SLOPE
- [x] SMALL
- [x] STANDARDIZE
- [x] STDEV.P
- [x] STDEV.S
- [x] STDEVA
- [x] STDEVPA
- [x] STEYX
- [x] T.DIST
- [x] T.DIST.2T
- [x] T.DIST.RT
- [x] T.INV
- [x] T.INV.2T
- [ ] TREND
- [ ] TRIMMEAN
- [x] VAR.P
- [x] VAR.S
- [x] VARA
- [x] VARPA
- [x] WEIBULL.DIST

**Comment by wojciechczerniak** [comment]
VAR.P, VAR.S, VARA, VARPA, STDEV.P, STDEV.S, STDEVA, STDEVPA added in #536

**Comment by wojciechczerniak** [comment]
#575
- [x] CONFIDENCE.NORM
- [x] CONFIDENCE.T
- [x] COVARIANCE.P
- [x] COVARIANCE.S
- [x] DEVSQ
- [x] GEOMEAN
- [x] HARMEAN
- [x] PEARSON
- [x] RSQ
- [x] SKEW
- [x] SKEW.P
- [x] STANDARDIZE
- [x] STEYX
- [x] SLOPE
- [x] LARGE
- [x] SMALL

#554
- [x] F.DIST
- [x] F.DIST.RT
- [x] F.INV
- [x] F.INV.RT
- [x] FINV
- [x] HYPGEOM.DIST
- [x] T.DIST
- [x] T.DIST.2T
- [x] T.DIST.RT
- [x] T.INV
- [x] T.INV.2T
- [x] WEIBULL.DIST
- [x] PHI
- [x] POISSON.DIST
- [x] NORM.DIST
- [x] NORMINV
- [x] NORM.S.DIST
- [x] NORM.S.INV

**Comment by wojciechczerniak** [comment]
We're done with functions for now.
