### ISSUE TITLE
Add Math and Trigonometry functions

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#161]
### Description

Part of Epic #150 

We need to add lacking **Math and Trigonometry** functions to achieve the minimum viable product to be incorporated into Handsontable.

The below list is compatible with formula.js as seen [here](https://github.com/sutoiku/formula.js/blob/master/lib/math-trig.js).

- [x] ACOS
- [x] ACOSH
- [x] ACOT
- [x] ACOTH
- [ ] AGGREGATE
- [x] ARABIC
- [x] ASIN
- [x] ASINH
- [x] ATAN
- [x] ATAN2
- [x] ATANH
- [x] COMBIN
- [x] COMBINA
- [x] COS
- [x] COSH
- [x] COT
- [x] COTH
- [x] CSC
- [x] CSCH
- [X] FACT
- [X] FACTDOUBLE
- [X] GCD
- [x] LCM
- [x] MROUND
- [x] MULTINOMIAL
- [x] PRODUCT
- [x] QUOTIENT
- [x] RANDBETWEEN
- [x] ROMAN
- [x] SEC
- [x] SECH
- [x] SERIESSUM
- [x] SIGN
- [x] SIN
- [x] SINH
- [x] SQRTPI
- [x] SUBTOTAL
- [x] SUMX2MY2
- [x] SUMX2PY2
- [x] SUMXMY2
- [x] TAN
- [x] TANH

**Comment by wojciechczerniak** [comment]
Update:

- [x] ACOS
- [x] ACOSH
- [x] ACOT
- [x] ACOTH
- [x] ASIN
- [x] ASINH
- [x] ATAN
- [x] ATAN2
- [x] ATANH
- [x] COS
- [x] COSH
- [x] COT
- [x] COTH
- [x] CSC
- [x] CSCH
- [x] SEC
- [x] SECH
- [x] SIN
- [x] SINH
- [x] TAN
- [x] TANH

**Comment by wojciechczerniak** [comment]
ROMAN, ARABIC, FACT, FACTDOUBLE, COMBIN, COMBINA, GCD, LCM, MROUND, MULTINOMIAL, QUOTIENT, RANDBETWEEN, SERIESSUM, SIGN, SQRTPI, SUMX2MY2, SUMX2PY2, SUMXMY2 added in #551

**Comment by wojciechczerniak** [comment]
PRODUCT, SUBTOTAL added in #536
