### ISSUE TITLE
Functions to be added after the initial release

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#221]
### Description

Functions list that should be added after the initial release:

- [ ] ACCRINT
- [x] AVERAGEIF
- [ ] AVERAGEIFS
- [x] CHOOSE
- [x] CLEAN
- [ ] CONFIDENCE
- [ ] CONVERT
- [x] COUNT
- [x] COUNTA
- [x] COUNTBLANK
- [x] COUNTIF
- [x] COUNTIFS
- [x] DATEDIF
- [x] DAYS
- [ ] DURATION
- [x] EDATE
- [x] EFFECT
- [x] EXP
- [x] FIND
- [x] FORMULATEXT
- [x] FV
- [x] IFERROR
- [x] IFNA
- [ ] IFS
- [ ] INDIRECT
- [x] ISNA
- [x] LEFT
- [x] LEN
- [x] LN
- [ ] MINIF
- [ ] MINIFS
- [x] NETWORKDAYS
- [x] NOW
- [x] OR
- [x] PMT
- [x] PROPER
- [ ] RANDBETWEEN
- [x] REPT
- [x] RIGHT
- [x] SEARCH
- [x] SQRT
- [x] SUMPRODUCT
- [x] TIME
- [x] TODAY
- [x] TRIM
- [x] WORKDAY

**Comment by voodoo11** [comment]
Functions from list above that are already implemented

- AVERAGEIF
- CHOOSE
- COUNT
- COUNTA
- COUNTBLANK
- COUNTIF
- COUNTIFS
- DAYS
- EXP
- IFERROR
- IFNA
- LN
- OR
- SQRT
- SUMPRODUCT
- FORMULATEXT (#422)

**Comment by voodoo11** [comment]
#436
- LEFT
- RIGHT
- CLEAN
- REPT
- PROPER
- TRIM
- LEN
- SEARCH
- FIND

**Comment by wojciechczerniak** [comment]
Updated:

- DATEIF
- EDATE
- EFFECT
- FV
- ISNA
- NOW
- PMT
- TIME
- TODAY

**Comment by wojciechczerniak** [comment]
NETWORKDAYS and WORKDAY in #534

**Comment by wojciechczerniak** [comment]
Some functions here are out of scope. Our priority is on #150 now.
