### ISSUE TITLE
Date Basis

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#282]
### Description

[Date Basis](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017922_715980110) is a collection of procedures that functions may follow to determine the difference between two dates. Different functions need different basis and some have different defaults.

We may need to extend the DateHelper to handle those correctly.

### Functions

YIELDDISC
YIELD
TBILLEQ
RECEIVED
PRICEMAT
PRICEDISC
PRICE
ODDLYIELD
ODDLPRICE
ODDFYIELD
ODDFPRICE
MDURATION
INTRATE
DURATION
DISC
COUPPCD
COUPNUM
COUPNCD
COUPDAYSNC
COUPDAYS
COUPDAYBS
AMORLINC
ACCRINTM
ACCRINT
YEARFRAC
DAYS360

### Links

https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017922_715980110

**Comment by izulin** [comment]
Implemented in #483
