### ISSUE TITLE
Finish the `getConfig` method

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#301]
### Description

Method is used by the instance to return current configuration to the end-developer and inside Config class for merging configs. Currently, this method returns the whole object which is polluted with methods and private properties. It should return only `ConfigParams`. We shouldn't create them by hand, maybe we can iterate over `defaultConfig` keys.

https://github.com/handsontable/hyperformula/blob/45f6f3d4c90686c3694a161cf1f0146032471bad/src/Config.ts#L552-L554

**Comment by izulin** [comment]
done in #656
