### ISSUE TITLE
Hide `EmptyValue` from public APIs

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#323]
### Description

Sometimes API returns a `Symbol` with no description #128 and it's hard for a new user to find out what it is. In public APIs we accept three different empty values: `null`, `undefined`, and `EmptyValue`. IMO the `EmptyValue` is unnecessary as an input and output value.

- [ ] Return only `null` as an empty value. CellExporter?
- [ ] Accept `undefined` and `null` as an empty value, remove `EmptyValue`
- [ ] Do not export `EmptyValue`, make it an internal symbol only
- [ ] Update all tests to use `null` as an empty value

**Comment by BrianHung** [comment]
Is it actually possible to re-expose this? It is hard to build a custom `IS_BLANK` function since this symbol is not exposed but given as args.

**Comment by sequba** [comment]
@BrianHung, thanks for reaching out. We'll analyze it and fix in scope of issue https://github.com/handsontable/hyperformula/issues/1265

**Comment by AMBudnik** [comment]
Hi @BrianHung I have good news! We've just published HyperFormula v2.6.0 that re-exposes the `EmptyValue` value.
