### ISSUE TITLE
Add watcher for tests

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#326]
### Description

Would be nice to have watcher to Jasmine tests.

**Comment by wojciechczerniak** [comment]
@swistach says we already have this. We need NPM task or documentation how to use it.

**Comment by swistach** [comment]
There are two configurations for karma:
1) normal - `npm run test:browser` - runs tests once and closes all open browsers
2) debug - `npm run test:browser.debug` - runs test only in Chrome until you exit process. It watches changes in `src` and `test` directories and rebuilds them automatically.

both configuration can read additional flag: `--spec`
example: `npm run test:browser.debug -- --spec=matrix.spec.ts`

**Comment by wojciechczerniak** [comment]
Thanks @swistach 

@scarletfog We should add this to the docs

**Comment by scarletfog** [comment]
@swistach what does `--spec` do? Watches the file and... something more? 🤔

**Comment by swistach** [comment]
`--spec` it's an argument to pass path/name pattern to be tested - only files which pass the pattern will be used to run tests. Very useful in development to not run hundreds of files if we want to check only a few. :)

**Comment by wojciechczerniak** [comment]
Thanks @swistach ! Closing as done
