### ISSUE TITLE
It's not possible to run tests in the Internet Explorer 11 on Windows 10

### ISSUE THREAD

**Issue by aninde** [handsontable/hyperformula#330]
An attempt to run tests in Internet Explorer 11 / Windows 10 failed.

`Error during loading: Oczekiwano znaku ')' in http://10.0.0.3:9876/base/karma.starter.js line 14239`

![image](https://user-images.githubusercontent.com/30186818/80717552-5ffb0e80-8af9-11ea-84be-ffacedf1372b.png)

**Comment by wojciechczerniak** [comment]
Fixed in #595 and #598

**Comment by aninde** [comment]
Running the tests in the IE on the current `develop` causes the same result. 
Changing this line false doesn't help. 
https://github.com/handsontable/hyperformula/blob/7ff3ab7888b7bab7aec9555620c3edf16f5b148d/jasmine.json#L12

**Comment by aninde** [comment]
it is still the same on the current `develop`.

**Comment by aninde** [comment]
@swistach discovered that in order to run these tests on IE `gpu.js` from node_modules needs to be removed after `npm i`.
There is no need to build via `npm run bundle-all` to start Karma. 

Tests from the current development pass successfully, apart from 3 related to `gpu.js`. Therefore I am closing the issue.
