### ISSUE TITLE
Diacritics tests failed on mobile UC browser on Android

### ISSUE THREAD

**Issue by aninde** [handsontable/hyperformula#339]
On Chinese mobile browser `UC Browser` does not pass 16 tests. 
Most of them are probably related to a lack of support for diacritics (e.g. `á`).

Apparently, the `UC browser` engine is based on `Blink` and `Chrome V8` (`Chromium`). 
I heard at a testing meeting that it's also based on `Trident` (like `Internet Explorer`)

#### List of failed tests:

1. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/i18n.spec.ts#L42-L48
2. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/i18n.spec.ts#L24-L40
3. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/string-cmp.spec.ts#L90-L96
4. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/string-cmp.spec.ts#L61-L67
5. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/string-cmp.spec.ts#L19-L25
6. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/string-cmp.spec.ts#L47-L53
7. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/string-cmp.spec.ts#L33-L39
8. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/string-cmp.spec.ts#L75-L81
9. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/parser/parser.spec.ts#L112-L118
10. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/parser/parser.spec.ts#L120-L126
11. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/parser/parser.spec.ts#L363-L367
12. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/function-code.spec.ts#L44-L48
13. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/function-code.spec.ts#L24-L33
14. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/named-expressions.spec.ts#L247-L261
15. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/function-char.spec.ts#L24-L40
16. https://github.com/handsontable/hyperformula/blob/2ba17f80090773f990a87603cb661c9d34aa7e27/test/interpreter/function-char.spec.ts#L54-L67

#### Tested on:
`UC Browser V13. 1. 2. 1293`
`Android 9` / Mii A2 Lite
`Android 10` / Huawei Mate 20

**Comment by aninde** [comment]
Two tests fail on Android 9 / Mi A2 Litle and on Android 11 / Galaxy A51. All tests pass on the same device on Chrome.

![image](https://user-images.githubusercontent.com/30186818/122414913-c7874e00-cf87-11eb-9fca-f39114f37b05.png)

**Comment by wojciechczerniak** [comment]
Great! UC Browsers is already by our docs marked as non ICU compliant. Nothing to do on our side.

We can close this and re-check in few months
