### ISSUE TITLE
Some tests "has no expectations"

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#354]
### Description

Some tests are missing asserts. They're using custom functions that are not created as asserts and are relaying on throwing errors, not expecting anything specific. While this works somehow in Jest, Jasmine reports it as an invalid test.

111 tests are affected 🙈 

We should refactor this to a proper matcher?

### Steps to reproduce

1. Run `npm run test:browser.debug`
2. Check the console
3.

### Demo
![Screenshot 2020-05-12 at 00 09 48](https://user-images.githubusercontent.com/4718998/81676984-d2041980-9450-11ea-8edf-028dbc8a058c.png)

**Comment by warpech** [comment]
Me and @sequba decided to close this as it is not evident that it is a problem. It might as well be seen as a feature of the testing framework.
