### ISSUE TITLE
Develop the main demo for HyperFormula - Angular

### ISSUE THREAD

**Issue by scarletfog** [handsontable/hyperformula#375]
### Description

We need a demo of HF for Angular, the expectation is described here:
https://github.com/handsontable/hyperformula/issues/340

### Behavior and data
It should have the very same data as in vanilla JS demo. The latest link with the demo I saw was https://codesandbox.io/s/hyperformula-docs-demo-v14-rl1gy?file=/index.html

### Design
Since we plan to share the same codebase across four different technologies (frameworks + pure js), it would be nice to: 
a) add a title above the table to clearly indicate what we're looking at, and 
b) change the colors of the button in alignment with the leading brand color of each framework.

Angular: primary `#dd0330` + secondary `#fff`

demo: https://codesandbox.io/s/hyperformula-docs-demo-v14-20q7i?fontsize=14&hidenavigation=1&theme=dark

**Comment by wojciechczerniak** [comment]
Demo will work and look like

React: https://handsontable.github.io/hyperformula/guide/integration-with-react.html
Vue: https://handsontable.github.io/hyperformula/guide/integration-with-vue.html

**Comment by swistach** [comment]
Hi @wojciechczerniak,
here is a demo for angular: https://codesandbox.io/s/dkuy4

**Comment by wojciechczerniak** [comment]
@jansiegel Can you commit it to examples repo and embed in the docs?

**Comment by wojciechczerniak** [comment]
Done, added #455 and deployed
