### ISSUE TITLE
Trace dependents

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#441]
Is there a function to get the dependents of a cell?

**Comment by wojciechczerniak** [comment]
No, not a public one. Might be a good feature.

What would be the expected syntax and result? A use case scenario would help as well.

**Comment by doczoidberg** [comment]
I think this could help to trace errors.

An array would be enough. Maybe also optional a recursive parameter to get all dependents. Also precendents would be nice.

**Comment by wojciechczerniak** [comment]
Thanks. I'm mark this as a feature request and will discuss it with the team if and how we can do it.

**Comment by wojciechczerniak** [comment]
Done in #468
