### ISSUE TITLE
Trace "Value of the formula cell is not computed."

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#442]
On some sheets I get "cell is not computed". How can I trace which cell it is?

```
VM1564:37 ERROR Error: Uncaught (in promise): Error: Value of the formula cell is not computed.
Error: Value of the formula cell is not computed.
    at FormulaCellVertex.getCellValue (FormulaCellVertex.js:109)
..
```

How are cross sheet references handled if the sheet was not added?

**Comment by wojciechczerniak** [comment]
> On some sheets I get "cell is not computed". How can I trace which cell it is?

https://github.com/handsontable/hyperformula/blob/508e4e4d9961473a35686354f46e3162be2cd53e/src/DependencyGraph/FormulaCellVertex.ts#L74

You can check `this.cellAddress` in the debugger. For future a simple `JSON.stringify` could help here: `throw Error('Value of the formula cell is not computed. ${JSON.stringify(this.cellAddress)}`

Can you attach a sample data set where you see this error? This shouldn't happen and reproduction would help us debug.

> How are cross sheet references handled if the sheet was not added?

It should be a `#REF!` until the dependency condition is met. Implemented in #207

**Comment by doczoidberg** [comment]
hmm the cell formula looks right: `=IF(B1086-1,J1367-B1096*B1089,J1367+B1096*B1089)`

**Comment by wojciechczerniak** [comment]
Negative indices are ok. Internally, we're using relative references.

> I can't post the whole table here because it's quite huge and also commercial data in it.

Right. Then we have to narrow it down first to a simple example how our developer can reproduce it and propose a fix.

**Comment by doczoidberg** [comment]
> Negative indices are ok. Internally, we're using relative references.

My cell with the formula is  9,1368. So B1086-1 would have the indices 1,1086 which seem to be right.

How can I further debug? cachedCellValue is null. What are the steps before `getCellValue` is called?

I could send you a table with my data to your e-mail....

**Comment by wojciechczerniak** [comment]
Do you have any CRUD operations applied or it's static data you're just trying to load as is?

Sure, you can send it to me at wojciech.czerniak@handsontable.com, that would help a lot to debug the case

**Comment by wojciechczerniak** [comment]
@doczoidberg Thanks to your help we've found and fixed a serious bug deep inside the engine #446. Thanks!

The fix was published yesterday as `v0.1.2`.

**Comment by doczoidberg** [comment]
Is think the error code is still not very informative. I can't trace where the error happens:
![image](https://user-images.githubusercontent.com/1972209/88041460-b7ce7200-cb4a-11ea-8a91-182f25af7203.png)

**Comment by wojciechczerniak** [comment]
This is a very different error type. The one that was thrown is developer error. The one you have here is a calculation result no other than spreadsheet apps provide. It's a value (`#VALUE!` here) wrapped with an object that has few more details: translation or an optional message.

Then the UI provides some dependents tracking #441 to help end-user find a mistake in their formulas.

**Comment by doczoidberg** [comment]
there is no mistake in the formula. In Excel the cell has no error.

**Comment by wojciechczerniak** [comment]
Hard to tell. Not all ODFF evaluation rules are 1:1 with Excel. Additionally, they have [Host-Defined Behaviors](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017868_715980110), other ambiguities are marked in the body of the spec as "Evaluator shall support" or "Evaluator may support" or "Evaluator will choose which one to support and break all other use cases" 🙈 

We've tried to support as many of those variations as possible. Some HF config rules may affect those. Sometimes additional work is needed to fill the gaps. ie. you need to add more date formats that are supported by a spreadsheet app you want to be compatible with.

Let's split those case by case with a simple reproduction example and then we can decide how to support them best.
