### ISSUE TITLE
API reference contains two categories Helper and Helpers

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#452]
### Description

API reference contains two categories Helper and Helpers. Some methods are tagged incorectly. Hepers is the correct one.

![Screenshot 2020-07-14 at 18 01 19](https://user-images.githubusercontent.com/4718998/87448757-89a5db00-c5fc-11ea-8e40-8da79a30d159.png)

### Your environment

* HyperFormula version: 0.1.2
* Browser Name and version: Firefox
* Operating System: Mac OSX

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/hyperformula/pull/460
