### ISSUE TITLE
evaluation of empty string values in if statements

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#453]
I think the evaluation of empty values in if statements is wrong. e.g.:

```
J66 is empty ("")
K66 =IF(J66,J66,K67)

```
does not result in `K67` but throws:

`DetailedCellError {value: "#VALUE!", type: "VALUE", message: ""}`

**Comment by AMBudnik** [comment]
Thank you for sharing. You're right. When the value is `null` or `undefined` this issue is not replicable.

**Comment by doczoidberg** [comment]
https://codesandbox.io/s/friendly-wing-f2ep2

"" also results in an error. But it resolves in the "else" case in excel

**Comment by wojciechczerniak** [comment]
@doczoidberg 🎉  We've just released `v0.1.3` that fixes the issue. Thanks for reporting.

 https://github.com/handsontable/hyperformula/releases/tag/0.1.3

**Comment by doczoidberg** [comment]
there are still errors:
following formula should result to 0 but results in an empty string

![image](https://user-images.githubusercontent.com/1972209/88040737-a0db5000-cb49-11ea-8437-83592b2fc4ca.png)
