### ISSUE TITLE
Config reference contains a doubled date and time category

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#456]
### Description

Config reference contains a doubled category. Some of the options are wrongly categorized. 

The correct one is "Date and Time"

![Screenshot 2020-07-17 at 12 26 20](https://user-images.githubusercontent.com/4718998/87776975-f0a7d780-c828-11ea-8c49-5a724e4e2540.png)

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/hyperformula/pull/459
