### ISSUE TITLE
Improve methods descriptions

### ISSUE THREAD

**Issue by scarletfog** [handsontable/hyperformula#466]
### Description

Work on improving the methods' descriptions. Here is the list with some of the things that should be improved + notes:
- `copy` will throw an error, which does not have a type. And the description is about "unsupported content", but doesn't explain what it is - should be improved.
- `NormalizeFormula` is described as normalizes formula. But never explains what does it mean. We should add the normalized rules.
-Explain what the `scope` is : `undefined` means workbook aka global, sheet name is local
- `getCellFormula`, `getCellSerialized`, `getCellValue`, `getCellValueType`, `getRangeFormulas`, `getRangeValues` are missing info that they throw `NoSheetWithIdError`.
- All methods that accept `SimpleCellAddress` and the sheet property is missing will throw `NoSheetWithIdError` as well: `copy`, `paste`, `cut`, `doesCellHaveFormula`, `doesCellHaveSimpleValue`, `isCellEmpty`, `isCellPartOfMatrix`, `moveColumns`, `moveRows`
- Add an example to `simpleCellAddressFromString` with sheet name 'Sheet1!A6', probably an absolute address as well
- `vlidateFormula` description should mention that validation is purely grammatical, it will not verify if the formula is possible to calculate ie. with sheet name that does not exist engine.validateFormula('=Sheet9999999!A1:A100000000')

**Comment by kirszenbaum** [comment]
* "Explain what the scope..." [x]

**Comment by kirszenbaum** [comment]
@wojciechczerniak - I did most of the above, but I'll need some input for these two points:

- [ ] `NormalizeFormula` is described as [normalizes formula](https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#normalizeformula). But never explains what does it mean. We should add the normalized rules.
**Question: What are "the normalized rules"?**

* [ ] `copy` will throw an error, which does not have a type. And the description is about "unsupported content", but doesn't explain what it is - should be improved.
**Question: the error type doesn't seem to be specified in [Operations.ts](https://github.com/handsontable/hyperformula/blob/8fc5a926c011b658287a6d5a4533824dc4cfdfe5/src/Operations.ts#L597). I haven't found any other reference to it - what does "unsupported content" mean here?**

Thanks for your help!

**Comment by wojciechczerniak** [comment]
I think we need to call @izulin for help here 😄 

- Normalize will parse the formula with our rules and then unparse it so it will be serialized exactly as an engine would do that. But with detailed list I will need @izulin help.
- Should we create specific error type or is this something that should not happen and we may hide it from docs?

**Comment by izulin** [comment]
formula normalization, as far as I understand, parses and then unparses the formula.
Thus, formulas equivalent purely from parser perspective will be `normalized` to be identical. This e.g. ignores sheet name capitalization  and function name capitalization.

See this PR: https://github.com/handsontable/hyperformula/pull/192
and tests here: https://github.com/handsontable/hyperformula/blob/master/test/temporary-formulas.spec.ts

**Comment by izulin** [comment]
Unsupported content: 

it's this line https://github.com/handsontable/hyperformula/blob/cca0887f21c10e56b723d1a5efb98780cc1cd89e/src/Operations.ts#L597

and it is there only so the compiler does not complain. This line of code is unreachable unless someone intentionally pollutes engine with objects of some weird types (impossible to do through API, has to be deep digging into the engine). Mention of this should be removed from the docs.
