### ISSUE TITLE
Add npm run coverage to the docs

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#475]
### Description
#443 added a new command to `package.json`: `npm run coverage`. We should add it to the docs.

### Links

https://handsontable.github.io/hyperformula/guide/testing.html

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by scarletfog** [comment]
Done in https://github.com/handsontable/hyperformula/pull/574
