### ISSUE TITLE
if returns empty string instead 0

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#476]
following formula should result to 0 but results in an empty string

![88040737-a0db5000-cb49-11ea-8437-83592b2fc4ca](https://user-images.githubusercontent.com/1972209/88048528-c79e8400-cb53-11ea-9d00-6fdcd0d86e00.png)

this is important because e.g. the formula can be encapsulated by another one e.g. `VLOOKUP` or in another `IF` statement

**Comment by krzysztofspilka** [comment]
@izulin do we have any update on this?

**Comment by bardek8** [comment]
We started discussing this offline. Actually this case is quite complicated as this is the place of inconsistency between Excel, Google Sheets and LibreOffice Calc.
With the current implementation of HyperFormula we cannot behave as in Excel - this will require storing auxiliary data with each cell value and processing it appropriately. Currently we behave as in Google Sheets.

See the difference between Google Sheets:
![gs](https://user-images.githubusercontent.com/16952569/89042665-9427da80-d347-11ea-9de2-df264905d438.png)

and Excel:
![excel](https://user-images.githubusercontent.com/16952569/89042645-8d996300-d347-11ea-9742-e3d893c1df97.png)

**Comment by doczoidberg** [comment]
maybe a global setting which format and an adaption of thes `if  function` would be enough?

only a special if check for excel would  be enough where 0==undefined results to tue?

Your plans are not to support Excel soon?

**Comment by AMBudnik** [comment]
Thank you for doing the investigation @bardek8. I've spoken with @krzysztofspilka and we both agree that we should consider switching to Excel's approach but as it is not an easy process we should mark this topic as a feature request and get back to it after doing the full investigation. 

@doczoidberg we'll update you on every change to this topic.

**Comment by doczoidberg** [comment]
@AMBudnik  can you give a rough time estimation?

**Comment by AMBudnik** [comment]
@doczoidberg some of our crucial team members are ooo, we cannot start the process without them. As soon as they meet and agree on the next step towards the goal this topic will get updated accordingly.

**Comment by doczoidberg** [comment]
any news here?

**Comment by bardek8** [comment]
Sorry for the late reply. Unfortunately, currently we cannot provide any precise time estimations.
This is an involved issue that requires deep understanding of the Excel's behavior, which is very different from GoogleSheets and LibreOffice. We envisage that this will be a big change in HF, so we decided to address it in the later future, after we finish the project of adding new functions to HF.

**Comment by doczoidberg** [comment]
I think you are overcomplating things here. Plese rethink about my comment:

If undefined==0 results to true and returns "0" if a cell reference is blank for excel tables all cases should be right? No need for auxilary data? Only a global setting for the calculation type and an adapted if function which handles the different calcultation types.

Can you give me hints where I have to edit the code?

**Comment by izulin** [comment]
Thanks! As @bardek8 mentioned in #496, we will investigate it soon and hopefully this will not be that bad as we thought first.
Here are the relevant places of code to start working with `IF`:

https://github.com/handsontable/hyperformula/blob/develop/src/interpreter/plugin/BooleanPlugin.ts#L24

https://github.com/handsontable/hyperformula/blob/develop/src/interpreter/plugin/FunctionPlugin.ts#L223

https://github.com/handsontable/hyperformula/blob/develop/src/interpreter/ArithmeticHelper.ts#L292

And here we process the second argument of `IF`:

https://github.com/handsontable/hyperformula/blob/develop/src/interpreter/plugin/FunctionPlugin.ts#L225

**Comment by wojciechczerniak** [comment]
Done in #500. Implemented as a Vendor Behaviour setting `evaluateNullToZero`.

https://github.com/handsontable/hyperformula/blob/4e092bd57a60005e8c5e687ef7f316dc269b13d3/src/Config.ts#L201-L209
