### ISSUE TITLE
Trace Dependents besides Precedents

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#487]
We can get the **precedents** of a cell:
https://github.com/handsontable/hyperformula/pull/468

But not the **dependents** yet.

**Comment by izulin** [comment]
Both the requested features are implemented and are currently available in the `develop` branch:
[precedents](https://github.com/handsontable/hyperformula/blob/2293528a60647440012d563c85100f4f0d3104d1/src/HyperFormula.ts#L2240
)
[dependents](https://github.com/handsontable/hyperformula/blob/2293528a60647440012d563c85100f4f0d3104d1/src/HyperFormula.ts#L2209)
Please let us know if they work as you expect.

**Comment by wojciechczerniak** [comment]
Added in  #468
