### ISSUE TITLE
Number decimal separators

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#489]
Excel can have different number separators.

Is it possible to switch them in HF?

![image](https://user-images.githubusercontent.com/1972209/90011687-52315980-dca2-11ea-995b-0870450e00a0.png)

**Comment by bardek8** [comment]
Yes, it is. We have the following config options for that: `decimalSeparator` and `thousandSeparator`. You can also change the separator of function arguments modifying `functionArgSeparator`. 

Please see the [documentation](https://handsontable.github.io/hyperformula/api/interfaces/configparams.html#number) with more details.
