### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#490]
Excel does work with trailing commas in parameter lists. HF does not. E.g.
`
=MAX(A1,A2,A3,)`

**Comment by izulin** [comment]
Actually HF is beginning to support such syntax. We introduced it in PR#480 and already some functions (see `CONCATENATE`, `AND`, `OR`, `SWITCH`,`CHOOSE`) work with trailing commas in the parameter list. However, this is a larger effort to make all functions support it and use the new framework, so this will take some time.

**Comment by doczoidberg** [comment]
ok, hope to see a new release soon ;)

**Comment by wojciechczerniak** [comment]
Do we have a list of functions that we need to update to call this fixed? Needs a definition of done

**Comment by izulin** [comment]
> Do we have a list of functions that we need to update to call this fixed? Needs a definition of done
> 
> EDIT: Or maybe we can fix this at the lvl higher than functions and drop the argument before sending it to the function body?

That is the plan: as I said, this is an artefact of not all the functions using new system of arguments coercion.

**Comment by izulin** [comment]
> Excel does work with trailing commas in parameter lists. HF does not. E.g.
> ` =MAX(A1,A2,A3,)`

Should be corrected now in the `develop` branch.

**Comment by wojciechczerniak** [comment]
Thanks! Closing as done in #515
