### ISSUE TITLE
VLOOKUP does not work

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#491]
```
hfInstance.setCellContents(hfInstance.simpleCellAddressFromString("B45", mytable), 0);
hfInstance.setCellContents(hfInstance.simpleCellAddressFromString("B46", mytable), 1);
hfInstance.setCellContents(hfInstance.simpleCellAddressFromString("C45", mytable), 3);
hfInstance.setCellContents(hfInstance.simpleCellAddressFromString("C46", mytable), 4);
hfInstance.setCellContents(hfInstance.simpleCellAddressFromString("C41", mytable), "=VLOOKUP(1,B45:C46,2,FALSE)");
```

C41 should return `4` but throws

`DetailedCellError {value: "#VALUE!", type: "VALUE", message: ""}`

**Comment by izulin** [comment]
The issue is actually not with `VLOOKUP`, but with `TRUE/FALSE`. If you replace `FALSE` with `FALSE()` it should work. If you prefer to use `FALSE`, you can use the named expression feature, i.e. in this way:
```
hfInstance.addNamedExpression('TRUE', '=TRUE()')
hfInstance.addNamedExpression('FALSE', '=FALSE()')
```

**Comment by doczoidberg** [comment]
ok, this is needed for excel imports. Maybe there should be an excel option or at least documentation for excel imports

**Comment by izulin** [comment]
That is a good idea, this should be better documented.
