### ISSUE TITLE
Considerations for Excel

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#496]
Excel implementation is wrong on ISBLANK, IF checks and concentations with "&".

There are different approaches to solve this problem.

1. handling empty cell values as an empty string (i think this is how excel handles it. Excel does not know "null" in my opinion)
- if function has to be adapted: ""=0 results to true and return 0 instead an empty string
- ISBLANK function has to be adapted: empty string results to blank
this solves: https://github.com/handsontable/hyperformula/issues/495 https://github.com/handsontable/hyperformula/issues/488

2. handling empty cell values as null
- if function has to be adapted: ""=0 results to true and return 0 instead an empty string
- replace null to empty strings "" in string concenations with "&"
- ISBLANK can be the same

3. empty cell value null or empty string
- the value of an empty cell results to 0 (https://stackoverflow.com/questions/43191270/excel-why-the-value-of-a-blank-cell-is-zero)
- ISBLANK does not check the value but the formula(!)

**there is no need to save additional value as stated in the issue here**: https://github.com/handsontable/hyperformula/issues/476

If I don't see something please tell me.

**Comment by doczoidberg** [comment]
My opinion about excel:

- Null values do not exist. Therefore other libraries export empty strings for empty cells an not null.
- Excel handles an empty string as a 0 if it is in a numeric context. Only if it is in a string context it is handled as and empty string. Therefore B1 results to 0 here:
![](https://user-images.githubusercontent.com/16952569/89042645-8d996300-d347-11ea-9742-e3d893c1df97.png)
1. A1=0 because A1 is handled as 0 because there is a numeric context
2. it returns 0

**Comment by doczoidberg** [comment]
I have gone through the issues once again. Sorry for all the text but I want you to understand by rhoughts about it.
In my opinion the right way to handle things is:

1. empty cells are empty string. Null does not exist
2. empty cell **values** return 0
3. string concentation is the exception. This is the difficult case in my opinion
4. `ISBLANK` checks the contents, not the value "" is "blank"

**Comment by doczoidberg** [comment]
...in javascript null+"foo" results to "foo". null*3 results to 3. Maybe one could just replace "&" with "+" and evaluate the token with javascripts `eval(val)`?

**Comment by bardek8** [comment]
Many thanks for the investigation! Indeed, it seems that we might have over complicated with that (as I mentioned in #476 ) and trying to align more with Excel’s semantics will actually make things easier.

So next week we’ll start with #495  (thanks for spotting that!) and then will try to see how close we can get to Excel’s behavior. We’ll keep you updated.

**Comment by bardek8** [comment]
@doczoidberg , @izulin already merged to `develop` two PRs: #499 and #500 that should address the issues you spotted. Could you please check if now the behavior is closer to Excel and as you expected?

**Comment by doczoidberg** [comment]
i compiled the es version and production version from the develop branch. Can you give a hint how I can use the files in my angular app?

**Comment by doczoidberg** [comment]
i compiled the es version and production version from the develop branch. Can you give a hint how I can use the files in my angular app?
I added the the `hyperformula.full.min.js` to my angular.json scripts but get the error `ReferenceError: HyperFormula is not defined` on 
 `const hfInstance = HyperFormula.buildEmpty(options);`

**Comment by doczoidberg** [comment]
OK, compiles now. I did `npm run bundle:es` added the files to my project and added to my package.json

```
"chevrotain": "^7.0.1",
"gpu.js": "^2.10.0",
"tiny-emitter": "2.1.0"
```

But now I get the error
```

Error: Language not registered.
Error: Language not registered.
    at Function.getLanguage (HyperFormula.js:3553)
    at new Config (Config.js:154)
```

**Comment by wojciechczerniak** [comment]
@doczoidberg Would be best if you could write to support@handsontable.com @AMBudnik and @pnowak will help you with setting up everything correctly. Some details are missing and the response time here may not be optimal, I almost lost your question when I was skimming the notifications list.

**Comment by wojciechczerniak** [comment]
Just to clarify, Excel does see an empty string and blank cell reference as 0, but they're not the same. Although there is no `null` value, it is called BLANK, and they have a whole page explaining the difference https://docs.microsoft.com/en-us/office/troubleshoot/excel/isblank-function-return-false. We're using `null` to differentiate between BLANK and `""` an empty string.

All other points are correct. We coerce the value (empty string included) to numeric values if that is the context of input arguments, ie. arithmetic operators are used. BLANKS are indeed complicated, we had a lot to do to handle them correctly https://github.com/handsontable/hyperformula/issues?q=blank so big thanks for reporting inconsistencies 💪 

I'm proposing a new page in the documentation  #535 that should take all the options into consideration.

`evaluateNullToZero` compatibility option was introduced in #476 and closed
The bundling problem was answered in #508 and solved 

I guess we can close this now. Please reopen if I missed anything
