### ISSUE TITLE
Cross references do not work on all sheet names?

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#509]
```
Material-Mapping C3: GL24h

F5 ='Material-Mapping'!C3
DetailedCellError {value: "#ERROR!", type: "ERROR", message: "Parsing error"}message: "Parsing error"type: "ERROR"value: "#ERROR!"__proto__: Object
```

renaming the sheet to `MaterialMapping` without `-` it works

**Comment by wojciechczerniak** [comment]
Looks like we're missing special characters in our test

https://github.com/handsontable/hyperformula/blob/cea4d22ba5c17bf3b96c12f661428dbc413b5a18/test/parser/parser.spec.ts#L364-L373

**Comment by voodoo11** [comment]
According to [ODFF](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html#__RefHeading__1017946_715980110), quoted sheet name may contain any character except `'` unless it is escaped with second quote. #514 should resolve that issue.

**Comment by wojciechczerniak** [comment]
Thanks @voodoo11
