### ISSUE TITLE
MID function supported?

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#523]
`K109` is `VGS-SK 08 G 300`
`L1231 =(MID($K$109,13,3)/10)`

I get a #name error:
L1231 DetailedCellError {value: "#NAME?", type: "NAME", message: ""}

the result should be 30

**Comment by wojciechczerniak** [comment]
Yup, `#NAME?` indicates that there is no such function yet.

**Comment by doczoidberg** [comment]
is it possible to implement this function (soon)?

**Comment by wojciechczerniak** [comment]
I see it already is implemented in #518, should be merged soon

**Comment by wojciechczerniak** [comment]
Let me close this as a duplicate, MID will be implemented as a part of the #159 task
