### ISSUE TITLE
engine reloading does not carry over added named expressions

### ISSUE THREAD

**Issue by izulin** [handsontable/hyperformula#527]
### Description

See MWE below:

```
const engine = HyperFormula.buildFromArray([])
engine.addNamedExpression('TRUE', '=TRUE()')
engine.addNamedExpression('FALSE', '=FALSE()')
engine.setCellContents(adr('A1'), '=FALSE')
engine.rebuildAndRecalculate()
expect(engine.getCellValue(adr('A1'))).toEqual(false)
```

### Steps to reproduce

1.
2.
3.

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by izulin** [comment]
done in #531

**Comment by doczoidberg** [comment]
does not work for me yet:

https://github.com/doczoidberg/hftests2/blob/735c425b52f0050b244fb3b994fe166f7118027b/src/app/app.component.ts#L58

**Comment by izulin** [comment]
> does not work for me yet:
> 
> https://github.com/doczoidberg/hftests2/blob/735c425b52f0050b244fb3b994fe166f7118027b/src/app/app.component.ts#L58

Could it be by any chance that it's not run on current `develop` branch code?
E.g. following code:
```
    const engine = HyperFormula.buildEmpty()
    engine.addNamedExpression('TRUE', '=TRUE()')
    engine.addNamedExpression('FALSE', '=FALSE()')
    engine.rebuildAndRecalculate()
    engine.addNamedExpression('TRUE', '=TRUE()')
    engine.addNamedExpression('FALSE', '=FALSE()')
```

results in exception:
`Error: Name of Named Expression 'TRUE' is already present`

**Comment by doczoidberg** [comment]
I compiled it today

**Comment by izulin** [comment]
> I compiled it today

Can you try to run just the example I posted above, and see whether you receive exception or not?

**Comment by doczoidberg** [comment]
it works for me compiled 10 hours ago

**Comment by izulin** [comment]
> it works for me compiled 10 hours ago

On newest develop, it should throw an exception.

**Comment by doczoidberg** [comment]
I did pull the new version and yes, it throws that execption now
