### ISSUE TITLE
VLOOKUP overwrites errors when coerced

### ISSUE THREAD

**Issue by izulin** [handsontable/hyperformula#528]
### Description
VLOOKUP (and maybe few other functions) overwrite the error value (and error message) when coercion is impossible

example:
```
=VLOOKUP(1,A10:A11,1, NA())
```

should return NA error, and returns VALUE error.

### Steps to reproduce

1.
2.
3.

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by voodoo11** [comment]
Fixed in #520

**Comment by wojciechczerniak** [comment]
Thanks 🥇
