### ISSUE TITLE
Prepare the documentation for the release 0.3.0

### ISSUE THREAD

**Issue by scarletfog** [handsontable/hyperformula#546]
### Description
We need several things to prepare in the documentation before the upcoming release. (`v0.3.0`)

### Checklist
- [ ] Add missing information in the changelog.md file (if any), tidy the changelog up, add the release date
- [ ] Add a `@since` tag for new methods in the API reference
- [ ] Mark the versions of functions (`v0.3.0` badge)
- [ ] Check if the documentation was updated with new functions

### Type of issue
- [x] Missing documentation

**Comment by wojciechczerniak** [comment]
Done in #552
