### ISSUE TITLE
Improve Custom Functions page

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#557]
### Description
Since we've created custom functions tutorial there were some changes. Custom functions have now arguments validation, extended meta-data and `runFunction` callback. Maybe we can keep the basic (if it still works correctly) and need an Advanced Custom Functions page. How to create function alias.

BTW. There's an error
![Screenshot 2020-11-02 at 11 35 07](https://user-images.githubusercontent.com/4718998/97858563-9e1ef800-1cff-11eb-861b-62209fa06830.png)
![Screenshot 2020-11-02 at 11 43 28](https://user-images.githubusercontent.com/4718998/97859295-b5121a00-1d00-11eb-9f40-3855e7ff42fb.png)

### Links
https://handsontable.github.io/hyperformula/guide/custom-functions.html

### Type of issue

- [x] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by krzysztofspilka** [comment]
@wojciechczerniak  Absolutely, we should do that. However, a custom function is already an advanced feature of the engine, thus no need to limit the new additions to so-called "advanced users".

I think we just need to add another section to the existing page, and that's it.

**Comment by kirszenbaum** [comment]
Self-note - take this into account: https://github.com/handsontable/hyperformula/discussions/734#discussioncomment-925414

**Comment by kirszenbaum** [comment]
- [x] Fixed errors depicted in the screenshots
