### ISSUE TITLE
Wrong demo on date and time page

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#568]
### Description
Wrong demo on date and time page [1]. Source code [2] shows that it links to localizing functions demo. Please fix this ASAP so we can publish it with the new version.

### Links
[1] https://handsontable.github.io/hyperformula/guide/date-and-time-handling.html#demo
[2] https://github.com/handsontable/hyperformula/blob/master/docs/guide/date-and-time-handling.md

### Type of issue

- [ ] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by scarletfog** [comment]
done in https://github.com/handsontable/hyperformula/pull/570
