### ISSUE TITLE
List of supported events

### ISSUE THREAD

**Issue by warpech** [handsontable/hyperformula#586]
### Description

I can see in the docs that it is possible register an event listener https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#events. However, the API documentation of the `on` and `off` methods do not contain a list of available event (event names). 

I understand that it is not DRY to maintain such a list there, but maybe we could at least add a clue like:

> To see the available event names, search this API reference for the keyword `"Fires"` that can be found in the method descriptions.

### Links

https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#sheets

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by kirszenbaum** [comment]
- `off`: fixed grammar + added info about searching for `fires`
- `on`: fixed grammar + added info about searching for `fires`
- `once`: fixed grammar + added info about searching for `fires`

**Comment by kirszenbaum** [comment]
Changes the `fires` keyword info to a link to the Event Types section.
