### ISSUE TITLE
copy-paste leads to incorrect serialization

### ISSUE THREAD

**Issue by izulin** [handsontable/hyperformula#587]
### Description
Moving cells with relative references can lead to engine with references into negative address space. This is handled correctly by evaluation, but incorrectly by serialization.

```
    const engine = HyperFormula.buildFromArray([
      [null, null],
      [null, '=A1'],
    ])

    engine.copy({sheet: 0, col: 1, row: 1}, 1, 1)
    engine.paste({sheet: 0, col: 0, row: 0})

    engine.getCellValue({sheet: 0, col: 0, row: 0})  //REF error (correct)
    engine.getCellSerialized({sheet: 0, col: 0, row: 0}) //'=0' (incorrect)
```

### Steps to reproduce

1.
2.
3.

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
Done in #585
