### ISSUE TITLE
MEDIAN behaviour is not consistent with other aggregating functions

### ISSUE THREAD

**Issue by izulin** [handsontable/hyperformula#601]
### Description
MEDIAN should coerce explicitly given arguments to numeric, and ignore nonnumeric elements of ranges.

### Steps to reproduce

MEDIAN("12", "11", "13")

should output 12, not error

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
Fixed in #602
