### ISSUE TITLE
Unwanted string slice when cell value starts with `'`

### ISSUE THREAD

**Issue by nikersify** [handsontable/hyperformula#617]
To integrate HyperFormula with Handsontable properly, we need the formulas to be "semantically reversible" - the value that a user puts in, after whatever cell type tranformations, should be the same as the serialized value they get out that we'll display a cell editor for them.

The case with escaped formulas with `'` seems not to meet that goal, consider this case:
1. User sets cell contents to `"'sum(2, 2)"` (`hf.setCellContents(address, "'=sum(2, 2)")`).
2. User wants to edit cell contents, the editor value we show them directly with `hf.getCellSerialized` will now be `=sum(2, 2)`, with the leading `'` omitted.
3. User saves cell contents without any edits of their own, now `hf.getCellValue` returns `4` instead of the escaped formula.

See the snippet below.

---

```typescript
import {HyperFormula} from 'hyperformula'

const hf = HyperFormula.buildFromArray([['']], {licenseKey: 'non-commercial-and-evaluation'})

const address = {
	sheet: 0,
	row: 0,
	col: 0
}

hf.setCellContents(address, "'=sum(2, 2)")

console.log(hf.getCellSerialized(address)) // "=sum(2, 2)", desired "'=sum(2, 2)"
console.log(hf.getCellValue(address)) // "=sum(2, 2)", desired "'=sum(2, 2)"

hf.setCellContents(address, hf.getCellSerialized(address))

console.log(hf.getCellValue(address)) // "4", desired "'=sum(2, 2)"
```

The problematic lines seem to be
https://github.com/handsontable/hyperformula/blob/f29c7ad6ffabda35097d88e6e932540a0b4e8d17/src/CellContentParser.ts#L176-L178

---

We'd be happy with always having the leading `'` characters returned as we can easily trim them during presentation.

---

* HyperFormula version: `0.4.0` & [`develop`](https://github.com/handsontable/hyperformula/tree/f29c7ad6ffabda35097d88e6e932540a0b4e8d17)

**Comment by izulin** [comment]
closed with #619
