### ISSUE TITLE
Remove deprecated vlookupThreshold 

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#620]
### Description

For `v1.0` we should remove the `vlookupThreshold` options. It was replaced by `binarySearchThreshold`. No need to ship deprecated option.

- [ ] Remove config option
- [ ] Remove from API [vlookupThreshold](https://handsontable.github.io/hyperformula/api/interfaces/configparams.html#vlookupthreshold) (should happen automatically when we remove TSDoc)
- [ ] Remove from docs if mentioned

### Links
https://handsontable.github.io/hyperformula/api/interfaces/configparams.html#vlookupthreshold

**Comment by izulin** [comment]
done in #627
