### ISSUE TITLE
An empty `updateConfig` call throws deprecation warnings.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/hyperformula#632]
### Description
Calling the `updateConfig` method with an empty object throws deprecation warnings:
```
vlookupThreshold option is deprecated since v.0.3.0, please use binarySearchThreshold
```
I'm guessing that's not a desired behaviour.

### Steps to reproduce
```
import HyperFormula from "hyperformula";

const hf = HyperFormula.buildEmpty({});

hf.updateConfig({});
```

### Demo
https://codesandbox.io/s/staging-leftpad-q1d26?file=/src/index.js

### Your environment

* HyperFormula version: `0.4.0`

**Comment by izulin** [comment]
Is it on `develop` branch? 
Since https://github.com/handsontable/hyperformula/pull/627 there are no calls in the project to the function that makes deprecation warning, so this should not be possible on `develop`.

**Comment by jansiegel** [comment]
Nope, on `develop` it looks good! Cool, thx!
