### ISSUE TITLE
Problem evaluating text based built-in functions

### ISSUE THREAD

**Issue by haraleib** [handsontable/hyperformula#636]
### Description

Evaluation of text based built-in functions (https://handsontable.github.io/hyperformula/guide/built-in-functions.html#list-of-available-functions) seems not working accordingly.

### Steps to reproduce

1.  Go to one of your sandbox demos. In this case https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/0.5.x/built-in-functions?from-embed=&file=/src/data.js:318-325
2. Switch to src/data.js
3.  Change line 14 to ` ["=EXACT(TEXT(Data!A4); TEXT(Data!A4))"],`
4.  Change line 15 to ` ["=EXACT(TEXT(12345); TEXT(12345))"],`

In the Browser tab on the right, there is no valid generated value for the functions.
![image](https://user-images.githubusercontent.com/19574757/114873075-3a930d80-9dfb-11eb-904d-2552e9b101a9.png)

Got the same problems when trying to evaluate other text based build-in functions.

### Demo

https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/0.5.x/built-in-functions?from-embed=&file=/src/data.js

(+ Steps 3 and 4 from "Steps to reproduce")

### Your environment

https://codesandbox.io

* HyperFormula version: 0.5.x
* Browser Name and version: Google Chrome
* Operating System: Windows 10

**Comment by izulin** [comment]
Function TEXT takes two arguments, and the second one is formatting string that should be applied to the first argument.

**Comment by haraleib** [comment]
Thanks for the answer. Seems obvious for the problem.
Nevertheless, using `=EXACT('1234'; '1234') `  results in the same problem
![image](https://user-images.githubusercontent.com/19574757/114880548-6ebdfc80-9e02-11eb-9caa-dfe9c9b0dcff.png)

**Comment by izulin** [comment]
I believe the problem lies in using `;` as a function separator. The default setting is `,`, but there is a config option to switch it to `;` though.

**Comment by haraleib** [comment]
Results in the same behaviour
![image](https://user-images.githubusercontent.com/19574757/114885639-235a1d00-9e07-11eb-8fdc-2e45e8dff658.png)

**Comment by izulin** [comment]
You need to use `"` for string delimitation.

**Comment by haraleib** [comment]
Thank you. It is working now.
