### ISSUE TITLE
listNamedExpressions will not return the expected result

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#638]
### Description

`listNamedExpressions` can return a flat array with strings that are names of the expressions. But expressions can be scoped and the same name can be used. Shouldn't `listNamedExpressions` have a `scope` argument to list all available expression in the context? Then `listNamedExpressions(undefined)` will return global scope or all named expressions in some other way?

### Steps to reproduce

1. Add `myName` expression with scope `Sheet 1`
2. Add `myName` expression with scope `Sheet 2`
3. Add `myName` expression with global scope
4. What will `listNamedExpressions` return? We have a conflict for a simple array list of strings

### Demo
```ts
  it('listing named expressions', () => {
    const engine = HyperFormula.buildFromSheets({ 'Sheet 1': [[]], 'Sheet 2': [[]] })
    engine.addNamedExpression('myName', '=42', 'Sheet 1')
    engine.addNamedExpression('myName', '=42', 'Sheet 2')
    engine.addNamedExpression('myName', '=42')

    const namedExpressions = engine.listNamedExpressions()

    expect(namedExpressions).toEqual([
      'myName',
      'myName',  // ????
    ])
  })
```

### Your environment

* HyperFormula version: 0.5.0
* Browser Name and version: any
* Operating System: any

**Comment by izulin** [comment]
After examination, it seems that it only returns global ones.

**Comment by wojciechczerniak** [comment]
Ok, so this is more a feature request. Without argument or `undefined` we get global scope. This is compatible with `scope` arguments across API and will be backward compatible for this method. 

What we're missing is an optional `scope` argument here to get named expressions for a scope?
