### ISSUE TITLE
removal of scoped named expressions

### ISSUE THREAD

**Issue by izulin** [handsontable/hyperformula#641]
### Description
1. Removing sheet does not remove scoped named expressions assigned to this sheet.
2. Trying to remove named expression scoped with nonexistent sheet results in an error.

1+2 gives:

```
    const engine = HyperFormula.buildFromSheets({'Sheet1': [[]], 'Sheet2': [[]]})
    engine.addNamedExpression('TRUE', true, 'Sheet1')
    expect(engine.listNamedExpressions()).toEqual(['TRUE'])
    engine.removeSheet('Sheet1')
    expect(engine.listNamedExpressions()).toEqual(['TRUE']) //named expression is still registered
    engine.removeNamedExpression('TRUE', 'Sheet1') //throws exception Error: There's no sheet with name 'Sheet1'
```

(note: this is on my private branch where `listNamedExpressions()` produces ALL named expressions)

### Steps to reproduce

1.
2.
3.

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by izulin** [comment]
Here is my take:
- we cannot add named expressions scoped with nonexistent sheets (*preload* named expression waiting for sheet to appear)
- scoped named expressions are stored internally assigned to sheet *number*, not to sheet *name*
- hence, we should remove all named expressions scoped with sheet that is going to be removed

**Comment by wojciechczerniak** [comment]
I agree. 

> we cannot add named expressions scoped with nonexistent sheets (preload named expression waiting for sheet to appear)

Just this one will be problematic. Once you load sheet with named expressions there will be #REF! errors or it will use global scoped ones if they exists, the results may be unexpected. We should create a test for both scenarios and figure out the solution.

First idea, batch:
```ts
hf.batch(() => {
  hf.addSheet()
  hf.addNamedExpression()
  hf.setSheetContent()
});
```

Second idea, extend `addSheet` method:

```ts
hf.addSheet(sheetName, sheetData, namedExpressions)
```

**Comment by izulin** [comment]
`addSheet` and general builder methods should be refactored. In general, serialization should consider Named Expressions (both ways).
