### ISSUE TITLE
extend `addSheet` method

### ISSUE THREAD

**Issue by izulin** [handsontable/hyperformula#643]
extend `addSheet` method:

```ts
hf.addSheet(sheetName, sheetData, namedExpressions)
```

_Originally posted by @wojciechczerniak in https://github.com/handsontable/hyperformula/issues/641#issuecomment-823800915_

**Comment by izulin** [comment]
addSheet and general builder methods should be refactored. In general, serialization should consider Named Expressions (both ways).

**Comment by wojciechczerniak** [comment]
True. We've got this covered by #319 and  #335.

Serialization with #335:
```ts
const serializedSheets = hfInstance.getAllSheetsSerialized()
const serializedNamedExpressions = hfInstance.getAllNamedExpressionsSerialized()
```

Then we can send this to the server and back to recreate the instance with #319:
```ts
new HyperFormula.buildFromSheets(serializedSheets, {
  namedExpressions: serializedNamedExpressions
})
```

Extending `addSheet` is a nice addition, and was requested few times. People want to add sheet with content:

```ts
hf.addSheet(sheetName, sheetData)
```

But you're right, the "content" for sheet are also named expressions.

**Comment by izulin** [comment]
> But you're right, the "content" for sheet are also named expressions.

What other content could it be?

**Comment by wojciechczerniak** [comment]
@izulin I always thought that it should be name + cell content as in `hf.addSheet(sheetName, sheetData)` but your syntax has added named expressions `hf.addSheet(sheetName, sheetData, namedExpressions)`, which is a very good idea because they're often need to properly initialize the new sheet. That's all.

I don't see any more content for sheets atm

**Comment by izulin** [comment]
Should it be possible to add global namedexpression this way, or only scoped to this sheet?

**Comment by izulin** [comment]
on a second thought, refactoring builders is ok and necessary, but `addSheet` with namedexpression can be achieved already with batching

**Comment by wojciechczerniak** [comment]
Good question. IMO scoped to the given sheet. Used don't know the sheet ID yet.
The `scope` key should be removed from the definition? ie:
`hf.addSheet(sheetName: sheet, sheetData: CellValue[][], namedExpressions: Omit<NamedExpression, "scope">)`

And yes, this is currently possible. Not a priority if you have more in backlog

**Comment by wojciechczerniak** [comment]
On second thoughts, we already have everything necessary to do this in one go:

```ts
function addSheet(sheetName: string, sheetData: CellValue[][], namedExpressions: Omit<NamedExpression, "scope">) {
    hfInstance.batch(function () {
        if (hfInstance.isItPossibleToAddSheet(sheetName)) {
            sheetName = hfInstance.addSheet(sheetName)
            const sheetId = hfInstance.getSheetId(sheetName)

            hfInstance.addNamedExpressions(sheetId, namedExpressions)
            hfInstance.setSheetContent(sheetId, sheetData)
        }
    })
}
```

And having multiple ways to do the same thing in API is IMO a very bad practice. We should have minimal atomic methods that anyone can compose to their likening as shown above
