### ISSUE TITLE
We should use sheetId consistently across our public APIs

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#645]
### Description

We should cleanup APIs before releaseing `v1.0.0`

@budnix mentioned this long time ago, @jansiegel and @nikersify recently. Sometimes we use `sheetName` and sometimes `sheetId` in our APIs. We should stick to one. Since `SimpleCellAddress` is our base format for cell addresses then my proposal is to use `sheetId` which is used for cell addresses.

A list of methods that need to be adjusted is short relatively to the methods that already use `sheetId`:

`clearSheet(sheetName: string): ExportedChange[]`
`isItPossibleToClearSheet(sheetName: string): boolean`
`isItPossibleToRemoveSheet(sheetName: string): boolean`
`isItPossibleToReplaceSheetContent(sheetName: string, values: RawCellContent[][]): boolean`
`removeSheet(sheetName: string): ExportedChange[]`
`setSheetContent(sheetName: string, values: RawCellContent[][]): ExportedChange[]`
`addNamedExpression(expressionName: string, expression: RawCellContent, scope?: undefined | string, options?: NamedExpressionOptions): ExportedChange[]` scope is sheetName
`changeNamedExpression(expressionName: string, newExpression: RawCellContent, scope?: undefined | string, options?: NamedExpressionOptions): ExportedChange[]` scope is sheetName
`getNamedExpression(expressionName: string, scope?: undefined | string): Maybe‹NamedExpression›` scope is sheetName
`getNamedExpressionFormula(expressionName: string, scope?: undefined | string): Maybe‹string›` scope is sheetName
`getNamedExpressionValue(expressionName: string, scope?: undefined | string): Maybe‹CellValue›` scope is sheetName
`isItPossibleToAddNamedExpression(expressionName: string, expression: RawCellContent, scope?: undefined | string): boolean` scope is sheetName
`isItPossibleToChangeNamedExpression(expressionName: string, newExpression: RawCellContent, scope?: undefined | string): boolean` scope is sheetName
`isItPossibleToRemoveNamedExpression(expressionName: string, scope?: undefined | string): boolean` scope is sheetName
`removeNamedExpression(expressionName: string, scope?: undefined | string): ExportedChange[]` scope is sheetName
`calculateFormula(formulaString: string, sheetName: string): CellValue`

### Dunno

`doesSheetExist(sheetName: string): boolean` kind of does not make sense to check for sheetId, if we can `getSheetId` then it exists 🤔 

### Those are ok, already use `sheetId`

👍 `getSheetDimensions(sheetId: number): SheetDimensions`
👍 `getSheetFormulas(sheetId: number): Maybe‹string›[][]`
👍 `getSheetName(sheetId: number): Maybe‹string›`
👍 `getSheetSerialized(sheetId: number): RawCellContent[][]`
👍 `getSheetValues(sheetId: number): CellValue[][]`
👍 `addRows(sheetId: number, ...indexes: ColumnRowIndex[]): ExportedChange[]`
👍 `isItPossibleToAddRows(sheetId: number, ...indexes: ColumnRowIndex[]): boolean`
👍 `isItPossibleToMoveRows(sheetId: number, startRow: number, numberOfRows: number, targetRow: number): boolean`
👍 `isItPossibleToRemoveRows(sheetId: number, ...indexes: ColumnRowIndex[]): boolean`
👍 `isItPossibleToSetRowOrder(sheetId: number, newRowOrder: number[]): boolean`
👍 `isItPossibleToSwapRowIndexes(sheetId: number, rowMapping: [number, number][]): boolean`
👍 `moveRows(sheetId: number, startRow: number, numberOfRows: number, targetRow: number): ExportedChange[]`
👍 `removeRows(sheetId: number, ...indexes: ColumnRowIndex[]): ExportedChange[]`
👍 `setRowOrder(sheetId: number, newRowOrder: number[]): ExportedChange[]`
👍 `swapRowIndexes(sheetId: number, rowMapping: [number, number][]): ExportedChange[]`
👍 `addColumns(sheetId: number, ...indexes: ColumnRowIndex[]): ExportedChange[]`
👍 `isItPossibleToAddColumns(sheetId: number, ...indexes: ColumnRowIndex[]): boolean`
👍 `isItPossibleToMoveColumns(sheetId: number, startColumn: number, numberOfColumns: number, targetColumn: number): boolean`
👍 `isItPossibleToRemoveColumns(sheetId: number, ...indexes: ColumnRowIndex[]): boolean`
👍 `isItPossibleToSetColumnOrder(sheetId: number, newRowOrder: number[]): boolean`
👍 `isItPossibleToSwapColumnIndexes(sheetId: number, columnMapping: [number, number][]): boolean`
👍 `moveColumns(sheetId: number, startColumn: number, numberOfColumns: number, targetColumn: number): ExportedChange[]`
👍 `removeColumns(sheetId: number, ...indexes: ColumnRowIndex[]): ExportedChange[]`
👍 `setColumnOrder(sheetId: number, newColumnOrder: number[]): ExportedChange[]`
👍 `swapColumnIndexes(sheetId: number, columnMapping: [number, number][]): ExportedChange[]`
👍 `doesCellHaveFormula(cellAddress: SimpleCellAddress): boolean` simpleCellAddress is using sheetId
👍 `doesCellHaveSimpleValue(cellAddress: SimpleCellAddress): boolean` simpleCellAddress is using sheetId
👍 `getCellFormula(cellAddress: SimpleCellAddress): Maybe‹string›` simpleCellAddress is using sheetId
👍 `getCellSerialized(cellAddress: SimpleCellAddress): RawCellContent` simpleCellAddress is using sheetId
👍 `getCellType(cellAddress: SimpleCellAddress): CellType` simpleCellAddress is using sheetId
👍 `getCellValue(cellAddress: SimpleCellAddress): CellValue` simpleCellAddress is using sheetId
👍 `getCellValueDetailedType(cellAddress: SimpleCellAddress): CellValueDetailedType` simpleCellAddress is using sheetId
👍 `getCellValueFormat(cellAddress: SimpleCellAddress): FormatInfo` simpleCellAddress is using sheetId
👍 `getCellValueType(cellAddress: SimpleCellAddress): CellValueType` simpleCellAddress is using sheetId
👍 `isCellEmpty(cellAddress: SimpleCellAddress): boolean` simpleCellAddress is using sheetId
👍 `isCellPartOfMatrix(cellAddress: SimpleCellAddress): boolean` simpleCellAddress is using sheetId
👍 `isItPossibleToMoveCells(sourceLeftCorner: SimpleCellAddress, width: number, height: number, destinationLeftCorner: SimpleCellAddress): boolean` simpleCellAddress is using sheetId
👍 `isItPossibleToSetCellContents(topLeftCornerAddress: SimpleCellAddress, width: number, height: number): boolean` simpleCellAddress is using sheetId
👍 `moveCells(sourceLeftCorner: SimpleCellAddress, width: number, height: number, destinationLeftCorner: SimpleCellAddress): ExportedChange[]` simpleCellAddress is using sheetId
👍 `setCellContents(topLeftCornerAddress: SimpleCellAddress, cellContents: RawCellContent[][] | RawCellContent): ExportedChange[]` simpleCellAddress is using sheetId
👍 `getCellDependents(address: SimpleCellAddress | AbsoluteCellRange): (SimpleCellAddress | AbsoluteCellRange‹›)[]` simpleCellAddress is using sheetId
👍 `getCellPrecedents(address: SimpleCellAddress | AbsoluteCellRange): (SimpleCellAddress | AbsoluteCellRange‹›)[]` simpleCellAddress is using sheetId
👍 `simpleCellAddressFromString(cellAddress: string, sheetId: number): Maybe‹SimpleCellAddress›` simpleCellAddress is using sheetId
👍 `simpleCellAddressToString(cellAddress: SimpleCellAddress, sheetId: number): Maybe‹string›` simpleCellAddress is using sheetId
👍 `copy(sourceLeftCorner: SimpleCellAddress, width: number, height: number): CellValue[][]` simpleCellAddress is using sheetId
👍 `cut(sourceLeftCorner: SimpleCellAddress, width: number, height: number): CellValue[][]` simpleCellAddress is using sheetId
👍 `paste(targetLeftCorner: SimpleCellAddress): ExportedChange[]` simpleCellAddress is using sheetId
👍 `getRangeFormulas(leftCorner: SimpleCellAddress, width: number, height: number): Maybe‹string›[][]` simpleCellAddress is using sheetId
👍 `getRangeSerialized(leftCorner: SimpleCellAddress, width: number, height: number): RawCellContent[][]` simpleCellAddress is using sheetId
👍 `getRangeValues(leftCorner: SimpleCellAddress, width: number, height: number): CellValue[][]` simpleCellAddress is using sheetId

### Those are ok, need to use `sheetName`

👍 `addSheet(sheetName?: undefined | string): string` sheetName is assigned here, sheetId will be created internally
👍 `getSheetId(sheetName: string): Maybe‹number›` you have to provide sheetName to get sheetId 😄 
👍 `isItPossibleToAddSheet(sheetName: string): boolean` we have to check if name is available, sheetId will be generated
👍 `isItPossibleToRenameSheet(sheetId: number, newName: string): boolean` both are needed
👍 `renameSheet(sheetId: number, newName: string): void` both are needed

### Your environment

* HyperFormula version:
* Browser Name and version:
* Operating System:

**Comment by izulin** [comment]
To be closed with #660 ?

**Comment by wojciechczerniak** [comment]
Sure! Done
