### ISSUE TITLE
Matrix error is mentioned twice for `paste` method

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#653]
### Description
Matrix error is mentioned twice

![Screenshot 2021-04-26 at 12 05 44](https://user-images.githubusercontent.com/4718998/116066136-04218200-a688-11eb-8bdb-dff0b09464d4.png)

### Links
https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#paste

### Type of issue

- [ ] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by kirszenbaum** [comment]
Removed the first matrix error
