### ISSUE TITLE
getSheetId fails with an error when called without an argument.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/hyperformula#654]
### Description
`hf.getSheetId` throws the `Cannot read property 'toLowerCase' of undefined`, when called without an argument.
It also fails with `sheetDisplayName.toLowerCase is not a function` if called with a number as an argument.

### Steps to reproduce

1. Call `hf.getSheetId()`...
2. ... or `hf.getSheetId(333)`

### Your environment

* HyperFormula version: latest `develop`

**Comment by izulin** [comment]
It is explicitly stated as a function taking `string` as an argument in the docs.

**Comment by wojciechczerniak** [comment]
In TS, but JS allows undefined args. We may do better here and return `undefined` assuming that such sheet name does not exist. One `if (typeof sheetName === 'string')` WDYT?

**Comment by jansiegel** [comment]
When I look closer and the other functions similar to this I can see there's basically no type validation anywhere, so it's an issue with many of the methods. 
Is this intentional?

**Comment by izulin** [comment]
> When I look closer and the other functions similar to this I can see there's basically no type validation anywhere, so it's an issue with many of the methods.
> Is this intentional?

Yes, in the sense that the code was written with TS-mindset in mind, not with JS-mindset.

**Comment by izulin** [comment]
> In TS, but JS allows undefined args. We may do better here and return `undefined` assuming that such sheet name does not exist. One `if (typeof sheetName === 'string')` WDYT?

To be consistent it would require to add basic typechecking to all the API functions. We can do it, but it's a little bit more of an effort.
