### ISSUE TITLE
Parsing Error for a Valid Excel/Google Sheets Formula

### ISSUE THREAD

**Issue by elucidateadmin** [handsontable/hyperformula#658]
### Steps to reproduce

1. Try evaluating formula expression: =MIN(IF(3.4646197505949>3,20000*(1+0.2),20000*(1-0.2)))
2. Evaluates correctly to 24000 in Google Sheets

### Your environment

Hyperformula version 0.6.0
* HyperFormula version: 0.6.0
* Browser Name and version: Node 15.12.0, Npm 7.6.3
* Operating System: macOS Catalina

**Comment by izulin** [comment]
Could you provide a code snippet? A following code produces `24000`:
```
    const engine = HyperFormula.buildFromArray([['=MIN(IF(3.4646197505949>3,20000*(1+0.2),20000*(1-0.2)))']])
    console.log(engine.getCellValue({row: 0, col: 0, sheet: 0}))
```

**Comment by elucidateadmin** [comment]
Yeah absolutely
``
const options = {
    precisionRounding: 15,
    licenseKey: 'agpl-v3'
};

const hfInstance = HyperFormula.HyperFormula.buildEmpty(options);

hfInstance.addSheet('Sheet1');
let expressionToSolveArray = [["=MIN(IF(3.4646197505949>3,20000*(1+0.2),20000*(1-0.2)))"]]
hfInstance.setSheetContent('Sheet1', expressionToSolveArray);
let calculatedValue = hfInstance.getCellValue({ col: 0, row: 0, sheet: 0 });
``

**Comment by izulin** [comment]
This is something very specific -- this code works for me (even on a clean test env).
@wojciechczerniak any ideas?

**Comment by elucidateadmin** [comment]
@izulin So my code snippet works for you?

**Comment by izulin** [comment]
Yes, produces desired output. Different behaviours could be a result of e.g. contaminated test environment (e.g. mine), that is some extra config options.

What is the parsing error that you are getting?

**Comment by izulin** [comment]
Take a look at this clean sandbox:

[](https://codesandbox.io/s/silent-water-c6uws?file=/src/hyperformulaConfig.js)

**Comment by izulin** [comment]
<img width="1043" alt="Screenshot 2021-04-30 at 00 15 39" src="https://user-images.githubusercontent.com/40573492/116625005-331a4b00-a949-11eb-9169-bd5439f5b325.png">

**Comment by krzysztofspilka** [comment]
Thanks for reporting this @elucidateadmin - I'm closing this issue as it was solved by @izulin - see the CodesandBox demo above.
