### ISSUE TITLE
`vlookupThreshold`

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/hyperformula#701]
@wojciechczerniak: Remove `vlookupThreshold` option which is deprecated by `binarySearchThreshold`. We should not ship major version with already deprecated stuff.

**Comment by kirszenbaum** [comment]
Seem like it's already been done: I can't find any reference to the `vlookupThreshold` option, except for the change log (where it says it's been deprecated), and the `binarySearchThreshold` option is mentioned [here](https://handsontable.github.io/hyperformula/guide/performance.html#vlookup-match)

**Comment by wojciechczerniak** [comment]
Already done in v0.5.0: https://github.com/handsontable/hyperformula/releases/tag/0.5.0
