### ISSUE TITLE
TODAY and NOW formulas return wrong value

### ISSUE THREAD

**Issue by SofyaNovikava** [handsontable/hyperformula#709]
Hello,

### Description
I am using TODAY and NOW formulas to get a current date but getting a date with a wrong day instead

I've checked coding and found out that these formulas return 
{
    **day: now.getDay()**
}

instead of 
{
    **day: now.getDate()**
}

These leads to getting a week day number instead of a real date

### Steps to reproduce
1. Set **=today()** value to A1 cell
2. Set **=day(a1)** value A2 cell
3. Check A2 value which is incorrect

### Demo
https://codesandbox.io/s/affectionate-banzai-zn7m1

* HyperFormula version: 0.6.2
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by izulin** [comment]
should work now on `develop` branch, thanks for spotting this

**Comment by wojciechczerniak** [comment]
Fixed in #710
