### ISSUE TITLE
HyperFormula with GPU.js will not compile on Mac with Node 16

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#717]
### Description

Tracked to: https://github.com/stackgl/headless-gl/pull/215 We're blocked by the dependency. Nothing to do for us here.

### Steps to reproduce

1. Install Node.js 16+ on Mac
2. Run `npm install`

### Your environment

* HyperFormula version: develop
* Browser Name and version: node.js
* Operating System: macOS Catalina 10.15.7

### Links
https://github.com/stackgl/headless-gl/pull/215

**Comment by dancollager** [comment]
Same problem but in windows 10
![image](https://user-images.githubusercontent.com/25945352/123014468-efaded00-d38b-11eb-9ae7-8cfeb871651d.png)

**Comment by wojciechczerniak** [comment]
@dancollager Your issue may be somewhere else. The types compiler is missing should be build in. Check if your `tsconfig.json` is configured with correct `lib` for web

**Comment by wojciechczerniak** [comment]
This problem was fixed upstream in version v4.9.2 https://github.com/stackgl/headless-gl/pull/215#issuecomment-913055016
