### ISSUE TITLE
Create new page explaining Arrays in HF

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/hyperformula#740]
Input: https://docs.google.com/document/d/1pR-wSoOmlL6OIMuL9E6qRKLc-BPvcazdXK8jctI8OwQ

**Comment by kirszenbaum** [comment]
First draft ready: /hyperformula/guide/arrays.html#about-arrays-in-hyperformula

**Comment by wojciechczerniak** [comment]
Can be read here: https://github.com/handsontable/hyperformula/blob/04f09239c9789ae74a32b0cd077dbdcf1fdd79c0/docs/guide/arrays.md
