### ISSUE TITLE
chooseAddressMappingPolicy configurations not exported from hyperformula

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#742]
### Description

https://handsontable.github.io/hyperformula/api/classes/config.html#chooseaddressmappingpolicy

The config requires actual classes to be passed to this property such as 'AlwaysSparse' class however `ChooseAddressMapping` is not exported

### Steps to reproduce

// Not possible due to no export on AlwaysSparse
```js
  const hyperformula = HyperFormula.buildEmpty({
    licenseKey: hyperformulaLicenseKey,
    chooseAddressMappingPolicy: AlwaysSparse,
  });
```

Also, a quick question on this. Why does HF use sparse arrays instead of object key values for quick lookups of values instead of all this sparse, dense stuff?

I presume it's some type of performance over using objects but I'd just like to know why so I can understand more behind it.

**Comment by izulin** [comment]
> Also, a quick question on this. Why does HF use sparse arrays instead of object key values for quick lookups of values instead of all this sparse, dense stuff?

The sparse arrays we are using are actually `Map()`.
I **believe** this is a matter of flavour whether one uses `{}` or `Map()` for sparse array, as underlying imlementation should be the same and its a matter of syntax differences.
