### ISSUE TITLE
Add sorting support info, number of supported functions, remove triple licensing info at the Introduction page at

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/hyperformula#744]
https://handsontable.github.io/hyperformula/

**Comment by wojciechczerniak** [comment]
Hint: We've got variable for functions count that is updated with each release. See https://github.com/handsontable/hyperformula/blob/master/docs/guide/built-in-functions.md how to use it

**Comment by kirszenbaum** [comment]
- [x] Remove triple licensing info (done in #700 )
- [x] Add number of supported functions
- [x] Add sorting support info
