### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/hyperformula#746]
New example and rewrite the https://handsontable.github.io/hyperformula/guide/sorting-data.html as we have a new API now

**Comment by kirszenbaum** [comment]
@wojciechczerniak - the [topic](https://github.com/handsontable/hyperformula/pull/759) was merged, but there's still the [demo](https://github.com/handsontable/hyperformula/blob/develop/docs/guide/sorting-data.md#data-sorting-demo) to [update](https://github.com/handsontable/hyperformula/pull/759#issue-685978400) - currently it showcases `moveRows()`

**Comment by wojciechczerniak** [comment]
Cool! We have to ask @jansiegel for help with the demo

**Comment by jansiegel** [comment]
@kirszenbaum @wojciechczerniak 
I did a little rewrite of the sorting demo on [hyperformula-demos](https://github.com/handsontable/hyperformula-demos): https://github.com/handsontable/hyperformula-demos/compare/0.6.x...1.0.x

I published it on the `1.0.x` branch along with bumping the HF version to `1.0.x` in the demos' dependencies, so for obvious reasons, it will not work out-of-the-box just yet.

**Comment by kirszenbaum** [comment]
Thanks @jansiegel ! @wojciechczerniak I updated the demo version: https://github.com/handsontable/hyperformula/pull/764
