### ISSUE TITLE
Formula Editor

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/hyperformula#75]
### Description

⚠️ WIP

Editor with syntax highlighting. Can use #2 for providing more details for the end user.

### Features

Reference cells via click during formula editing
Visible traceability of cells within a formula
Formula auto-complete
See a cell’s underlying formula without having to click into it (formula bar)

### Links:
https://sap.github.io/chevrotain/docs/guide/syntactic_content_assist.html#introduction

**Comment by wojciechczerniak** [comment]
Just cleaning up. Formula Editor is a UI component. It doesn't belong here. Will be created separately, outside of the HF repo.

Ref: https://github.com/handsontable/handsontable/issues/6466

**Comment by BrianHung** [comment]
@marek-baranowski Hi, would it be possible to share the autocomplete code? I'm about to also use codemirror 6 for a hyperformula cell editor with autocomplete support.

**Comment by scrapeable** [comment]
Does this feature exist?

**Comment by sequba** [comment]
Hi, @scrapeable!

As @wojciechczerniak said:
> Formula Editor is a UI component. It doesn't belong here.

HyperFormula is a headless library without a GUI. It's the responsibility of the UI app to provide a way for the end user to enter formulas.
