### ISSUE TITLE
destroy(), unregisterFunctionPlugin, unregisterAllFunctions not removing custom plugins

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#775]
### Description

The above functions should all remove hyperformula instance registered custom plugins.

### Steps to reproduce

```js
// Register the custom function plugin
HyperFormula.registerFunctionPlugin(CountHF, countHFTranslations);

// Create an empty HyperFormula instance.
const hf = HyperFormula.buildEmpty({
  licenseKey: "gpl-v3"
});

console.log(hf.getAllFunctionPlugins());

HyperFormula.unregisterFunctionPlugin(CountHF);
HyperFormula.unregisterAllFunctions();
hf.destroy();

console.log(hf.getAllFunctionPlugins());
```

![image](https://user-images.githubusercontent.com/15030491/126138786-b857af1a-55ff-4b91-adcf-e433d83ef1bb.png)

### Demo

https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/0.6.x/vanillajs-demo?from-embed=&file=/src/hyperformulaConfig.js

### Your environment

* HyperFormula version: Sandbox
* Browser Name and version: Chrome latest
* Operating System: Windows 10

I ran into this issue when testing this PR: https://github.com/handsontable/hyperformula/pull/766

Thanks.

**Comment by wojciechczerniak** [comment]
Calling method on an instance that is destroyed should not be possible:

```ts
hf.destroy();

console.log(hf.getAllFunctionPlugins());
```
So this is a bug IMO.

The second part with 

```ts
HyperFormula.registerFunctionPlugin(CountHF, countHFTranslations);

HyperFormula.unregisterFunctionPlugin(CountHF);
```

we will have to investigate. AFAIK plugin should be removed globally 🤔  Thanks for reporting.

**Comment by izulin** [comment]
> The second part with
> 
> ```ts
> HyperFormula.registerFunctionPlugin(CountHF, countHFTranslations);
> 
> HyperFormula.unregisterFunctionPlugin(CountHF);
> ```
> 
> we will have to investigate. AFAIK plugin should be removed globally 🤔 Thanks for reporting.

AFAIR it's not a bug. Look at this code:

```
    HyperFormula.unregisterAllFunctions()
    HyperFormula.registerFunctionPlugin(FooPlugin)
    const engine = HyperFormula.buildEmpty()
    HyperFormula.unregisterFunctionPlugin(FooPlugin)
    console.log(engine.getAllFunctionPlugins())
```

`engine` was created when registered statically plugins contained `FooPlugin`. Removing it `statically` did not affect after `engine` was created. So the output is `[FooPlugin]`.

Do you see a way around it? For me it's working as designed.

**Comment by wojciechczerniak** [comment]
Done in #788
