### ISSUE TITLE
Removing named expressions after destroying hyperformula throws a -1 sheet id error

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#776]
### Description

`destroy` should remove the named expressions and/or `isItPossibleToRemoveNamedExpression` after destroying should not return true.

### Steps to reproduce

```js

// Register the custom function plugin
HyperFormula.registerFunctionPlugin(CountHF, countHFTranslations);

// Create an empty HyperFormula instance.
const hf = HyperFormula.buildEmpty({
  licenseKey: "gpl-v3"
});

hf.addNamedExpression("TRUE", "=TRUE()");
hf.addNamedExpression("FALSE", "=FALSE()");

hf.destroy();

if (hf.isItPossibleToRemoveNamedExpression("TRUE")) {
  console.log(hf.listNamedExpressions());
  hf.removeNamedExpression("TRUE");
  console.log(hf.listNamedExpressions());
}
```
throws: Error: There's no sheet with id = -1

### Demo

https://codesandbox.io/s/cocky-edison-jpt31?file=/src/hyperformulaConfig.js

### Your environment

* HyperFormula version: sandbox
* Browser Name and version: chrome latest
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
Done in #788
