### ISSUE TITLE
Docs: add a more advanced custom function tutorial

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/hyperformula#779]
### Description
As discussed [here](https://github.com/handsontable/hyperformula/discussions/778#discussioncomment-1037447), we should add a more advanced guide on implementng custom functions.

### Links
https://handsontable.github.io/hyperformula/guide/custom-functions.html#implementing-your-custom-function
https://github.com/handsontable/hyperformula/issues/968
#1090

### Type of issue
- [ ] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [x] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by warpech** [comment]
The goal here is to show in the docs how to make a function that:

- accepts arguments (one of which might be a range, expression, etc)
- is comprehensive (is protected from edge cases, does not blow up by being too naive)
- is testable (there is an example of a unit test)

**Comment by sequba** [comment]
Turns out, our current guide contains bugs which cause problems when trying to implement a custom function tha takes arguments: #1090

**Comment by sequba** [comment]
We've decided to make this guide as comprehensive as possible and request the review from external consulting company.

**Comment by sequba** [comment]
Released with [HyperFormula 2.3.0](https://github.com/handsontable/hyperformula/releases/tag/2.3.0).
