### ISSUE TITLE
Vlookup approximate lookup not working

### ISSUE THREAD

**Issue by maadws** [handsontable/hyperformula#787]
### Description

When vloopup last argument is true it still searches for exact results while in excel it searched for approximate results

### Steps to reproduce

1. add a lookup table with first column all numbers in sorted order
2. add vlookup and search for a number inbetween
3. no results
check [demo](https://codesandbox.io/s/competent-jackson-490o7?file=/src/data.js)

### Demo
https://codesandbox.io/s/competent-jackson-490o7?file=/src/hyperformulaConfig.js

### Your environment
node10.15.3/chrome 92.0.4515.107(64bit)

* HyperFormula version: 1.0.0
* Browser Name and version: chrome 92.0.4515.107(64bit)
* Operating System :windows 10

**Comment by maadws** [comment]
The problem is related to [this line](https://github.com/handsontable/hyperformula/blob/413e199a632452bffb45f33c747b53a6f8af2cab/src/Lookup/RowSearchStrategy.ts#L30) it seems if binary search is used it forces exact matching. to work around it for now I made binarySearchThreshold = 1 in my config

**Comment by wojciechczerniak** [comment]
Done in #791
