### ISSUE TITLE
Webworker with HF

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#793]
I want to pass my Hypeformula instance from a webworker. When doing so via `postmessage` :

```
 const excel = HyperFormula.buildEmpty(options as any);
 // ...load data
 postMessage(excel); // fails
```

I get the error:

`Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope':Failed to execute 'postMessage' on 'ServiceWorker': function could not be cloned` 

I tried to stringify+parse but then I loose the functions such as `getCellValue`.
```
  const getCircularReplacer = () => {
        const seen = new WeakSet();
        return (key, value) => {
          if (typeof value === "object" && value !== null) {
            if (seen.has(value)) {
              return;
            }
            seen.add(value);
          }
          return value;
        };
      };
      var obj = JSON.parse(JSON.stringify(excel, getCircularReplacer()));
      postMessage(obj); // passes not the whole instance
```

What can I do?

**Comment by wojciechczerniak** [comment]
You can't. `postMessage` can send primitive JS values only or with new API `postMessage(message, [ TransferableObject ])`[1] transferable objects:  ArrayBuffer, MessagePort, ImageBitmap and OffscreenCanvas [2].

I would try something like Google Comlink[3] to wrap the WebWorker Handsontable in Proxy creating an RPC interface. HF would be run on a thread while `postMessage` should transfer results only. Not tested.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage
[2] https://developer.mozilla.org/en-US/docs/Web/API/Transferable
[3] https://github.com/GoogleChromeLabs/comlink

**Comment by doczoidberg** [comment]
as far as I understand Comlink ist based on webworkers. I don't see why I should transfer complex objects with functions with that?

I only need to post the HF instance once from the webworker and not back to it. IS this maybe possible with the ArrayBuffer?

**Comment by wojciechczerniak** [comment]
Comlink does not transfer objects with functions. You can't do that in JavaScript. 

HF is not an ArrayBuffer so this won't help either. You may stringify HF and initialize it again on the main thread, but I doubt it's what you're looking for.

**Comment by doczoidberg** [comment]
so what you suggest that I keep my HF instances in the worker and build my own interface for getting and setting data from and to the HF instance(s) in the webworker?

**Comment by wojciechczerniak** [comment]
Yes. That's what I would do. Unfortunately, I can't give you a solid solution, as this is an untested idea.

**Comment by krzysztofspilka** [comment]
I'll close this for now.

**Comment by doczoidberg** [comment]
thanks. It works for now

**Comment by MartinDawson** [comment]
Web workers should probably be in hyperformula by default in the future for all computations I think and not in users app's.

As users will never want a blocked UI or backend from hyperformula calculations.
