### ISSUE TITLE
Docs: update the GPU page

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/hyperformula#796]
Update this page: https://handsontable.github.io/hyperformula/guide/enabling-gpu-acceleration.html

- Remove the full stop in the title
- Make sure it's up to date with the GPU config changes introduced in HF 1.0.0
- If the GPU acceleration is "not bundled with the engine", why does it have "to be passed to the engine configuration"?

**Comment by warpech** [comment]
Closing as not relevant anymore. GPU support was deprecated in 1.2.0 and removed in 2.0.0

- https://github.com/handsontable/hyperformula/releases/tag/1.2.0
- https://github.com/handsontable/hyperformula/releases/tag/2.0.0
