### ISSUE TITLE
Can'f find variable Intl

### ISSUE THREAD

**Issue by vincentgheza** [handsontable/hyperformula#801]
### Description

Hello, first of all thank you for your work.

I am using react-native 0.59 to generate a mobile app for android and ios.

For ios the installation and its use is impeccable.

However on android I have the following problem. => Can'f find variable Intl (possible rejection)

What information can I provide to you so that you can help me solve the problem?

Sorry i don't speak realy fine in english.

* HyperFormula version: 1.0.0
* Browser Name and version: react-native 0.59
* Operating System: android

**Comment by wojciechczerniak** [comment]
Hi, thanks for your kind words. Unfortunately, we haven't tested HF in react-native yet. 

INTL is one of JavaScript APIs that we're using. Most of current browsers have support already, node.js from v14+. I'm not sure where Android is with those. There are some polyfills tho

**Comment by vincentgheza** [comment]
ok no problem, if i find the polyfills can working with my android version , i will back give more info.

**Comment by vincentgheza** [comment]
Hello, i found the polyfill, so i give the url : https://github.com/react-native-community/jsc-android-buildscripts

And it's important to use International variant implementation => implementation "org.webkit:android-jsc-intl:+"

If you use react-native 0.59.10
