### ISSUE TITLE
Best way to read a file and import it into HF?

### ISSUE THREAD

**Issue by mmahalwy** [handsontable/hyperformula#803]
### Description

What's the best way to read a file and import it into HF?

### Links

Should be here: https://handsontable.github.io/hyperformula/guide/advanced-usage.html#demo

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [x] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by AMBudnik** [comment]
Hi @mmahalwy 

HyperFormula works on an array of arrays.

![image](https://user-images.githubusercontent.com/10757813/130796586-716e6db0-9503-4080-86cd-69d6ff8de84a.png)
ref: https://handsontable.github.io/hyperformula/guide/basic-usage.html 

So if you would like to pass JSON, you need to parse it and build an array out of the data first. Using variables is permitted, so once you import any function you can use it on a regular basis (replace the `data` in the screenshot above).

Ps. your data can be of different types https://handsontable.github.io/hyperformula/guide/types-of-values.html#getting-cell-type 

If I got your question wrong or missed anything, feel free to let me know.

**Comment by AMBudnik** [comment]
We do not have this kind of functionality yet. But I also think that it would be a useful feature. 
I will move this idea to `discussions` so other developers can also share their ideas and concepts.
