### ISSUE TITLE
Improve redirection in former handsontable/formula.js repo

### ISSUE THREAD

**Issue by nicolashefti** [handsontable/hyperformula#806]
### Description

I am Nicolas, maintainer of [@formulajs/formulajs](https://www.npmjs.com/package/@formulajs/formulajs).

Your former package is still heavily used [@handsontable/formulajs](https://www.npmjs.com/package/@handsontable/formulajs). In addition to the current statement about HypeFormula, I think this would be great to inform the developers that there is a continuity of development for Formula.js.

### Links

Documentation page to improve: https://github.com/handsontable/formula.js
An example: https://github.com/sutoiku/formula.js

### Type of issue

Other issues, suggestions, or ideas

**Comment by krzysztofspilka** [comment]
Hi @nicolashefti, thanks for bringing this up.

First off, good job on maintaining https://github.com/formulajs/formulajs. We know how hard the formulas can be:)

As for your improvement suggestion for the notification in our fork of the Sutoiku project - if you don't mind we'd rather keep it our way. Originally, we created the fork solely for `hot-formula-parser` needs, which was a part of Handsontable's plugin. Thus, we've always considered it an internal project, not a general-purpose solution.

Also, we've put a lot of time and effort to create HyperFormula, and we'd like to encourage developers to give it a try.

I believe that the disclaimer at https://github.com/sutoiku/formula.js is sufficient for most users to recognize your work at https://github.com/formulajs/formulajs as a continuity of the project.
