### ISSUE TITLE
SUMPRODUCT with +3 arrays results with N/A

### ISSUE THREAD

**Issue by bjorngrundtalf** [handsontable/hyperformula#810]
I'm using handsontable with hyperformula to recreate an economic model in web interface. While recreating the calculations I realised that SUMPRODUCT supports only two arrays as inputs when documentation shows  this example:

SUMPRODUCT(Array1; Array2...Array30)

Each time when I try to input different amount of arrays than two I receive 'N/A' as an output. Is there any trick to make it work with more arrays?

**Comment by AMBudnik** [comment]
Thank you for posting the issue report here @bjorngrundtalf 

You are right, at the moment [we only support a 2-argument formula](https://github.com/handsontable/hyperformula/blob/35e526fad11bbf3fd1e83613492ff15352737a30/test/interpreter/function-sumproduct.spec.ts#L7) (`=SUMPRODUCT(array1, array2)`) while the actual formula has syntax as this `=SUMPRODUCT(array1, [array2,….. array_n])`

That should be altered. I will keep you updated on the subject as soon as we make the necessary changes.

**Comment by wojciechczerniak** [comment]
Done in #826
