### ISSUE TITLE
Remove gpu.js from the project

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/hyperformula#812]
It turned out that the gpu.js slows down the `npm i` of Handsontable. The problem lies in the dependency of HyperFormula that creates the WebGL context in Node.js (see [gl](https://www.npmjs.com/package/gl)). As there is no easy workaround for this problem, I recommend removing gpu.js from the source code, documentation, marketing materials, README; and all other mentions of GPU usage inside of HyperFormula.

GPU.js was a successful experiment to speed up the calculation time of some functions (MMULT, MAXPOOL, MEDIANPOOL, and TRANSPOSE) used within big data sets. It will be left in [version 1.0.0](https://github.com/handsontable/hyperformula/releases/tag/1.1.0) for all users who still need the GPU acceleration in their projects.

Handsontable 9.0.2 / HyperFormula 1.1.0

**Comment by krzysztofspilka** [comment]
Update: the removal will be done in the next `major` version

**Comment by AMBudnik** [comment]
Changed added to [HyperFormula v2.0.0](https://github.com/handsontable/hyperformula/issues/964) released today. I'm closing this issue as solved.
