### ISSUE TITLE
Incorrect calculation result when using MIN and MAX functions in the same cell range continuously

### ISSUE THREAD

**Issue by taknb2nch** [handsontable/hyperformula#827]
### Description
I'm using Handsontable 9.0.2 (with Hyper formula 0.6.2)

I use the MIN function and the MAX function continuously in the same cell range, I can not get the correct calculation result.

I check source code below,
https://github.com/handsontable/hyperformula/blob/43071aa2a822ddcea04a7b1016fa3e8dda78e751/src/interpreter/plugin/NumericAggregationPlugin.ts#L438
since the same cache key is used for MIN and MAX, it seems that the calculation result is overwritten.

This is fixed in master.

If you do not plan to upgrade the version of hyperformula used in handsontable to v1 (or higher), we would appreciate it if you could fix it.

### Steps to reproduce

1. set value 1 to 5 in A1 to A5
2. calculate MIN(A1:A5) -> 1
3. calculate MAX(A1:A5) -> 1

### Your environment
* HyperFormula version: 0.6.2 ( in Handsontable 9.0.2 )
* Browser Name and version: Chrome
* Operating System: Windows10

**Comment by krzysztofspilka** [comment]
@taknb2nch thanks for reporting this. It should be fixed in Handsontable 10, released last week. Can you update your copy of Handsontable and let me know if it helped?

**Comment by AMBudnik** [comment]
Hi @taknb2nch 

Here https://github.com/handsontable/handsontable/issues/8104 is the corresponding issue fixed for Handsontable v10.

If you would have any further questions or concerns please contact me at support@handsontable.com 
I'll be happy to guide you through all of the[ changes that we made in v10](https://handsontable.com/docs/migration-from-9.0-to-10.0/).
