### ISSUE TITLE
Add support for reversed ranges (previously: "...and multiple range references of cells")

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/hyperformula#834]
### Discussed in https://github.com/handsontable/hyperformula/discussions/832

<sup>Originally posted by **AMBudnik** October  6, 2021</sup>
As discussed [here](https://forum.handsontable.com/t/error-when-using-a-reversible-range/5570) we should consider adding support for **reversed ranges** of cells and support **multiple range references** to match the standard of OpenFormula.

**Examples**
1. Reversed ranges - `=SUM(A10:A1)` should be equal to `=SUM(A1:A10)`
2. Multiple range references - `=SUM(B4:B5:C5)` should be equal to `=SUM(B4:C5)`

**Comment by warpech** [comment]
We decided today that point 1 from the OP will be done in scope of this issue and point 2 from the OP will be extracted into a separate issue, for the future.

**Comment by AMBudnik** [comment]
Thank you for adding this functionality @sequba 
I updated the Client who requested this functionality.
