### ISSUE TITLE
runFunction docs are wrong

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#842]
Link: https://handsontable.github.io/hyperformula/guide/custom-functions.html#implementing-your-custom-function

```
    return this.runFunction(() => 'Hyperformula'.length)
```
This doesn't work and throws an error because `runFunction` needs 3 params before it according to typescript:

https://codesandbox.io/s/elated-kepler-tetng?file=/src/countHFFunctionPlugin.js

**Comment by wojciechczerniak** [comment]
Done in #848
