### ISSUE TITLE
Can I add a number of days to a date using built in functions?

### ISSUE THREAD

**Issue by mike13927** [handsontable/hyperformula#844]
### I want to shift a date by a number of days

 Example DATEADD(A1, 20)  where A1 is a date and '20' is the number of days

I see the built in function ESHIFT adds a number of months and returns a date, but I need to add days to the date

**Comment by wojciechczerniak** [comment]
`=TEXT(B1, 'MM/DD/YY')` has wrong syntax. Text values should be surrounded with double quotes.
Either `'=TEXT(B1, "MM/DD/YY")'` or escaped `"=TEXT(B1, \"MM/DD/YY\")"`
