### ISSUE TITLE
addRows does not return the updated cells

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#845]
Example: https://codesandbox.io/s/nice-gagarin-05yc0?file=/src/hyperformulaConfig.js

Have a sheet with some formulas in it.

Do the following:
```
const changes = hf.addRows(0, [0, 1]);

console.log(changes);
```

changes is always an empty array. It should have returned the the cells whos formulas were updated due to the `addRows` calculation.

**Comment by wojciechczerniak** [comment]
AFAIK `changes` do not include updated formulas, only calculated values. Since HF will shift relative formula references, they will reference same values and the calculation results will not change.

IMO this is not a bug

**Comment by IMSupperkaka** [comment]
I want to get the changes of formula cells to update original data, how can i did this.

**Comment by sequba** [comment]
Hi @IMSupperkaka, thanks for reaching out to us. I am sorry you experienced an issue with HyperFormula but to answer your question we need more detail. Please describe it more thoroughly and include a code example.

**Comment by IMSupperkaka** [comment]
> https://codesandbox.io/s/nice-gagarin-05yc0?file=/src/hyperformulaConfig.js

Same sample as @MartinDawson 
Example: https://codesandbox.io/s/nice-gagarin-05yc0?file=/src/hyperformulaConfig.js

**Comment by IMSupperkaka** [comment]
I just want the changes of formula cells when i do some operation like addRows, how can i get the changes if addRows method not return.

**Comment by wojciechczerniak** [comment]
From the array perspective if you add or remove row on position N, all rows from that position will be changed up to the end of this array length. If you move row it depends, may be either from source or destination position to the end, depending if the move is down or up. All the rows will be shifted. Therefore, every single cell by coordinates will change value/formula. 

It does not make sense to return half or all (in edge case where row was added to the beginning) the data each time. 

```ts
const allChanges = hfInstance.getAllSheetsSerialized().slice(addedRowPosition);
const formulaChanges = hfInstance.getAllSheetsFormulas().slice(addedRowPosition);

// then find non-null values and sync them to your data store
```

**Comment by IMSupperkaka** [comment]
> 

We use HyperFormula to enhance the spreadsheet, i need to update the origin data at backend when client side do addRows addColumns operations

```javascript
const data = [[]]; // origin data

sheet.formulaInstance = HyperFormula.buildFromArray(data, options);

sheet.on('apply', (op) => {
  switch(op.type) {
    case 'insert-row': 
        sheet.formulaInstance.addRows(0, [op.at, op.amount]);
        // I want to update the origin data here
    break;
  }
})
```

**Comment by IMSupperkaka** [comment]
> From the array perspective if you add or remove row on position N, all rows from that position will be changed up to the end of this array length. If you move row it depends, may be either from source or destination position to the end, depending if the move is down or up. All the rows will be shifted. Therefore, every single cell by coordinates will have value/formula changed.
> 
> It does not make sense to return half or all (in edge case where row was added to the beginning) the data each time.
> 
> ```ts
> const allChanges = hfInstance.getAllSheetsSerialized().slice(addedRowPosition);
> const formulaChanges = hfInstance.getAllSheetsFormulas().slice(addedRowPosition);
> 
> // then find non-null values and sync them to your data store
> ```

This is the way how i did now, but i dont kdonw if there have performance problem when data is huge.


> From the array perspective if you add or remove row on position N, all rows from that position will be changed up to the end of this array length. If you move row it depends, may be either from source or destination position to the end, depending if the move is down or up. All the rows will be shifted. Therefore, every single cell by coordinates will have value/formula changed.
> 
> It does not make sense to return half or all (in edge case where row was added to the beginning) the data each time.
> 
> ```ts
> const allChanges = hfInstance.getAllSheetsSerialized().slice(addedRowPosition);
> const formulaChanges = hfInstance.getAllSheetsFormulas().slice(addedRowPosition);
> 
> // then find non-null values and sync them to your data store
> ```

This is the way how i did now, but i dont kdonw if there have performance problem when data is huge. case i need to serialized again.

**Comment by IMSupperkaka** [comment]
> From the array perspective if you add or remove row on position N, all rows from that position will be changed up to the end of this array length. If you move row it depends, may be either from source or destination position to the end, depending if the move is down or up. All the rows will be shifted. Therefore, every single cell by coordinates will have value/formula changed.
> 
> It does not make sense to return half or all (in edge case where row was added to the beginning) the data each time.
> 
> ```ts
> const allChanges = hfInstance.getAllSheetsSerialized().slice(addedRowPosition);
> const formulaChanges = hfInstance.getAllSheetsFormulas().slice(addedRowPosition);
> 
> // then find non-null values and sync them to your data store
> ```

This is the way how i did now, but i dont kdonw if there have performance problem when data is huge. case i need to serialized again.

**Comment by sequba** [comment]
Looking at your code snippet, it seems that your `data` array contains basically the serialized sheet, so as @wojciechczerniak wrote, 
> if you add or remove row on position N, all rows from that position will be changed up to the end of this array length.

Well, the easiest thing to do would be to just:
```js
data = sheet.formulaInstance.getSheetSerialized(sheetId);
```

If you don't want to copy the whole array, there is no other option than to update all the formulas in rows from `op.at+op.amount` to the end of the array:
```js
sheet.on('apply', (op) => {
  switch(op.type) {
    case 'insert-row': 
        sheet.formulaInstance.addRows(0, [op.at, op.amount]);
        const newRows = Array(op.amount).fill().map(() => [])        
        data.splice(op.at, 0, ...newRows);
        const dataToBeChanged = data.slice(op.at+op.amount);
        // update all formulas contained in dataToBeChanged
    break;
  }
})
```

I didn't test this snippet so it might not work out of the box. It demonstrates the idea though.

**Comment by IMSupperkaka** [comment]
> 

It seems to work for me, thank you for answer.

**Comment by sequba** [comment]
No problem, I hope it will help to solve your problem ;)

**Comment by BrianHung** [comment]
@sequba 

> If you don't want to copy the whole array, you might omit indexes from 0 to op.at:

This works for `addRows` but for stuff like `removeRows` and `moveRows` (and their column counterparts), I would find it hard to optimize from user-land syncing the serialized sheet back to `data`.

Is there a chance `formulasUpdated` can be added, mentioned in https://github.com/handsontable/hyperformula/issues/135

**Comment by sequba** [comment]
We created an [issue to implement `formulasUpdated` hook](https://github.com/handsontable/hyperformula/issues/1156).
