### ISSUE TITLE
SPLIT function implementation does not match docs

### ISSUE THREAD

**Issue by andyvanee** [handsontable/hyperformula#857]
### Description

The documentation for the SPLIT function matches Google Sheets' documentation, but the current implementation and spec do not reflect this.

Function List: <https://handsontable.github.io/hyperformula/guide/built-in-functions.html#list-of-available-functions>

Google Documentation: <https://support.google.com/docs/answer/3094136>

Spec: <https://github.com/handsontable/hyperformula/blob/35e526fad11bbf3fd1e83613492ff15352737a30/test/interpreter/function-split.spec.ts>

The method signature SHOULD be: `SPLIT(text, delimiter, [split_by_each], [remove_empty_text])`

The actual method signature seems to be: `SPLIT(text, count)`

### Steps to reproduce

In a Google Spreadsheet, you can verify that `=SPLIT("Some,Text,Here", ",")` returns an array result `[["Some", "Text", "Here"]]`.

**Comment by wojciechczerniak** [comment]
Interesting finding 🤔 Thank you for reporting

I've tracked earliest implementation to https://github.com/handsontable/hyperformula/commit/2976094255fe094c9a093735559a7062d9822ca9, that's B+R phase era. I don't remember where the spec was taken from. Excel does not have SPLIT function, neither does [OpenDocument OpenFormula spec](https://docs.oasis-open.org/office/OpenDocument/v1.3/csprd02/part4-formula/OpenDocument-v1.3-csprd02-part4-formula.html) and it's not in [Open Office Calc Guide](https://wiki.openoffice.org/w/images/b/b3/0300CS3-CalcGuide.pdf) that Google Sheets documentation is referring to.

It was on the list for our B+R phase #13, and I've found Appendix 5, but there's nothing more. Just a list of names.

It's not an implementation of `formula.js`, as it was closer to GS one: https://github.com/handsontable/formula.js/blob/98a52fd6aca2326e0a035facbe01ef015955b539/lib/text.js#L243-L245

I guess the best way would be to adjust SPLIT function to GS implementation then? @bardek8 you remember something ( why/how) about SPLIT function?

**Comment by andyvanee** [comment]
Very interesting! It's one of those functions I really miss when I'm using something other than Google Sheets.

I have done a rough first pass just to get it working for how I'm using it. It would need a fair bit more testing to make it match the spec (the RegExp split is particularly hacky).

```javascript
    split(ast, state) {
        const metadata = this.metadata("SPLIT")
        const callback = (str, sep, split_each = true, remove_empty = true) => {
            const cells = this.doSplit(str, sep, split_each, remove_empty)
            return SimpleRangeValue.onlyValues(cells)
        }
        return this.runFunction(ast.args, state, metadata, callback)
    }

    splitSize(ast, state) {
        const metadata = this.metadata("SPLIT")
        const callback = (str, sep, split_each = true, remove_empty = true) => {
            return this.doSplit(str, sep, split_each, remove_empty)
        }
        const cells = this.runFunction(ast.args, state, metadata, callback)

        if (cells instanceof CellError) return cells
        return ArraySize.fromArray(cells)
    }

    doSplit(str, sep, split_each, remove_empty) {
        split_each = split_each ? true : false
        remove_empty = remove_empty ? true : false
        let parts = `${str}`.split(sep)
        if (split_each) {
            const re = new RegExp(`[${sep}]`)
            parts = str.split(re)
        }
        if (remove_empty) {
            parts = parts.map(v => v.trim())
            parts = parts.filter(v => v)
        }
        return [parts]
    }
```

Just for reference - I tend to use it as a way to translate a single cell into a list of values, so the `formula.js` implementation would work just fine for me. I usually don't need the last two arguments.

![Screen Shot 2021-11-18 at 11 16 04 AM](https://user-images.githubusercontent.com/212280/142473586-a0ed366f-7808-4892-af34-49dda9dde1b8.png)
.

**Comment by andyvanee** [comment]
So, I said it needs more testing, and I've already found a bug:) My example code throws an error if the split size is zero, so I've added this before the `doSplit` return `if (!parts.length) return [[""]]`

**Comment by bardek8** [comment]
> I guess the best way would be to adjust SPLIT function to GS implementation then? @bardek8 you remember something ( why/how) about SPLIT function?

The issue with `SPLIT` function is that we don't know size of its output - it can occupy many cells and we don't know how many before evaluation. This makes things more difficult for the engine, as the dependency graph changes depending on the values and in the current implementation we cannot handle that.
That's why right now we return only the `count`-th element of the split input. 

Of course we could extend the function to handle different delimiters, but I'm afraid we won't be able to support the full GS functionality right now.

**Comment by andyvanee** [comment]
I'm not sure I totally understand how this is different than the `FILTER` function, for example, which changes it's output dimensions based on it's input. At the same time, I don't understand a lot of what's going on under the hood and I'm sure there are tons of bugs hiding in my code, so I can appreciate that it may not be worth the effort to implement the full GS functionality. 

For now I've "pre-split" the values and I'm pulling them in using `ARRAYFORMULA`. Thanks for looking into it!

**Comment by bardek8** [comment]
Good point, indeed `FILTER` function also doesn't know the exact size of output. However, here we have an upper bound on the size of output - it cannot be larger than the array that is filtered.
But in the `SPLIT` function we can have arbitrarily big output which makes things difficult to create the graph of dependencies between cells.

I'm glad that you found a workaround!

**Comment by sequba** [comment]
Related: https://github.com/handsontable/hyperformula/issues/1253
