### ISSUE TITLE
Slow graph building with 500k of rows without formulas

### ISSUE THREAD

**Issue by crystalstone** [handsontable/hyperformula#876]
hi，
we use handsonetable + hyperformula to develop sheet like excel. But we find when setSheetContent or buildfromsheets with huge datas may has bad performance.

demo:
setSheetContent 50w rows data (do not has any formula) will cost 50s
https://jsfiddle.net/rdfa45vp/21/

but spreadjs just cost 2~3s

**Comment by AMBudnik** [comment]
Hi @crystalstone 

Could you please check the tips on the performance that I've just posted at https://github.com/handsontable/hyperformula/discussions/871
I hope they will help.

**Comment by warpech** [comment]
Maybe related: #872

**Comment by sequba** [comment]
When completed, please re-verify https://github.com/handsontable/handsontable/issues/8118.

**Comment by sequba** [comment]
Related: https://github.com/handsontable/hyperformula/issues/1272

**Comment by adrianszymanski89** [comment]
Test based on the initial demo shows significant improvement in the described scenario.

**2.5.0**

Loading time ~ 55s

**2.6.0**

Loading time ~ 11.5s

**Comment by AMBudnik** [comment]
Hi @crystalstone 

I'm more than happy to announce that HyperFormula v2.6.0 is here, and it significantly improves the loading time of the example.

ps. Here https://hyperformula.handsontable.com/guide/release-notes.html#_2-6-0 you can read more about the changes within this version.
