### ISSUE TITLE
null values -> wrong dimensions

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#886]
setting null values 

`hf.setSheetContent(0, [[null, null],[null, null]]);`

result in SheetDimesions [0,0]

null-rows have 0 elements

Is there a way to set "null" as a normal value? Otherwise I have to set a dummy value at the end of each row?

**Comment by MartinDawson** [comment]
What is the use case for needing this?

I checked the code and null values (Empty) are not set in the dependency graph and therefore not counted in sheetWidth & sheetHeight.

This seems correct to me as null is equivalent to Empty.

So the dimensions are correct imo but I need to understand the context first.

**Comment by doczoidberg** [comment]
the use case it for using HF with handsontable. Of course I can also use a workaround if this is not possible with hf by option

**Comment by MartinDawson** [comment]
That's the implementation but not a use case so I still don't understand why it's needed. I presume the use case is that you need to set empty cells in HF for handsontable to render these cells as UI or something. However I use HF in my (non handsontable) spreadsheet and do not need to do this so I'm not sure.

Either way this is not an hyperformula issue but a handsontable issue. Hyperformula is correct here.

**Comment by doczoidberg** [comment]
setting null values and not getting these back is weird IMO. But I have a simple workaround as said
