### ISSUE TITLE
Rename the docs page "Named ranges"

### ISSUE THREAD

**Issue by warpech** [handsontable/hyperformula#890]
### Description

The docs page "Named ranges" is not only about ranges, but also about named expressions, named cells and named constants. 

At least named ranges and named expressions are very useful, so I propose to rename this page to "Named ranges and expressions" or simply "Named expressions" (if expressions entail ranges, etc)

### Links

https://handsontable.github.io/hyperformula/guide/named-ranges.html

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by sequba** [comment]
Fixed by #891
