### ISSUE TITLE
Serious performance drain due to IE11 polyfills for all users of this library

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#896]
This babel config with iE11 support:

```js
targets: {
        chrome: '64',
        firefox: '58',
        ie: '11',
        safari: '11'
      },
```

Change it to this:

```js
targets: {
        chrome: '64',
        firefox: '58',
        safari: '11'
      },
```

It's causing a ~5x slowdown in hyperformula's speed when I tested the `es` bundle output. I imagine the commonjs & dist bundles are even worse. I think this is a critical bug.

I'm running a what-if scenario in my spreadsheet with 10,000 iterations. When I remove ie11 from the aboe it takes 5 seconds. When I add ie11 back it takes 30 seconds. This is due to the extra code for ie11.

However hyperformula should not be bundling the code anyway. Just use something like parcel: https://parceljs.org/ with the target: `library` instead.

And let users of the library bundle their code how they want to, people have different browser support and right now hyperformula is adding a ton of useless code in bundling.

**Comment by warpech** [comment]
Thanks for finding this! It may actually explain some problems listed in #872, #876.

We have the following build targets, as seen in `package.json`:

```
  "module": "es/index.js",
  "main": "commonjs/index.js",
  "jsnext:main": "es/index.js",
  "jsdelivr": "dist/hyperformula.min.js",
  "unpkg": "dist/hyperformula.min.js",
```

I agree that only the `dist` builds (for `<script>` in a browser) should contain the polyfills.

However, it is also interesting for me what exactly causes the IE11 polyfill to hit performance so badly. Maybe we made some engineering choices that are hard for polyfill and we could simplify the critical code path with this in mind. For example, `for ... of` has a bad reputation for polyfilling and we use it in a few places: https://github.com/handsontable/hyperformula/blob/94c3d72c2492daeb2862bd0163c0af88c1465313/src/interpreter/ArithmeticHelper.ts#L314

**Comment by warpech** [comment]
This should be done as part of #1011

**Comment by sequba** [comment]
We removed the polyfills for IE in [HyperFormula 2.1.0](https://github.com/handsontable/hyperformula/releases/tag/2.1.0). The bundle size dropped significantly.
