### ISSUE TITLE
Issue when we divide the variable inside the IF function

### ISSUE THREAD

**Issue by Nithin0000** [handsontable/hyperformula#908]
We have 3 input fields called "valsecurityValue", "loanAmount", "securityValue" and one output field called "Result" for which we are adding value through IF formula in formula.js

formula is:
if valsecurityValue is greater than zero then calculate result from "ROUND((loanAmount*100/valsecurityValue),2)" formula, if it's less or equal to zero then calculate result from ROUND((loanAmount*100)/securityValue,2) formula
i.e
IF((valsecurityValue > '0'), ROUND((loanAmount100/valsecurityValue),2), ROUND((loanAmount100)/securityValue,2))

In the above formula it's throwing an error as "#DIV/0!"

According to me, the value suppose to be calculate based on the condition true or false. But here, it's try to calculate both scenarios values initially only and then try to check the condition at last. Hence In our case even before checking the condition it try to execute both formula where division is happening but zero value is assigned to "valsecurityValue" field.

* HyperFormula version: we are using hot-formula-parse 3.0.1
* Browser Name and version: chrome
* Operating System: windows
![IFError](https://user-images.githubusercontent.com/99805419/154619719-65b40f5f-1d9e-4c06-a8b2-52ba6942c09a.png)

**Comment by MartinDawson** [comment]
IF((valsecurityValue > 0), ROUND((loanAmount100/valsecurityValue),2),
ROUND((loanAmount100)/securityValue,2))

‘0’ is a string

It will always evaluate to false

I believe this is your issue but I need to double check on my pc and not my
iPhone

**Comment by sequba** [comment]
@Nithin0000 Could you paste the code that produced this issue? What values of `valsecurityValue`, `loanAmount` and `securityValue` caused the `#DIV/0!` error?

**Comment by warpech** [comment]
@Nithin0000, in your message you mention names `formula.js` and `hot-formula-parse`, which are other libraries, unrelated to HyperFormula. Closing this as out-of-topic. Please reopen if you I think I was wrong. In that case, please add more details are requested in the comments above
