### ISSUE TITLE
Explain better why getCellDependents & getCellPrecedents return ranges

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#930]
### Description
Some users are confused by this behaviour. The documentation of `getCellDependents` and `getCellPrecedents` methods should be improved.

### Links
#889
#929

### Type of issue
- [x] Other issues, suggestions or ideas

**Comment by warpech** [comment]
Merged into #934

**Comment by sequba** [comment]
A thorough explanation of these functions can be found in the https://handsontable.github.io/hyperformula/guide/dependency-graph.html and API reference for https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#getcelldependents and https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#getcellprecedents.
