### ISSUE TITLE
SUMIF not working on dates

### ISSUE THREAD

**Issue by AJNandi** [handsontable/hyperformula#951]
### Description

SUMIF does not work when dates are included in the conditional values range and the criterion is also a date. It seems to be failing regardless of whether the date has been parsed using dateFormats.

### Steps to reproduce
```
    const engine = HyperFormula.buildFromArray([
      ['1', '4', 43384, '25000'],
      ['2', '2', '11/10/2018', '15000'],
      ['=SUMIF(C1:C3, "11/10/2018" ,D1:D3)']
    ], {dateFormats: ['DD/MM/YYYY']})
    expect(engine.getCellValue(adr('A3'))).toEqual(40000)
```

```
const engine = HyperFormula.buildFromArray([
      ['1', '4', 43384, '25000'],
      ['2', '2', '11/10/2018', '15000'],
      ['=SUMIF(C1:C3, 43384 ,D1:D3)']
    ], {dateFormats: ['DD/MM/YYYY']})
    expect(engine.getCellValue(adr('A3'))).toEqual(40000)
```

Both tests fail with a result of 25000

MBP 2021
macOS 12.3
node v16.13.0
npm v8.1.0

HF version: 1.3.1

Seems like the issue is that DateNumbers are not RawScalarValues from here
https://github.com/handsontable/hyperformula/blob/fd0a40581d1dea2a19c2307228825ad0c3b6dedb/src/interpreter/CriterionFunctionCompute.ts#L160

**Comment by sequba** [comment]
@AJNandi I can confirm it's a bug. It will be fixed in one of the upcoming releases.

**Comment by AJNandi** [comment]
Hi @sequba 

I'm also getting an error on using the match function on computed dates. Wondering if they are related. If not, I can file a separate issue. 

Thanks! 

```
test("Match function on computed dates", () => {
  const engine = HyperFormula.buildFromArray(
    [
      ["1/1/12",         "1/1/12", "=MATCH(B1, A1:A4, 0)"],
      ["=EOMONTH(A1,1)", "2/1/12", "=MATCH(B2, A1:A4, 0)"],
      ["=EOMONTH(A2,1)"],
      ["=EOMONTH(A3,1)"],
    ],
    {
      dateFormats: ["D/M/YY"],
      licenseKey: "gpl-v3",
    }
  );
  expect(engine.getCellValue({ sheet: 0, row: 0, col: 2 })).toEqual(1); // Passes
  expect(engine.getCellValue({ sheet: 0, row: 1, col: 2 })).toEqual(2); // Fails with #N/A
});
```

**Comment by AMBudnik** [comment]
Hi @AJNandi 

We just launched **Hyperformula 2.1.0,** where this issue is fixed. We are closing the issue as solved. 
If you would have any additional questions, please feel free to leave a comment.
