### ISSUE TITLE
Explain 3D range references in the docs

### ISSUE THREAD

**Issue by warpech** [handsontable/hyperformula#952]
### Description

HyperFormula supports 3D range references (ranges spanning across multiple sheets). This is useful in many ways, as presented in multiple advanced Excel tutorials found online, e.g.:

- https://www.ablebits.com/office-addins-blog/2015/12/09/excel-3d-reference-formula/
- https://support.microsoft.com/en-us/office/create-a-3-d-reference-to-the-same-cell-range-on-multiple-worksheets-40ca91ff-9dcb-4ad1-99d2-787d0bc888b6

We should present a viable use case in the Guide. 

I am not sure if the name "3D range reference" is a correct one.

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by krzysztofspilka** [comment]
It's described here https://hyperformula.handsontable.com/guide/cell-references.html#referencing-ranges and since it's a niche feature from the user's perspective, I'm closing this issue.
