### ISSUE TITLE
Docs: document apostrophe as an explicit string literal trigger

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#960]
### Description

It's an undocumented feature

By starting the cell content with `'` character (apostrophe) our parser treats the rest of it as string. It is a way to prevent automatic conversion strings to number, date and time values.

### Links
https://handsoncode.slack.com/archives/C031GBX62SE/p1667382294314379 (internal discussion)
https://github.com/handsontable/hyperformula/discussions/959
https://github.com/handsontable/hyperformula/blob/fd0a40581d1dea2a19c2307228825ad0c3b6dedb/test/CellContentParser.spec.ts#L128-L135

### Type of issue

- [x] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by sequba** [comment]
Possible duplicate: #1087

**Comment by sequba** [comment]
Another question related to that: https://github.com/handsontable/hyperformula/issues/1326

**Comment by AMBudnik** [comment]
Fixed with https://github.com/handsontable/hyperformula/pull/1334 in HyperFormula 2.6.1
