### ISSUE TITLE
[2.0.0] Demo with sorting doesn't work

### ISSUE THREAD

**Issue by aninde** [handsontable/hyperformula#963]
### Description
Sorting doesn't work.
https://handsontable.github.io/hyperformula/guide/sorting-data.html#data-sorting-demo

### Steps to reproduce

1. Open demo.
2. Press the right sorting button
3.  Press the left sorting button.

### Actual result
![Kapture 2022-04-14 at 09 49 02](https://user-images.githubusercontent.com/30186818/163342796-28412e1d-64d3-4724-b639-f25030c29bc6.gif)

### Result in 1.3.0
![Kapture 2022-04-14 at 09 54 13](https://user-images.githubusercontent.com/30186818/163342809-119ba0f4-91b1-442a-b55a-533a417f24b1.gif)

### Demo

https://codesandbox.io/s/aged-forest-ufki1x v1.3.0 working
 https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/2.0.x/sorting?from-embed v2.0.0 broken
### Your environment

* HyperFormula version: 2.0.0
* Browser Name and version: any
* Operating System: macOS 12.2.1 (21D62)

**Comment by sequba** [comment]
Fixed by commit https://github.com/handsontable/hyperformula-demos/commit/b0b84425fd339709ff159891cdc0062740431560.
Codesandbox pulls the code from branch `2.0.x` so it updated automatically. @aninde please verify.

**Comment by aninde** [comment]
It works great, @sequba thank you. I checked on[ LTS Safari 15.3 (17612.4.9.1.8) / mac OS 12.2.1 (21D62](https://app.qase.io/run/HYPER/dashboard/5#)) and on Windows 10 / Edge 100.0.1185.50. 

![Kapture 2022-04-28 at 12 04 03](https://user-images.githubusercontent.com/30186818/165730830-74dc67d1-daec-413c-8106-889745c8b139.gif)

**Comment by sequba** [comment]
Thanks @aninde
