### ISSUE TITLE
Build tooling for comparing performance against other spreadsheet software

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#970]
### Description

We should think of a way to feed HF and Microsoft Excel with the same worksheets and measure the build time.

### Links

https://kb.handsontable.com/pages/resumedraft.action?draftId=56461842&draftShareId=afd03cbf-f20d-4478-b16a-88cb2fd393c8 (internal resource)

**Comment by krzysztofspilka** [comment]
I think it's not necessarily needed at this point. I will close this issue if you don't mind.
