### ISSUE TITLE
Create an example of using HF in a node server

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#972]
### Description

- A similar thing might also be helpful for some specific Handsontable use-cases (according to @AMBudnik )
- It could be in a form of tutorial with code examples
- Nice to have: a working example available publically (something like swagger?)
- A client should be able to download it and run locally
- Kuba S will raise the priority of this task

### Links
- #992
- https://kb.handsontable.com/display/PH/2022/04/13/Hyperformula+demo+training+2022-04-13
- https://docs.google.com/presentation/d/1ACch2e35-3Sdr9Jsy-v_x-2YmN4VLYdu5DsoCSq7vxM/edit#slide=id.g121b144f38b_0_32
- https://github.com/handsontable/hyperformula/discussions/971
- https://handsoncode.slack.com/archives/C031GBX62SE/p1662044500543019 (internal link)

### Type of issue

- [ ] Missing documentation
- [ ] Error in the documentation
- [x] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by warpech** [comment]
I think it is a good idea, we've also briefly discussed it here https://kb.handsontable.com/display/PH/2022/02/16/HyperFormula+onboarding+summary. 

The "microservice" should be kept to minimum, e.g. use basic ExpressJs setup, and the emphasis should be on using a few of the HyperFormula APIs exposed as REST API endpoints.

> Nice to have: a working example available publically (something like swagger?)

I think this is costly to set up and maintain and doesn't have any real benefit. What would it prove?

For me, a GH repo (or a project in https://github.com/handsontable/hyperformula-demos) that one can run locally sounds good.

**Comment by sequba** [comment]
Will be done in scope of https://github.com/handsontable/hyperformula/issues/1277
