### ISSUE TITLE
Test building HyperFormula on different OS and different node versions automatically

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#974]
### Description

Create a way of testing if building works in different environments:
- MacOS
- Windows
- Linux
- different node versions

Should it be run automatically on each PR to develop/master? Or manually before each release?

### Links
- https://handsoncode.slack.com/archives/C031GBX62SE/p1649681545935479 (internal discussion)

**Comment by warpech** [comment]
This can be done using a [workflow matrix](https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs) similarly how to Handsontable: https://github.com/handsontable/handsontable/pull/9403/files

Different Node versions can be added as an additional matrix row.

> Should it be run automatically on each PR to develop/master? Or manually before each release?

Definitely automatically. In my opinion on every commit. It will be a quick workflow.

**Comment by sequba** [comment]
Released with **2.0.1**
