### ISSUE TITLE
setRowOrder with empty rows is returning incorrect order

### ISSUE THREAD

**Issue by AJNandi** [handsontable/hyperformula#989]
### Description

Using setRowOrder with empty rows returns an incorrect order.

```
const hfInstance = HyperFormula.buildFromArray([["apple"], ["bat"], ["car"], [], [], ["a"]]);
hfInstance.setRowOrder(0, [5, 0, 1, 2, 3, 4]);
expect(hfInstance.getSheetSerialized(0)).toBe([["a"], ["apple"], ["bat"], ["car"], [], []]);
```

the new sheet order HF returns is
```
[ [ 'bat' ], [ 'car' ], [], [], [ 'a' ], [ 'apple' ] ]
```

**Comment by AJNandi** [comment]
After inspecting further, it appears that the `newRowOrder` argument is a little unintuitive. 

I had initially assumed that it would be the order of the rows you wish the sheet to now have. (Row 5 first, then row 0, row 1, row 2, etc.) Instead it appears that it requires you to set the value at the index of the array to be the row index you wish it to move to, which is a bit confusing. 

In order to get the above example to work, I would need to pass in `[1, 2, 3, 4, 5, 0]`

Perhaps the documentation could make this more clear.

**Comment by sequba** [comment]
@AJNandi thank you for your feedback. I agree - documentation could be more clear about it. We will improve it shortly.

**Comment by sequba** [comment]
@AJNandi we've just released the new version of API reference for these methods:
- https://hyperformula.handsontable.com/api/classes/hyperformula.html#setroworder
- https://hyperformula.handsontable.com/api/classes/hyperformula.html#setcolumnorder
