### ISSUE TITLE
Document how to import Excel (XLSX) or CSV

### ISSUE THREAD

**Issue by warpech** [handsontable/hyperformula#992]
### Description

Many people ask how they can open Excel documents with HyperFormula. It is not a built-in feature, but it should be possible to use an open source library to convert XLSX to a JS object and then pass it to HyperFormula.

I have some experience from the SV project in converting from XLSX to JS using a library, and I can present it here.

Additionally, issue #911 will inform us how to read and write CSV files, so that should also be reused to create content for the docs page.

### Links
https://handsoncode.slack.com/archives/C031GBX62SE/p1652448983243029 (internal discussion) that explains a real use case in which an app that runs in NodeJS:
1. uses a XLSX "template" made in Excel that contains formulas
2. inserts input from end users into that template
3. evaluates the formulas in the XLSX
4. returns the calculated output

### Type of issue

- [ ] Missing documentation
- [ ] Error in the documentation
- [ ] Request for a demo
- [x] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by warpech** [comment]
I think that our new docs page could show two NodeJS snippets:

- Snippet 1: How to load a simple XLSX file and have it evaluated in HyperFormula
- Snippet 2: How to implement the real use case explained in the OP
    - It could use simple addressing or named expressions to insert the variables
    - The input from end-users can be provided in the simplest form possible (env vars, HTTP GET query string, etc)

I don't think that it is necessary to have code sandboxes with these examples, but if there is time for it, they could be provided as Express server in CodeSandbox, like here: https://codesandbox.io/s/204q4r408j. This server could very simply use HTTP GET query string for the input and raw JSON for the output.

----

For XLSX files parsing, I have experience with the following libraries:
- in SV, I used SheetJS (`js-xlsx` on npm): https://github.com/handsontable/spreadsheet-viewer-dev/blob/3346fe021d875596f8b80a11d93b1471982600e3/src/sv/parse-worker/parse.ts - it is a stable project with a clunky API
- in HF, I used ExcelJS: https://github.com/handsontable/hyperformula/commit/7324387b12dd2e47bd0c33fc577512b92febcfe6 - it is a modern project with a simple API. I would recommend this one for this task

**Comment by sequba** [comment]
> * Snippet 2: How to implement the real use case explained in the OP
>   
>   * It could use simple addressing or named expressions to insert the variables
>   * The input from end-users can be provided in the simplest form possible (env vars, HTTP GET query string, etc)

IMHO Snippet 2 is out of the scope of this task. It would essentially solve https://github.com/handsontable/hyperformula/issues/972.

**Comment by sequba** [comment]
Closing as released in [HyperFormula 2.2.0](https://github.com/handsontable/hyperformula/releases/tag/2.2.0)
