### ISSUE TITLE
Build fails on node 17 & 18

### ISSUE THREAD

**Issue by sequba** [handsontable/hyperformula#996]
### Description

According to [Node documentation](https://nodejs.org/en/about/releases/) in October v18 enters the `ACTIVE` stage of the release cycle and v16 goes into `MAINTENANCE`. We should start using the newest LTS release.

Also - newer node versions should be included in our `build` workflow.

### Steps to reproduce

1. `nvm use v17`
2. `npm install`

### Links

- https://github.com/handsontable/hyperformula/pull/995
- https://github.com/handsontable/hyperformula/pull/995#discussion_r881394724

**Comment by AMBudnik** [comment]
We're able to build HyperFormula 2.7.1 on node v17.
