### ISSUE TITLE
Copy Paste does not copy formula

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#997]
docs say that `copy` copies the cell content: 
https://handsontable.github.io/hyperformula/guide/clipboard-operations.html#paste

I have as content
A1=>  "Content of A1"
B1 =>  "=A1"

when I copy B1 "Content of A1" is copied (and pasted afterwards) and not the formula?

    // cellrange is B1
    var f = this.hf.getCellFormula(cellrange.start); // =A1
    var v = this.hf.getCellValue(cellrange.start);  // ="Content of A1"
    var s = this.hf.getCellSerialized(cellrange.start);  // =A1

    var content = this.hf.copy(cellrange);
    // content should be "=A1" but is "Content of A1"   

there are different docs?
https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#clipboard

https://handsontable.github.io/hyperformula/guide/clipboard-operations.html#copy
seems wrong? wrong parameters in documentation here? `copy` needs one parameter, not 3

first link says it copies the values second says it copies the contents?

**Comment by doczoidberg** [comment]
did something wrong, but 2nd doc link is wrong with 3 parameters

**Comment by sequba** [comment]
Hi @doczoidberg!

You are right. Our guide is outdated and contains inaccurate information. It will be fixed in #998.

Thanks for pointing that out.

**Comment by sequba** [comment]
@doczoidberg We've just released the fixed version of the [Clipboard operations](https://hyperformula.handsontable.com/guide/clipboard-operations.html) guide.
